using System.Globalization;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Storage;
using Npgsql;
using SESS.NexaERP.Application.Common;
using SESS.NexaERP.Application.Masters;
using SESS.NexaERP.Domain.Employees;
using SESS.NexaERP.Domain.Foundation;
using SESS.NexaERP.Domain.Inventory;
using SESS.NexaERP.Domain.Masters;
using SESS.NexaERP.Domain.Stores;
using SESS.NexaERP.Infrastructure.Persistence;

namespace SESS.NexaERP.Infrastructure.MasterData;

internal static class ImportFields
{
    internal static string? V(MasterDataRawRow r,string k)=>r.Values.TryGetValue(k,out var v)?v?.Trim():null;
    internal static string Code(string? v)=>(v??string.Empty).Trim().ToUpperInvariant();
    internal static MasterDataRowError Error(string k,string h,string c,string m,string? v)=>new(k,h,c,m,v);
    internal static void Required(MasterDataRawRow r,string k,string h,List<MasterDataRowError> e){if(string.IsNullOrWhiteSpace(V(r,k)))e.Add(Error(k,h,"REQUIRED",$"{h} is required.",V(r,k)));}
    internal static bool Bool(MasterDataRawRow r,string k,List<MasterDataRowError> e){var v=V(r,k);if(bool.TryParse(v,out var b))return b;e.Add(Error(k,k,"INVALID_VALUE",$"{k} must be TRUE or FALSE.",v));return false;}
    internal static decimal Decimal(MasterDataRawRow r,string k,List<MasterDataRowError> e){var v=V(r,k);if(decimal.TryParse(v,NumberStyles.Number,CultureInfo.InvariantCulture,out var d)&&d>=0)return d;e.Add(Error(k,k,"INVALID_VALUE",$"{k} must be a non-negative invariant decimal.",v));return 0;}
    internal static DateOnly? Date(MasterDataRawRow r,string k,List<MasterDataRowError> e){var v=V(r,k);if(string.IsNullOrWhiteSpace(v))return null;if(DateOnly.TryParseExact(v,"yyyy-MM-dd",CultureInfo.InvariantCulture,DateTimeStyles.None,out var d))return d;e.Add(Error(k,k,"INVALID_VALUE",$"{k} must use YYYY-MM-DD.",v));return null;}
    internal static IReadOnlyList<string> Codes(string? value)=>string.IsNullOrWhiteSpace(value)?[]:value.Split([',',';'],StringSplitOptions.RemoveEmptyEntries|StringSplitOptions.TrimEntries).Select(Code).Distinct(StringComparer.Ordinal).ToArray();
    internal static MasterDataColumnDefinition C(string k,string h,MasterDataColumnType t,bool required,string format,string allowed,string description,string? lookup=null)=>new(k,h,t,required,required,true,format,allowed,lookup,description);
    internal static MasterDataColumnDefinition R(string k,string h,MasterDataColumnType t)=>new(k,h,t,false,false,false,"Read-only","Exported value",null,"Read-only identity, lifecycle or concurrency value.");
    internal static MasterDataExportRow Example(params (string Key,object? Value)[] values)=>new(values.ToDictionary(x=>x.Key,x=>x.Value,StringComparer.Ordinal));
    internal static MasterDataExistingSet Set(IEnumerable<MasterDataExistingRecord> rows)=>new(rows.ToDictionary(x=>x.NormalizedBusinessCode,StringComparer.Ordinal),rows.ToDictionary(x=>x.Id));
}

public sealed class ItemImportDefinition : IMasterDataDefinition
{
    public string MasterKey=>"items"; public int TemplateVersion=>1; public string PageKey=>"masters.items"; public string BusinessCodeColumnKey=>"ItemCode";
    public IReadOnlyList<string> OperationalRolePriority=>["STORES_MANAGER","PURCHASE_MANAGER","TECHNICAL_DIRECTOR","IT_MANAGER"];
    public MasterDataSensitivePermission? SensitiveResultPermission=>null;
    public IReadOnlyList<string> WorkbookGuideNotes=>["Every imported item lands as DRAFT and must be approved before purchase or receipt.","Unknown lookup codes are refused; imports never create categories, UOMs, manufacturers or vendors.","Serial Policy is NONE, SERIAL, BATCH or SHELF_LIFE. Reorder Level may be zero and can be maintained later."];
    public IReadOnlyList<MasterDataColumnDefinition> Columns=>[
        ImportFields.R("RecordId","Record ID",MasterDataColumnType.Guid),ImportFields.R("Version","Version",MasterDataColumnType.UnsignedInteger),
        ImportFields.C("ItemCode","Item Code",MasterDataColumnType.Text,true,"Uppercase text","Unique item code","Immutable item code"),
        ImportFields.C("Name","Item Name",MasterDataColumnType.Text,true,"Text","Non-blank","Item description"),ImportFields.C("ItemType","Item Type",MasterDataColumnType.Text,true,"Uppercase code","RAW_MATERIAL, COMPONENT, CONSUMABLE, SPARE, FINISHED_MACHINE, TOOL, SERVICE_ITEM, NON_STOCK","Inventory behavior"),ImportFields.C("IsReturnable","Is Returnable",MasterDataColumnType.Boolean,true,"TRUE or FALSE","TRUE or FALSE","Returnability"),
        ImportFields.C("HsnSacCode","HSN / SAC Code",MasterDataColumnType.Text,true,"Text","Valid business HSN/SAC","Tax classification"),
        ImportFields.C("GstPercentage","GST Rate",MasterDataColumnType.Decimal,true,"Invariant decimal","0 or greater","GST percentage"),
        ImportFields.C("UomCode","UOM Code",MasterDataColumnType.Text,true,"Uppercase code","Existing active UOM","Base UOM","uoms"),
        ImportFields.C("CategoryCode","Category Code",MasterDataColumnType.Text,true,"Uppercase code","Existing active category","Item category","item-categories"),
        ImportFields.C("SubcategoryCode","Subcategory Code",MasterDataColumnType.Text,false,"Uppercase code","Existing subcategory of Category","Item subcategory","item-subcategories"),
        ImportFields.C("ManufacturerCode","Manufacturer Code",MasterDataColumnType.Text,false,"Uppercase code","Existing active manufacturer","Manufacturer","manufacturers"),
        ImportFields.C("PreferredVendorCode","Preferred Vendor Code",MasterDataColumnType.Text,false,"Uppercase code","Existing active vendor","Preferred vendor","vendors"),
        ImportFields.C("SerialPolicy","Serial Policy",MasterDataColumnType.Text,true,"Uppercase code","NONE, SERIAL, BATCH, SHELF_LIFE","Tracking policy"),
        ImportFields.C("ReorderLevel","Reorder Level",MasterDataColumnType.Decimal,true,"Non-negative decimal","0 or greater","Reorder threshold"),
        ImportFields.R("Status","Status",MasterDataColumnType.Text),ImportFields.R("ApprovalStatus","Approval Status",MasterDataColumnType.Text)];
    public IReadOnlyList<MasterDataExportRow> TemplateExampleRows=>[ImportFields.Example(("ItemCode","EXAMPLE-001"),("Name","Example temperature sensor"),("ItemType","COMPONENT"),("IsReturnable",true),("HsnSacCode","90251990"),("GstPercentage",18m),("UomCode","NOS"),("CategoryCode","SENSOR"),("SubcategoryCode","TEMPERATURE"),("ManufacturerCode","EXAMPLE-MAKE"),("PreferredVendorCode","VENDOR-001"),("SerialPolicy","SERIAL"),("ReorderLevel",5m))];
}

internal sealed record ItemLookup(Dictionary<string,Guid> Uoms,Dictionary<string,Guid> Categories,Dictionary<string,(Guid Id,Guid CategoryId)> Subcategories,Dictionary<string,Guid> Manufacturers,Dictionary<string,Guid> Vendors);

public sealed class ItemMasterDataAdapter(NexaErpDbContext db,ICurrentUser user) : IMasterDataAdapter
{
    public IMasterDataDefinition Definition {get;}=new ItemImportDefinition(); public string NormalizeBusinessCode(string v)=>ImportFields.Code(v);
    public async Task<IReadOnlyList<MasterDataExportRow>> ExportAsync(MasterDataExportQuery q,CancellationToken ct)=>await db.Items.AsNoTracking().OrderBy(x=>x.ItemCode).Select(x=>new MasterDataExportRow(new Dictionary<string,object?>{{"RecordId",x.Id},{"Version",x.Version},{"ItemCode",x.ItemCode},{"Name",x.Name},{"ItemType",x.ItemType},{"IsReturnable",x.IsReturnable},{"HsnSacCode",x.HsnSacCode},{"GstPercentage",x.GstPercentage},{"UomCode",x.Uom},{"CategoryCode",x.Category==null?null:x.Category.Code},{"SubcategoryCode",x.Subcategory==null?null:x.Subcategory.Code},{"ManufacturerCode",x.Manufacturer==null?null:x.Manufacturer.Code},{"PreferredVendorCode",x.PreferredVendor==null?null:x.PreferredVendor.VendorCode},{"SerialPolicy",x.SerialNumberTracking?"SERIAL":x.BatchTracking?"BATCH":x.ShelfLifeTracking?"SHELF_LIFE":"NONE"},{"ReorderLevel",x.ReorderLevel},{"Status",x.Status},{"ApprovalStatus",x.ApprovalStatus}})).ToListAsync(ct);
    public async Task<MasterDataExistingSet> LoadExistingAsync(IReadOnlyCollection<string> codes,IReadOnlyCollection<Guid> ids,CancellationToken ct){var rows=await db.Items.AsNoTracking().Where(x=>codes.Contains(x.ItemCode)||ids.Contains(x.Id)).Select(x=>new MasterDataExistingRecord(x.Id,x.ItemCode,x.ItemCode,x.Version,new Dictionary<string,string?>{{"ItemCode",x.ItemCode},{"Name",x.Name},{"ItemType",x.ItemType},{"IsReturnable",x.IsReturnable.ToString()},{"HsnSacCode",x.HsnSacCode},{"GstPercentage",x.GstPercentage.ToString(CultureInfo.InvariantCulture)},{"UomCode",x.Uom},{"ReorderLevel",x.ReorderLevel.ToString(CultureInfo.InvariantCulture)},{"Status",x.Status},{"ApprovalStatus",x.ApprovalStatus}})).ToListAsync(ct);return ImportFields.Set(rows);}
    public async Task<object?> LoadLookupContextAsync(IReadOnlyList<MasterDataRawRow> rows,CancellationToken ct)=>new ItemLookup(await db.Uoms.Where(x=>x.IsActive).ToDictionaryAsync(x=>x.Code,x=>x.Id,ct),await db.ItemCategories.Where(x=>x.IsActive).ToDictionaryAsync(x=>x.Code,x=>x.Id,ct),await db.ItemSubcategories.Where(x=>x.IsActive).ToDictionaryAsync(x=>x.Code,x=>new ValueTuple<Guid,Guid>(x.Id,x.CategoryId),ct),await db.Manufacturers.Where(x=>x.IsActive).ToDictionaryAsync(x=>x.Code,x=>x.Id,ct),await db.Vendors.Where(x=>x.IsActive).ToDictionaryAsync(x=>x.VendorCode,x=>x.Id,ct));
    public IReadOnlyList<MasterDataRowError> Validate(MasterDataRawRow r,MasterDataExistingRecord? existing,object? context){var e=new List<MasterDataRowError>();foreach(var x in new[]{("ItemCode","Item Code"),("Name","Item Name"),("ItemType","Item Type"),("IsReturnable","Is Returnable"),("HsnSacCode","HSN / SAC Code"),("UomCode","UOM Code"),("CategoryCode","Category Code"),("SerialPolicy","Serial Policy"),("ReorderLevel","Reorder Level")})ImportFields.Required(r,x.Item1,x.Item2,e);ImportFields.Bool(r,"IsReturnable",e);ImportFields.Decimal(r,"GstPercentage",e);ImportFields.Decimal(r,"ReorderLevel",e);var itemType=ImportFields.Code(ImportFields.V(r,"ItemType"));if(!ItemTypes.All.Contains(itemType))e.Add(ImportFields.Error("ItemType","Item Type","INVALID_VALUE","Use a documented item type.",itemType));var policy=ImportFields.Code(ImportFields.V(r,"SerialPolicy"));if(!new[]{"NONE","SERIAL","BATCH","SHELF_LIFE"}.Contains(policy))e.Add(ImportFields.Error("SerialPolicy","Serial Policy","INVALID_VALUE","Use NONE, SERIAL, BATCH or SHELF_LIFE.",policy));if(context is ItemLookup l){Check(l.Uoms,"UomCode","UOM Code",true);Check(l.Categories,"CategoryCode","Category Code",true);Check(l.Manufacturers,"ManufacturerCode","Manufacturer Code",false);Check(l.Vendors,"PreferredVendorCode","Preferred Vendor Code",false);var sub=ImportFields.Code(ImportFields.V(r,"SubcategoryCode"));if(sub.Length>0&&(!l.Subcategories.TryGetValue(sub,out var s)||!l.Categories.TryGetValue(ImportFields.Code(ImportFields.V(r,"CategoryCode")),out var c)||s.CategoryId!=c))e.Add(ImportFields.Error("SubcategoryCode","Subcategory Code","LOOKUP_NOT_FOUND","Subcategory was not found under the selected category.",sub));void Check(Dictionary<string,Guid> d,string k,string h,bool req){var v=ImportFields.Code(ImportFields.V(r,k));if((req||v.Length>0)&&!d.ContainsKey(v))e.Add(ImportFields.Error(k,h,"LOOKUP_NOT_FOUND",$"Active {h} was not found.",v));}}if(existing is not null&&existing.MaterialValues.TryGetValue("Status",out var status)&&status!="DRAFT")e.Add(ImportFields.Error("ItemCode","Item Code","GOVERNED_RECORD","Only Draft items may be changed by import.",existing.BusinessCode));return e;}
    public bool IsMateriallyEqual(MasterDataRawRow r,MasterDataExistingRecord x)=>false;
    public async Task<MasterDataApplyResult> CreateAsync(MasterDataRawRow r,CancellationToken ct){var l=(ItemLookup)(await LoadLookupContextAsync([r],ct))!;var item=new Item{ItemCode=ImportFields.Code(ImportFields.V(r,"ItemCode")),Name=ImportFields.V(r,"Name")!,DetailedDescription=ImportFields.V(r,"Name")!,ItemType=ImportFields.Code(ImportFields.V(r,"ItemType")),MaterialType=ImportFields.Code(ImportFields.V(r,"CategoryCode")),IsReturnable=bool.Parse(ImportFields.V(r,"IsReturnable")!),HsnSacCode=ImportFields.V(r,"HsnSacCode"),GstPercentage=decimal.Parse(ImportFields.V(r,"GstPercentage")!,CultureInfo.InvariantCulture),Uom=ImportFields.Code(ImportFields.V(r,"UomCode")),UomId=l.Uoms[ImportFields.Code(ImportFields.V(r,"UomCode"))],BaseUomId=l.Uoms[ImportFields.Code(ImportFields.V(r,"UomCode"))],CategoryId=l.Categories[ImportFields.Code(ImportFields.V(r,"CategoryCode"))],SubcategoryId=Id(l.Subcategories,ImportFields.V(r,"SubcategoryCode")),ManufacturerId=Id(l.Manufacturers,ImportFields.V(r,"ManufacturerCode")),PreferredVendorId=Id(l.Vendors,ImportFields.V(r,"PreferredVendorCode")),ReorderLevel=decimal.Parse(ImportFields.V(r,"ReorderLevel")!,CultureInfo.InvariantCulture),Status=MasterStatuses.Draft,ApprovalStatus=MasterApprovalStatuses.Draft,IsActive=true,CreatedBy=user.LoginId};SetPolicy(item,ImportFields.Code(ImportFields.V(r,"SerialPolicy")));db.Items.Add(item);await db.SaveChangesAsync(ct);return new(item.Id,item.Version);}
    public async Task<MasterDataApplyResult> UpdateAsync(MasterDataExistingRecord x,MasterDataRawRow r,uint version,CancellationToken ct){var item=await db.Items.SingleAsync(y=>y.Id==x.Id&&y.Version==version,ct);var l=(ItemLookup)(await LoadLookupContextAsync([r],ct))!;item.Name=ImportFields.V(r,"Name")!;item.DetailedDescription=item.Name;item.ItemType=ImportFields.Code(ImportFields.V(r,"ItemType"));item.MaterialType=ImportFields.Code(ImportFields.V(r,"CategoryCode"));item.IsReturnable=bool.Parse(ImportFields.V(r,"IsReturnable")!);item.HsnSacCode=ImportFields.V(r,"HsnSacCode");item.GstPercentage=decimal.Parse(ImportFields.V(r,"GstPercentage")!,CultureInfo.InvariantCulture);item.Uom=ImportFields.Code(ImportFields.V(r,"UomCode"));item.UomId=item.BaseUomId=l.Uoms[item.Uom];item.CategoryId=l.Categories[ImportFields.Code(ImportFields.V(r,"CategoryCode"))];item.SubcategoryId=Id(l.Subcategories,ImportFields.V(r,"SubcategoryCode"));item.ManufacturerId=Id(l.Manufacturers,ImportFields.V(r,"ManufacturerCode"));item.PreferredVendorId=Id(l.Vendors,ImportFields.V(r,"PreferredVendorCode"));item.ReorderLevel=decimal.Parse(ImportFields.V(r,"ReorderLevel")!,CultureInfo.InvariantCulture);item.UpdatedAt=DateTimeOffset.UtcNow;item.UpdatedBy=user.LoginId;SetPolicy(item,ImportFields.Code(ImportFields.V(r,"SerialPolicy")));await db.SaveChangesAsync(ct);return new(item.Id,item.Version);}
    private static Guid? Id(Dictionary<string,Guid> d,string? v)=>d.TryGetValue(ImportFields.Code(v),out var id)?id:null;private static Guid? Id(Dictionary<string,(Guid Id,Guid CategoryId)> d,string? v)=>d.TryGetValue(ImportFields.Code(v),out var x)?x.Id:null;private static void SetPolicy(Item i,string p){i.SerialNumberTracking=p=="SERIAL";i.BatchTracking=p=="BATCH";i.ShelfLifeTracking=p=="SHELF_LIFE";}
}

public sealed class EmployeeImportDefinition : IMasterDataDefinition
{
    public string MasterKey=>"employees";public int TemplateVersion=>1;public string PageKey=>"employees.master";public string BusinessCodeColumnKey=>"EmployeeCode";
    public IReadOnlyList<string> OperationalRolePriority=>["IT_MANAGER","TECHNICAL_DIRECTOR","MANAGING_DIRECTOR"];
    public MasterDataSensitivePermission? SensitiveResultPermission=>null;
    public IReadOnlyList<string> WorkbookGuideNotes=>["Company Assignments is a comma-separated list of existing company codes.","Import never creates an identity, password or login. Login Enabled is always FALSE.","Unknown departments, designations or companies are refused; spelling variants are not created."];
    public IReadOnlyList<MasterDataColumnDefinition> Columns=>[ImportFields.R("RecordId","Record ID",MasterDataColumnType.Guid),ImportFields.R("Version","Version",MasterDataColumnType.UnsignedInteger),ImportFields.C("EmployeeCode","Employee Code",MasterDataColumnType.Text,true,"Uppercase text","Unique employee code","Immutable employee code"),ImportFields.C("EmployeeName","Employee Name",MasterDataColumnType.Text,true,"Text","Non-blank","Official employee name"),ImportFields.C("DepartmentCode","Department Code",MasterDataColumnType.Text,true,"Uppercase code","Existing department only","Department","departments"),ImportFields.C("DesignationCode","Designation Code",MasterDataColumnType.Text,true,"Uppercase code","Existing designation only","Designation","designations"),ImportFields.C("JoiningDate","Joining Date",MasterDataColumnType.Date,true,"YYYY-MM-DD","Valid date","Employment joining date"),ImportFields.C("CompanyAssignments","Company Assignments",MasterDataColumnType.Text,true,"Comma-separated company codes","Existing active companies","Employment companies","companies"),ImportFields.R("LoginEnabled","Login Enabled",MasterDataColumnType.Boolean)];
    public IReadOnlyList<MasterDataExportRow> TemplateExampleRows=>[ImportFields.Example(("EmployeeCode","SESS-99"),("EmployeeName","Example Employee"),("DepartmentCode","PRODUCTION"),("DesignationCode","ENGINEER"),("JoiningDate","2026-09-01"),("CompanyAssignments","SESS_PVT_LTD, SESS_PROPRIETORSHIP"),("LoginEnabled",false))];
}
internal sealed record EmployeeLookup(Dictionary<string,Guid> Departments,Dictionary<string,Guid> Designations,Dictionary<string,Guid> Companies);
public sealed class EmployeeMasterDataAdapter(NexaErpDbContext db,ICurrentUser user):IMasterDataAdapter
{
    public IMasterDataDefinition Definition{get;}=new EmployeeImportDefinition();public string NormalizeBusinessCode(string v)=>ImportFields.Code(v);
    public async Task<IReadOnlyList<MasterDataExportRow>> ExportAsync(MasterDataExportQuery q,CancellationToken ct)
    {
        var company=await db.Companies.Where(x=>x.Code==user.OrganizationId).Select(x=>x.Id).SingleAsync(ct);
        var employeeIds=await db.EmployeeCompanyAssignments.AsNoTracking().Where(x=>x.CompanyId==company&&x.IsActive).Select(x=>x.EmployeeId).Distinct().ToListAsync(ct);
        var employees=await db.Employees.AsNoTracking().Include(x=>x.Department).Include(x=>x.Designation).Where(x=>employeeIds.Contains(x.Id)).OrderBy(x=>x.EmployeeCode).ToListAsync(ct);
        var companyCodes=await db.EmployeeCompanyAssignments.AsNoTracking().Where(x=>employeeIds.Contains(x.EmployeeId)&&x.IsActive).Join(db.Companies,a=>a.CompanyId,c=>c.Id,(a,c)=>new{a.EmployeeId,c.Code}).ToListAsync(ct);
        return employees.Select(x=>new MasterDataExportRow(new Dictionary<string,object?>{{"RecordId",x.Id},{"Version",x.Version},{"EmployeeCode",x.EmployeeCode},{"EmployeeName",x.EmployeeName},{"DepartmentCode",x.Department?.Code},{"DesignationCode",x.Designation?.Code},{"JoiningDate",x.DateOfJoining},{"CompanyAssignments",string.Join(", ",companyCodes.Where(c=>c.EmployeeId==x.Id).Select(c=>c.Code).OrderBy(c=>c))},{"LoginEnabled",x.LoginEnabled}})).ToArray();
    }
    public async Task<MasterDataExistingSet> LoadExistingAsync(IReadOnlyCollection<string> codes,IReadOnlyCollection<Guid> ids,CancellationToken ct){var rows=await db.Employees.AsNoTracking().Where(x=>codes.Contains(x.EmployeeCode)||ids.Contains(x.Id)).Select(x=>new MasterDataExistingRecord(x.Id,x.EmployeeCode,x.EmployeeCode,x.Version,new Dictionary<string,string?>{{"EmployeeCode",x.EmployeeCode},{"EmployeeName",x.EmployeeName},{"JoiningDate",x.DateOfJoining==null?null:x.DateOfJoining.Value.ToString("yyyy-MM-dd")},{"LoginEnabled",x.LoginEnabled.ToString()}})).ToListAsync(ct);return ImportFields.Set(rows);}
    public async Task<object?> LoadLookupContextAsync(IReadOnlyList<MasterDataRawRow> rows,CancellationToken ct)=>new EmployeeLookup(await db.Departments.Where(x=>x.IsActive).ToDictionaryAsync(x=>x.Code,x=>x.Id,ct),await db.Designations.Where(x=>x.IsActive).ToDictionaryAsync(x=>x.Code,x=>x.Id,ct),await db.Companies.Where(x=>x.IsActive).ToDictionaryAsync(x=>x.Code,x=>x.Id,ct));
    public IReadOnlyList<MasterDataRowError> Validate(MasterDataRawRow r,MasterDataExistingRecord? x,object? context){var e=new List<MasterDataRowError>();foreach(var f in new[]{("EmployeeCode","Employee Code"),("EmployeeName","Employee Name"),("DepartmentCode","Department Code"),("DesignationCode","Designation Code"),("JoiningDate","Joining Date"),("CompanyAssignments","Company Assignments")})ImportFields.Required(r,f.Item1,f.Item2,e);ImportFields.Date(r,"JoiningDate",e);if(context is EmployeeLookup l){Check(l.Departments,"DepartmentCode","Department");Check(l.Designations,"DesignationCode","Designation");var companies=ImportFields.Codes(ImportFields.V(r,"CompanyAssignments"));foreach(var c in companies)if(!l.Companies.ContainsKey(c))e.Add(ImportFields.Error("CompanyAssignments","Company Assignments","LOOKUP_NOT_FOUND",$"Unknown company '{c}'.",c));void Check(Dictionary<string,Guid>d,string k,string h){var v=ImportFields.Code(ImportFields.V(r,k));if(v.Length>0&&!d.ContainsKey(v))e.Add(ImportFields.Error(k,h+" Code","LOOKUP_NOT_FOUND",$"Unknown {h.ToLowerInvariant()} '{v}'.",v));}}if(!string.IsNullOrWhiteSpace(ImportFields.V(r,"LoginEnabled"))&&ImportFields.V(r,"LoginEnabled")!.ToUpperInvariant()!="FALSE")e.Add(ImportFields.Error("LoginEnabled","Login Enabled","GOVERNED_FIELD","Employee import cannot create identities or enable login.",ImportFields.V(r,"LoginEnabled")));return e;}
    public bool IsMateriallyEqual(MasterDataRawRow r,MasterDataExistingRecord x)=>false;
    public async Task<MasterDataApplyResult> CreateAsync(MasterDataRawRow r,CancellationToken ct){var l=(EmployeeLookup)(await LoadLookupContextAsync([r],ct))!;var code=ImportFields.Code(ImportFields.V(r,"EmployeeCode"));var employee=new Employee{EmployeeCode=code,EmployeeName=ImportFields.V(r,"EmployeeName")!,OriginalImportedName=ImportFields.V(r,"EmployeeName")!,EmployeeType="PERMANENT",Grade="STAFF",DepartmentId=l.Departments[ImportFields.Code(ImportFields.V(r,"DepartmentCode"))],DesignationId=l.Designations[ImportFields.Code(ImportFields.V(r,"DesignationCode"))],DateOfJoining=DateOnly.ParseExact(ImportFields.V(r,"JoiningDate")!,"yyyy-MM-dd",CultureInfo.InvariantCulture),Status="Active",ApprovalStatus="Draft",LoginEnabled=false,IsEmployeeCodeLocked=true,CreatedBy=user.LoginId};db.Employees.Add(employee);foreach(var c in ImportFields.Codes(ImportFields.V(r,"CompanyAssignments")))db.EmployeeCompanyAssignments.Add(new EmployeeCompanyAssignment{EmployeeId=employee.Id,CompanyId=l.Companies[c],EmployeeCode=code,AssignmentType="PAYROLL",EmploymentType="PERMANENT",EffectiveFrom=employee.DateOfJoining!.Value,Status="ACTIVE",IsActive=true,CreatedBy=user.LoginId});await db.SaveChangesAsync(ct);return new(employee.Id,employee.Version);}
    public async Task<MasterDataApplyResult> UpdateAsync(MasterDataExistingRecord x,MasterDataRawRow r,uint v,CancellationToken ct){var l=(EmployeeLookup)(await LoadLookupContextAsync([r],ct))!;var employee=await db.Employees.SingleAsync(y=>y.Id==x.Id&&y.Version==v,ct);employee.EmployeeName=ImportFields.V(r,"EmployeeName")!;employee.DepartmentId=l.Departments[ImportFields.Code(ImportFields.V(r,"DepartmentCode"))];employee.DesignationId=l.Designations[ImportFields.Code(ImportFields.V(r,"DesignationCode"))];employee.DateOfJoining=DateOnly.ParseExact(ImportFields.V(r,"JoiningDate")!,"yyyy-MM-dd",CultureInfo.InvariantCulture);employee.UpdatedAt=DateTimeOffset.UtcNow;employee.UpdatedBy=user.LoginId;var existing=await db.EmployeeCompanyAssignments.Where(a=>a.EmployeeId==employee.Id&&a.IsActive).Select(a=>a.CompanyId).ToListAsync(ct);foreach(var c in ImportFields.Codes(ImportFields.V(r,"CompanyAssignments"))){var id=l.Companies[c];if(!existing.Contains(id))db.EmployeeCompanyAssignments.Add(new EmployeeCompanyAssignment{EmployeeId=employee.Id,CompanyId=id,EmployeeCode=employee.EmployeeCode,AssignmentType="PAYROLL",EmploymentType="PERMANENT",EffectiveFrom=employee.DateOfJoining.Value,Status="ACTIVE",IsActive=true,CreatedBy=user.LoginId});}await db.SaveChangesAsync(ct);return new(employee.Id,employee.Version);}
}

public sealed class ItemVendorImportDefinition:IMasterDataDefinition
{
    public string MasterKey=>"item-vendors";public int TemplateVersion=>1;public string PageKey=>"masters.items";public string BusinessCodeColumnKey=>"LinkCode";public IReadOnlyList<string> OperationalRolePriority=>["PURCHASE_MANAGER","STORES_MANAGER","TECHNICAL_DIRECTOR"];public MasterDataSensitivePermission? SensitiveResultPermission=>null;public IReadOnlyList<string> WorkbookGuideNotes=>["Link Code must be ITEMCODE|VENDORCODE and is immutable.","Both item and vendor must already exist and be active."];
    public IReadOnlyList<MasterDataColumnDefinition> Columns=>[ImportFields.R("RecordId","Record ID",MasterDataColumnType.Guid),ImportFields.R("Version","Version",MasterDataColumnType.UnsignedInteger),ImportFields.C("LinkCode","Link Code",MasterDataColumnType.Text,true,"ITEM|VENDOR","Unique pair","Stable pair key"),ImportFields.C("ItemCode","Item Code",MasterDataColumnType.Text,true,"Uppercase code","Existing active item","Item","items"),ImportFields.C("VendorCode","Vendor Code",MasterDataColumnType.Text,true,"Uppercase code","Existing active vendor","Vendor","vendors")];public IReadOnlyList<MasterDataExportRow> TemplateExampleRows=>[ImportFields.Example(("LinkCode","ITEM-001|VENDOR-001"),("ItemCode","ITEM-001"),("VendorCode","VENDOR-001"))];
}
internal sealed record ItemVendorLookup(Dictionary<string,Guid> Items,Dictionary<string,Guid> Vendors);
public sealed class ItemVendorMasterDataAdapter(NexaErpDbContext db,ICurrentUser user):IMasterDataAdapter
{
    public IMasterDataDefinition Definition{get;}=new ItemVendorImportDefinition();public string NormalizeBusinessCode(string v)=>ImportFields.Code(v);
    public async Task<IReadOnlyList<MasterDataExportRow>> ExportAsync(MasterDataExportQuery q,CancellationToken ct)=>await db.ItemVendors.AsNoTracking().OrderBy(x=>x.Item!.ItemCode).ThenBy(x=>x.Vendor!.VendorCode).Select(x=>new MasterDataExportRow(new Dictionary<string,object?>{{"RecordId",x.Id},{"Version",x.Version},{"LinkCode",x.Item!.ItemCode+"|"+x.Vendor!.VendorCode},{"ItemCode",x.Item.ItemCode},{"VendorCode",x.Vendor.VendorCode}})).ToListAsync(ct);
    public async Task<MasterDataExistingSet> LoadExistingAsync(IReadOnlyCollection<string> codes,IReadOnlyCollection<Guid> ids,CancellationToken ct){var all=await db.ItemVendors.AsNoTracking().Where(x=>ids.Contains(x.Id)||codes.Contains(x.Item!.ItemCode+"|"+x.Vendor!.VendorCode)).Select(x=>new MasterDataExistingRecord(x.Id,x.Item!.ItemCode+"|"+x.Vendor!.VendorCode,x.Item.ItemCode+"|"+x.Vendor.VendorCode,x.Version,new Dictionary<string,string?>{{"ItemCode",x.Item.ItemCode},{"VendorCode",x.Vendor.VendorCode}})).ToListAsync(ct);return ImportFields.Set(all);}
    public async Task<object?> LoadLookupContextAsync(IReadOnlyList<MasterDataRawRow> r,CancellationToken ct)=>new ItemVendorLookup(await db.Items.Where(x=>x.IsActive).ToDictionaryAsync(x=>x.ItemCode,x=>x.Id,ct),await db.Vendors.Where(x=>x.IsActive).ToDictionaryAsync(x=>x.VendorCode,x=>x.Id,ct));
    public IReadOnlyList<MasterDataRowError> Validate(MasterDataRawRow r,MasterDataExistingRecord? x,object? context){var e=new List<MasterDataRowError>();foreach(var f in new[]{("LinkCode","Link Code"),("ItemCode","Item Code"),("VendorCode","Vendor Code")})ImportFields.Required(r,f.Item1,f.Item2,e);var item=ImportFields.Code(ImportFields.V(r,"ItemCode"));var vendor=ImportFields.Code(ImportFields.V(r,"VendorCode"));if(ImportFields.Code(ImportFields.V(r,"LinkCode"))!=item+"|"+vendor)e.Add(ImportFields.Error("LinkCode","Link Code","PAIR_MISMATCH","Link Code must equal ITEMCODE|VENDORCODE.",ImportFields.V(r,"LinkCode")));if(context is ItemVendorLookup l){if(!l.Items.ContainsKey(item))e.Add(ImportFields.Error("ItemCode","Item Code","LOOKUP_NOT_FOUND","Active item was not found.",item));if(!l.Vendors.ContainsKey(vendor))e.Add(ImportFields.Error("VendorCode","Vendor Code","LOOKUP_NOT_FOUND","Active vendor was not found.",vendor));}return e;}public bool IsMateriallyEqual(MasterDataRawRow r,MasterDataExistingRecord x)=>true;
    public async Task<MasterDataApplyResult> CreateAsync(MasterDataRawRow r,CancellationToken ct){var l=(ItemVendorLookup)(await LoadLookupContextAsync([r],ct))!;var link=new ItemVendor{ItemId=l.Items[ImportFields.Code(ImportFields.V(r,"ItemCode"))],VendorId=l.Vendors[ImportFields.Code(ImportFields.V(r,"VendorCode"))],CreatedBy=user.LoginId};db.ItemVendors.Add(link);await db.SaveChangesAsync(ct);return new(link.Id,link.Version);}public Task<MasterDataApplyResult> UpdateAsync(MasterDataExistingRecord x,MasterDataRawRow r,uint v,CancellationToken ct)=>Task.FromResult(new MasterDataApplyResult(x.Id,x.Version));
}

public sealed class OpeningStockImportDefinition:IMasterDataDefinition
{
    public string MasterKey=>"opening-stock";public int TemplateVersion=>1;public string PageKey=>"stores.opening-stock";public string BusinessCodeColumnKey=>"LineReference";public IReadOnlyList<string> OperationalRolePriority=>["STORES_MANAGER","ACCOUNTS_MANAGER","TECHNICAL_DIRECTOR"];public MasterDataSensitivePermission? SensitiveResultPermission=>null;
    public IReadOnlyList<string> WorkbookGuideNotes=>["Import validates and stages rows only. It never posts stock; Item 13 requires separate Stores count, Accounts valuation and Technical Director authorization.","Rack Bin is mandatory because the legacy export has no rack data.","Rate is authoritative. Stated legacy value is deliberately omitted and is recomputed as Quantity x Rate.","Negative quantity is refused. Correct the source row to zero or a positive quantity before import.","Each company is imported separately under the selected company session."];
    public IReadOnlyList<MasterDataColumnDefinition> Columns=>[ImportFields.C("LineReference","Line Reference",MasterDataColumnType.Text,true,"Unique text","Unique within workbook","Stable operator row reference"),ImportFields.C("ItemCode","Item Code",MasterDataColumnType.Text,true,"Uppercase code","Approved active item","Stock item","items"),ImportFields.C("WarehouseCode","Warehouse Code",MasterDataColumnType.Text,true,"Uppercase code","Active company warehouse","Warehouse","warehouses"),ImportFields.C("RackBinCode","Rack Bin Code",MasterDataColumnType.Text,true,"Uppercase code","Active bin in warehouse","Mandatory physical rack/bin","rack-bins"),ImportFields.C("LotNumber","Lot Number",MasterDataColumnType.Text,false,"Text","Required for batch-tracked item","Opening lot"),ImportFields.C("SerialNumber","Serial Number",MasterDataColumnType.Text,false,"Text","Required for serial-tracked item","Opening serial"),ImportFields.C("Quantity","Quantity",MasterDataColumnType.Decimal,true,"Positive decimal","Greater than zero","Opening quantity"),ImportFields.C("Rate","Rate",MasterDataColumnType.Decimal,true,"Non-negative rupee decimal","Zero or greater","Landed-cost basis unit rate")];
    public IReadOnlyList<MasterDataExportRow> TemplateExampleRows=>[ImportFields.Example(("LineReference","OPEN-0001"),("ItemCode","ITEM-001"),("WarehouseCode","MAIN"),("RackBinCode","RACK-01-A"),("LotNumber","LOT-2026-001"),("SerialNumber","SN-000001"),("Quantity",1m),("Rate",1250.00m))];
}
internal sealed record OpeningStockLookup(Dictionary<string,(bool Serial,bool Batch)> Items,Dictionary<string,Guid> Warehouses,Dictionary<string,(Guid WarehouseId,bool Active)> Bins);
public sealed class OpeningStockMasterDataAdapter(NexaErpDbContext db,ICurrentUser user):IMasterDataAdapter
{
    public IMasterDataDefinition Definition{get;}=new OpeningStockImportDefinition();public string NormalizeBusinessCode(string v)=>ImportFields.Code(v);public Task<IReadOnlyList<MasterDataExportRow>> ExportAsync(MasterDataExportQuery q,CancellationToken ct)=>Task.FromResult<IReadOnlyList<MasterDataExportRow>>([]);public Task<MasterDataExistingSet> LoadExistingAsync(IReadOnlyCollection<string> c,IReadOnlyCollection<Guid> i,CancellationToken ct)=>Task.FromResult(new MasterDataExistingSet(new Dictionary<string,MasterDataExistingRecord>(),new Dictionary<Guid,MasterDataExistingRecord>()));
    public async Task<object?> LoadLookupContextAsync(IReadOnlyList<MasterDataRawRow> r,CancellationToken ct){var company=await db.Companies.Where(x=>x.Code==user.OrganizationId&&x.IsActive).Select(x=>x.Id).SingleAsync(ct);return new OpeningStockLookup(await db.Items.Where(x=>x.IsActive&&x.ApprovalStatus==MasterApprovalStatuses.Approved).ToDictionaryAsync(x=>x.ItemCode,x=>new ValueTuple<bool,bool>(x.SerialNumberTracking,x.BatchTracking),ct),await db.Warehouses.Where(x=>x.CompanyId==company&&x.IsActive).ToDictionaryAsync(x=>x.WarehouseCode,x=>x.Id,ct),await db.RackBins.Where(x=>x.CompanyId==company).ToDictionaryAsync(x=>x.BinCode,x=>new ValueTuple<Guid,bool>(x.WarehouseId,x.IsActive),ct));}
    public IReadOnlyList<MasterDataRowError> Validate(MasterDataRawRow r,MasterDataExistingRecord? x,object? context){var e=new List<MasterDataRowError>();foreach(var f in new[]{("LineReference","Line Reference"),("ItemCode","Item Code"),("WarehouseCode","Warehouse Code"),("RackBinCode","Rack Bin Code"),("Quantity","Quantity"),("Rate","Rate")})ImportFields.Required(r,f.Item1,f.Item2,e);var qty=ImportFields.Decimal(r,"Quantity",e);ImportFields.Decimal(r,"Rate",e);if(qty==0)e.Add(ImportFields.Error("Quantity","Quantity","INVALID_VALUE","Opening quantity must be greater than zero.",ImportFields.V(r,"Quantity")));if(context is OpeningStockLookup l){var item=ImportFields.Code(ImportFields.V(r,"ItemCode"));var wh=ImportFields.Code(ImportFields.V(r,"WarehouseCode"));var bin=ImportFields.Code(ImportFields.V(r,"RackBinCode"));if(!l.Items.TryGetValue(item,out var tracking))e.Add(ImportFields.Error("ItemCode","Item Code","LOOKUP_NOT_FOUND","Approved active item was not found.",item));if(!l.Warehouses.TryGetValue(wh,out var warehouseId))e.Add(ImportFields.Error("WarehouseCode","Warehouse Code","LOOKUP_NOT_FOUND","Active warehouse was not found in this company.",wh));if(!l.Bins.TryGetValue(bin,out var location)||!location.Active||location.WarehouseId!=warehouseId)e.Add(ImportFields.Error("RackBinCode","Rack Bin Code","LOOKUP_NOT_FOUND","Active rack/bin was not found in the selected warehouse and company.",bin));if(tracking.Serial&&string.IsNullOrWhiteSpace(ImportFields.V(r,"SerialNumber")))e.Add(ImportFields.Error("SerialNumber","Serial Number","REQUIRED","Serial Number is required for this item.",null));if(tracking.Batch&&string.IsNullOrWhiteSpace(ImportFields.V(r,"LotNumber")))e.Add(ImportFields.Error("LotNumber","Lot Number","REQUIRED","Lot Number is required for this item.",null));if(tracking.Serial&&qty!=1)e.Add(ImportFields.Error("Quantity","Quantity","SERIAL_QUANTITY","Each serial row must have quantity 1.",ImportFields.V(r,"Quantity")));}return e;}public bool IsMateriallyEqual(MasterDataRawRow r,MasterDataExistingRecord x)=>false;
    public async Task<MasterDataApplyResult> CreateAsync(MasterDataRawRow r,CancellationToken ct)
    {
        var company=await db.Companies.Where(x=>x.Code==user.OrganizationId&&x.IsActive).Select(x=>x.Id).SingleAsync(ct);
        var itemCode=ImportFields.Code(ImportFields.V(r,"ItemCode"));var warehouseCode=ImportFields.Code(ImportFields.V(r,"WarehouseCode"));var binCode=ImportFields.Code(ImportFields.V(r,"RackBinCode"));
        var item=await db.Items.Where(x=>x.ItemCode==itemCode&&x.IsActive&&x.ApprovalStatus==MasterApprovalStatuses.Approved).Select(x=>x.Id).SingleAsync(ct);
        var warehouse=await db.Warehouses.Where(x=>x.CompanyId==company&&x.WarehouseCode==warehouseCode&&x.IsActive).Select(x=>x.Id).SingleAsync(ct);
        var bin=await db.RackBins.Where(x=>x.CompanyId==company&&x.WarehouseId==warehouse&&x.BinCode==binCode&&x.IsActive).Select(x=>x.Id).SingleAsync(ct);
          var connection=(NpgsqlConnection)db.Database.GetDbConnection();
          await using var command=new NpgsqlCommand(
              @"SELECT advance.stage_opening_stock_import_line(@company,@reference,@item,@warehouse,@bin,@lot,@serial,@quantity,@rate,@actor,@role,@assignment,@type,@login)",
              connection,(NpgsqlTransaction?)db.Database.CurrentTransaction?.GetDbTransaction());
          command.Parameters.AddWithValue("company",company);
          command.Parameters.AddWithValue("reference",ImportFields.V(r,"LineReference")!);
          command.Parameters.AddWithValue("item",item);
          command.Parameters.AddWithValue("warehouse",warehouse);
          command.Parameters.AddWithValue("bin",bin);
          command.Parameters.AddWithValue("lot",(object?)Null(ImportFields.V(r,"LotNumber"))??DBNull.Value);
          command.Parameters.AddWithValue("serial",(object?)Null(ImportFields.V(r,"SerialNumber"))??DBNull.Value);
          command.Parameters.AddWithValue("quantity",decimal.Parse(ImportFields.V(r,"Quantity")!,CultureInfo.InvariantCulture));
          command.Parameters.AddWithValue("rate",decimal.Parse(ImportFields.V(r,"Rate")!,CultureInfo.InvariantCulture));
          command.Parameters.AddWithValue("actor",user.EmployeeId!.Value);
          command.Parameters.AddWithValue("role",user.RoleCode);
          command.Parameters.AddWithValue("assignment",user.ResolvedRoleAssignmentId!.Value);
          command.Parameters.AddWithValue("type",user.ResolvedRoleAssignmentType!);
          command.Parameters.AddWithValue("login",user.LoginId);
          var id=(Guid)(await command.ExecuteScalarAsync(ct)
              ?? throw new MasterDataConflictException("Opening Stock staging returned no durable row."));
          return new(id,0);
    }
    public Task<MasterDataApplyResult> UpdateAsync(MasterDataExistingRecord x,MasterDataRawRow r,uint v,CancellationToken ct)=>throw new MasterDataValidationException("Opening-stock staging rows are immutable; upload a corrected workbook before authorization.");
    private static string? Null(string? value)=>string.IsNullOrWhiteSpace(value)?null:value.Trim();
}
