using System.Globalization;
using Microsoft.EntityFrameworkCore;
using SESS.NexaERP.Application.Common;
using SESS.NexaERP.Application.Inventory;
using SESS.NexaERP.Application.Masters;
using SESS.NexaERP.Domain.Inventory;
using SESS.NexaERP.Infrastructure.Persistence;

namespace SESS.NexaERP.Infrastructure.MasterData;

public sealed class WarehouseMasterDataDefinition : IMasterDataDefinition
{
    public string MasterKey=>"warehouses";public int TemplateVersion=>1;public string PageKey=>"masters.warehouses";public string BusinessCodeColumnKey=>"WarehouseCode";
    public IReadOnlyList<string> OperationalRolePriority { get; }=["STORES_MANAGER","STORES_EXECUTIVE","IT_MANAGER","TECHNICAL_DIRECTOR","MANAGING_DIRECTOR"];
    public MasterDataSensitivePermission? SensitiveResultPermission=>null;
    public IReadOnlyList<string> WorkbookGuideNotes { get; }=["Company scope comes from the signed-in session and is never read from the workbook.","Default receiving, QC and accepted locations are managed through the append-only warehouse condition-location UI after racks exist.","Lifecycle fields are read-only; deactivate through the governed API."];
    public IReadOnlyList<MasterDataColumnDefinition> Columns { get; }=
    [
        new("RecordId","Record ID",MasterDataColumnType.Guid,false,true,false,"UUID; blank for new rows","Existing record UUID",null,"Read-only identity used for update matching."),
        new("Version","Version",MasterDataColumnType.UnsignedInteger,false,true,false,"Whole number; blank for new rows","Current exported version",null,"Read-only optimistic concurrency version."),
        C("WarehouseCode","Warehouse Code",MasterDataColumnType.Text,true,true,"Uppercase text, maximum 80 characters","Unique within the selected company","Immutable warehouse business code.",80),
        C("Name","Name",MasterDataColumnType.Text,true,true,"Text, maximum 200 characters","Non-blank text","Warehouse display name.",200),
        C("WarehouseType","Warehouse Type",MasterDataColumnType.Text,true,true,"Uppercase text, maximum 80 characters","Business-defined warehouse type","Warehouse classification.",80),
        C("Location","Location",MasterDataColumnType.Text,false,true,"Text, maximum 1000 characters","Text or blank","Physical address/location.",1000),
        C("ResponsibleEmployeeCode","Responsible Employee Code",MasterDataColumnType.Text,false,true,"Uppercase employee code","Active employee assignment in selected company","Optional responsible employee lookup.",80,"employees"),
        C("DepartmentCode","Department Code",MasterDataColumnType.Text,false,true,"Uppercase department code","Active Department master code","Optional department lookup.",80,"departments"),
        R("Status","Status",MasterDataColumnType.Text),R("ApprovalStatus","Approval Status",MasterDataColumnType.Text),R("IsActive","Is Active",MasterDataColumnType.Boolean)
    ];
    private static MasterDataColumnDefinition C(string key,string header,MasterDataColumnType type,bool required,bool editable,string format,string allowed,string description,int? max=null,string? lookup=null)=>new(key,header,type,required,required,editable,format,allowed,lookup,description,max);
    private static MasterDataColumnDefinition R(string key,string header,MasterDataColumnType type)=>new(key,header,type,false,false,false,type==MasterDataColumnType.Boolean?"TRUE or FALSE; blank for new rows":"Text; blank for new rows","Current exported value",null,"Governed lifecycle value.");
}

public sealed class RackBinMasterDataDefinition : IMasterDataDefinition
{
    public string MasterKey=>"rack-bins";public int TemplateVersion=>1;public string PageKey=>"masters.rack-bins";public string BusinessCodeColumnKey=>"BinCode";
    public IReadOnlyList<string> OperationalRolePriority { get; }=["STORES_MANAGER","STORES_EXECUTIVE","IT_MANAGER","TECHNICAL_DIRECTOR","MANAGING_DIRECTOR"];
    public MasterDataSensitivePermission? SensitiveResultPermission=>null;
    public IReadOnlyList<string> WorkbookGuideNotes { get; }=["Company scope comes from the signed-in session.","Bin Code is unique within the selected company and immutable through upload.","A big-rack partition is one bin row. Use the same Rack Name for all partitions and identify each partition in Bin / Partition Number.","Condition locations are created and closed separately; lifecycle fields cannot be changed through upload."];
    public IReadOnlyList<MasterDataColumnDefinition> Columns { get; }=
    [
        new("RecordId","Record ID",MasterDataColumnType.Guid,false,true,false,"UUID; blank for new rows","Existing record UUID",null,"Read-only identity used for update matching."),new("Version","Version",MasterDataColumnType.UnsignedInteger,false,true,false,"Whole number; blank for new rows","Current exported version",null,"Read-only optimistic concurrency version."),
        C("WarehouseCode","Warehouse Code",MasterDataColumnType.Text,true,"Uppercase text, maximum 80 characters","Active Warehouse master code","Owning warehouse; immutable after creation.",80,"warehouses"),
        C("BinCode","Bin Code",MasterDataColumnType.Text,true,"Uppercase text, maximum 80 characters","Unique within selected company","Immutable rack/bin business code.",80),
        C("RackName","Rack Name",MasterDataColumnType.Text,true,"Text, maximum 120 characters","Non-blank text","Physical rack name shared by its partitions.",120),
        C("BinNameNumber","Bin / Partition Number",MasterDataColumnType.Text,true,"Text, maximum 120 characters","Non-blank text","Bin, shelf or partition identifier.",120),
        C("Zone","Zone",MasterDataColumnType.Text,false,"Text, maximum 120 characters","Text or blank","Optional warehouse zone.",120),
        C("LocationType","Location Type",MasterDataColumnType.Text,true,"Uppercase text, maximum 80 characters","Business-defined location type","Examples RACK, PARTITION, QC_SECTION.",80),
        C("MaterialCondition","Material Condition",MasterDataColumnType.Text,true,"Uppercase condition code",string.Join(", ",InventoryConditionCodes.All),"Condition this bin is eligible to map.",80),
        C("CapacityQuantity","Capacity Quantity",MasterDataColumnType.Decimal,false,"Invariant non-negative decimal","Zero or greater, or blank","Optional capacity; requires Capacity UOM."),
        C("CapacityUom","Capacity UOM",MasterDataColumnType.Text,false,"Uppercase UOM code, maximum 32 characters","Active UOM master code, or blank","Required with Capacity Quantity.",32,"uoms"),
        C("Barcode","Barcode",MasterDataColumnType.Text,false,"Uppercase text, maximum 128 characters","Text or blank","Optional physical location barcode.",128),
        C("Description","Description",MasterDataColumnType.Text,false,"Text, maximum 240 characters","Text or blank","Optional description.",240),
        R("Status","Status",MasterDataColumnType.Text,"Text; blank for new rows"),R("ApprovalStatus","Approval Status",MasterDataColumnType.Text,"Text; blank for new rows"),R("IsActive","Is Active",MasterDataColumnType.Boolean,"TRUE or FALSE; blank for new rows")
    ];
    private static MasterDataColumnDefinition C(string key,string header,MasterDataColumnType type,bool required,string format,string allowed,string description,int? max=null,string? lookup=null)=>new(key,header,type,required,required,true,format,allowed,lookup,description,max);
    private static MasterDataColumnDefinition R(string key,string header,MasterDataColumnType type,string format)=>new(key,header,type,false,false,false,format,"Current exported value",null,"Read-only identity, concurrency or lifecycle value.");
}

internal sealed record WarehouseLookup(IReadOnlySet<string> Employees,IReadOnlySet<string> Departments);
internal sealed record RackLookup(IReadOnlySet<string> Warehouses,IReadOnlySet<string> Uoms);

public sealed class WarehouseMasterDataAdapter(IWarehouseMasterDataService service,NexaErpDbContext db,ICurrentUser user) : IMasterDataAdapter
{
    private static readonly string[] Keys=["WarehouseCode","Name","WarehouseType","Location","ResponsibleEmployeeCode","DepartmentCode","Status","ApprovalStatus","IsActive"];
    public IMasterDataDefinition Definition { get; }=new WarehouseMasterDataDefinition();public string NormalizeBusinessCode(string value)=>Code(value);
    public Task<IReadOnlyList<MasterDataExportRow>> ExportAsync(MasterDataExportQuery q,CancellationToken ct)=>service.ExportAsync(q,ct);public Task<MasterDataExistingSet> LoadExistingAsync(IReadOnlyCollection<string> c,IReadOnlyCollection<Guid> i,CancellationToken ct)=>service.LoadExistingAsync(c,i,ct);
    public async Task<object?> LoadLookupContextAsync(IReadOnlyList<MasterDataRawRow> rows,CancellationToken ct){var company=await db.Companies.Where(x=>x.Code==user.OrganizationId&&x.IsActive).Select(x=>x.Id).SingleAsync(ct);var employeeCodes=rows.Select(x=>Code(V(x,"ResponsibleEmployeeCode"))).Where(x=>x.Length>0).Distinct().ToArray();var departmentCodes=rows.Select(x=>Code(V(x,"DepartmentCode"))).Where(x=>x.Length>0).Distinct().ToArray();var employees=await db.EmployeeCompanyAssignments.Where(x=>x.CompanyId==company&&x.IsActive&&employeeCodes.Contains(x.EmployeeCode)).Select(x=>x.EmployeeCode).ToListAsync(ct);var departments=await db.Departments.Where(x=>x.IsActive&&departmentCodes.Contains(x.Code)).Select(x=>x.Code).ToListAsync(ct);return new WarehouseLookup(employees.ToHashSet(StringComparer.Ordinal),departments.ToHashSet(StringComparer.Ordinal));}
    public IReadOnlyList<MasterDataRowError> Validate(MasterDataRawRow row,MasterDataExistingRecord? existing,object? context){var e=new List<MasterDataRowError>();Req(row,"WarehouseCode","Warehouse Code",80,e);Req(row,"Name","Name",200,e);Req(row,"WarehouseType","Warehouse Type",80,e);Max(row,"Location","Location",1000,e);Max(row,"ResponsibleEmployeeCode","Responsible Employee Code",80,e);Max(row,"DepartmentCode","Department Code",80,e);ReadOnly(row,existing,"Status","Status",e);ReadOnly(row,existing,"ApprovalStatus","Approval Status",e);ReadOnly(row,existing,"IsActive","Is Active",e);if(context is WarehouseLookup l){var employee=Code(V(row,"ResponsibleEmployeeCode"));if(employee.Length>0&&!l.Employees.Contains(employee))e.Add(Err("ResponsibleEmployeeCode","Responsible Employee Code","LOOKUP_NOT_FOUND","Employee is not actively assigned to the selected company.",employee));var department=Code(V(row,"DepartmentCode"));if(department.Length>0&&!l.Departments.Contains(department))e.Add(Err("DepartmentCode","Department Code","LOOKUP_NOT_FOUND","Active Department was not found.",department));}return e;}
    public bool IsMateriallyEqual(MasterDataRawRow row,MasterDataExistingRecord existing)=>Same(row,existing,Keys);
    public Task<MasterDataApplyResult> CreateAsync(MasterDataRawRow r,CancellationToken ct)=>service.CreateAsync(Request(r,null),ct);public Task<MasterDataApplyResult> UpdateAsync(MasterDataExistingRecord x,MasterDataRawRow r,uint v,CancellationToken ct)=>service.UpdateAsync(x,Request(r,v),ct);
    private static UpsertWarehouseRequest Request(MasterDataRawRow r,uint? v)=>new(V(r,"WarehouseCode")!,V(r,"Name")!,V(r,"WarehouseType")!,Opt(V(r,"Location")),Opt(V(r,"ResponsibleEmployeeCode")),Opt(V(r,"DepartmentCode")),null,null,null,null,null,null,v);
    internal static string? V(MasterDataRawRow r,string k)=>r.Values.TryGetValue(k,out var v)?v:null;internal static string Code(string? v)=>(v??"").Trim().ToUpperInvariant();internal static string? Opt(string? v)=>string.IsNullOrWhiteSpace(v)?null:v.Trim();
    internal static MasterDataRowError Err(string k,string h,string c,string m,string? a)=>new(k,h,c,m,a);internal static void Req(MasterDataRawRow r,string k,string h,int max,List<MasterDataRowError> e){if(string.IsNullOrWhiteSpace(V(r,k)))e.Add(Err(k,h,"REQUIRED",$"{h} is required.",V(r,k)));else Max(r,k,h,max,e);}internal static void Max(MasterDataRawRow r,string k,string h,int max,List<MasterDataRowError> e){if(V(r,k)?.Trim().Length>max)e.Add(Err(k,h,"MAX_LENGTH",$"{h} cannot exceed {max} characters.",V(r,k)));}
    internal static void ReadOnly(MasterDataRawRow r,MasterDataExistingRecord? x,string k,string h,List<MasterDataRowError> e){var v=V(r,k);if(string.IsNullOrWhiteSpace(v))return;if(x is null||!x.MaterialValues.TryGetValue(k,out var c)||!string.Equals(Norm(k,v),Norm(k,c),StringComparison.Ordinal))e.Add(Err(k,h,"READ_ONLY",$"{h} cannot be changed by upload.",v));}
    internal static bool Same(MasterDataRawRow r,MasterDataExistingRecord x,IEnumerable<string> keys){foreach(var k in keys){var v=V(r,k);if(string.IsNullOrWhiteSpace(v)&&k is "Status" or "ApprovalStatus" or "IsActive")continue;x.MaterialValues.TryGetValue(k,out var c);if(!string.Equals(Norm(k,v),Norm(k,c),StringComparison.Ordinal))return false;}return true;}internal static string? Norm(string k,string? v)=>k is "WarehouseCode" or "WarehouseType" or "ResponsibleEmployeeCode" or "DepartmentCode" or "IsActive"?Opt(v)?.ToUpperInvariant():Opt(v);
}

public sealed class RackBinMasterDataAdapter(IRackBinMasterDataService service,NexaErpDbContext db,ICurrentUser user) : IMasterDataAdapter
{
    private static readonly string[] Keys=["WarehouseCode","BinCode","RackName","BinNameNumber","Zone","LocationType","MaterialCondition","CapacityQuantity","CapacityUom","Barcode","Description","Status","ApprovalStatus","IsActive"];
    public IMasterDataDefinition Definition { get; }=new RackBinMasterDataDefinition();public string NormalizeBusinessCode(string v)=>WarehouseMasterDataAdapter.Code(v);public Task<IReadOnlyList<MasterDataExportRow>> ExportAsync(MasterDataExportQuery q,CancellationToken ct)=>service.ExportAsync(q,ct);public Task<MasterDataExistingSet> LoadExistingAsync(IReadOnlyCollection<string> c,IReadOnlyCollection<Guid> i,CancellationToken ct)=>service.LoadExistingAsync(c,i,ct);
    public async Task<object?> LoadLookupContextAsync(IReadOnlyList<MasterDataRawRow> rows,CancellationToken ct){var company=await db.Companies.Where(x=>x.Code==user.OrganizationId&&x.IsActive).Select(x=>x.Id).SingleAsync(ct);var warehouses=await db.Warehouses.Where(x=>x.CompanyId==company&&x.IsActive).Select(x=>x.WarehouseCode).ToListAsync(ct);var uoms=await db.Uoms.Where(x=>x.IsActive).Select(x=>x.Code).ToListAsync(ct);return new RackLookup(warehouses.ToHashSet(StringComparer.Ordinal),uoms.ToHashSet(StringComparer.Ordinal));}
    public IReadOnlyList<MasterDataRowError> Validate(MasterDataRawRow r,MasterDataExistingRecord? x,object? context){var e=new List<MasterDataRowError>();WarehouseMasterDataAdapter.Req(r,"WarehouseCode","Warehouse Code",80,e);WarehouseMasterDataAdapter.Req(r,"BinCode","Bin Code",80,e);WarehouseMasterDataAdapter.Req(r,"RackName","Rack Name",120,e);WarehouseMasterDataAdapter.Req(r,"BinNameNumber","Bin / Partition Number",120,e);WarehouseMasterDataAdapter.Req(r,"LocationType","Location Type",80,e);WarehouseMasterDataAdapter.Req(r,"MaterialCondition","Material Condition",80,e);foreach(var f in new[]{("Zone","Zone",120),("CapacityUom","Capacity UOM",32),("Barcode","Barcode",128),("Description","Description",240)})WarehouseMasterDataAdapter.Max(r,f.Item1,f.Item2,f.Item3,e);var condition=WarehouseMasterDataAdapter.Code(WarehouseMasterDataAdapter.V(r,"MaterialCondition"));if(condition.Length>0&&!InventoryConditionCodes.All.Contains(condition,StringComparer.Ordinal))e.Add(WarehouseMasterDataAdapter.Err("MaterialCondition","Material Condition","INVALID_VALUE","Use a documented inventory condition code.",condition));var qty=WarehouseMasterDataAdapter.V(r,"CapacityQuantity");var uom=WarehouseMasterDataAdapter.Code(WarehouseMasterDataAdapter.V(r,"CapacityUom"));if(!string.IsNullOrWhiteSpace(qty)&&(!decimal.TryParse(qty,NumberStyles.Number,CultureInfo.InvariantCulture,out var parsed)||parsed<0))e.Add(WarehouseMasterDataAdapter.Err("CapacityQuantity","Capacity Quantity","INVALID_VALUE","Use a non-negative invariant decimal.",qty));if(string.IsNullOrWhiteSpace(qty)!=(uom.Length==0))e.Add(WarehouseMasterDataAdapter.Err("CapacityUom","Capacity UOM","REQUIRED_PAIR","Capacity Quantity and Capacity UOM must be supplied together.",uom));if(context is RackLookup l){var wh=WarehouseMasterDataAdapter.Code(WarehouseMasterDataAdapter.V(r,"WarehouseCode"));if(wh.Length>0&&!l.Warehouses.Contains(wh))e.Add(WarehouseMasterDataAdapter.Err("WarehouseCode","Warehouse Code","LOOKUP_NOT_FOUND","Active Warehouse was not found in the selected company.",wh));if(uom.Length>0&&!l.Uoms.Contains(uom))e.Add(WarehouseMasterDataAdapter.Err("CapacityUom","Capacity UOM","LOOKUP_NOT_FOUND","Active UOM was not found.",uom));}foreach(var f in new[]{("Status","Status"),("ApprovalStatus","Approval Status"),("IsActive","Is Active")})WarehouseMasterDataAdapter.ReadOnly(r,x,f.Item1,f.Item2,e);return e;}
    public bool IsMateriallyEqual(MasterDataRawRow r,MasterDataExistingRecord x)=>WarehouseMasterDataAdapter.Same(r,x,Keys);public Task<MasterDataApplyResult> CreateAsync(MasterDataRawRow r,CancellationToken ct)=>service.CreateAsync(Request(r,null),ct);public Task<MasterDataApplyResult> UpdateAsync(MasterDataExistingRecord x,MasterDataRawRow r,uint v,CancellationToken ct)=>service.UpdateAsync(x,Request(r,v),ct);
    private static UpsertRackBinRequest Request(MasterDataRawRow r,uint? v){decimal? capacity=decimal.TryParse(WarehouseMasterDataAdapter.V(r,"CapacityQuantity"),NumberStyles.Number,CultureInfo.InvariantCulture,out var q)?q:null;return new(WarehouseMasterDataAdapter.V(r,"WarehouseCode")!,WarehouseMasterDataAdapter.V(r,"BinCode")!,WarehouseMasterDataAdapter.V(r,"RackName")!,WarehouseMasterDataAdapter.V(r,"BinNameNumber")!,WarehouseMasterDataAdapter.Opt(WarehouseMasterDataAdapter.V(r,"Zone")),WarehouseMasterDataAdapter.V(r,"LocationType")!,WarehouseMasterDataAdapter.V(r,"MaterialCondition")!,capacity,WarehouseMasterDataAdapter.Opt(WarehouseMasterDataAdapter.V(r,"CapacityUom")),WarehouseMasterDataAdapter.Opt(WarehouseMasterDataAdapter.V(r,"Barcode")),WarehouseMasterDataAdapter.Opt(WarehouseMasterDataAdapter.V(r,"Description")),v);}
}
