param(
    [string]$GitPath,
    [switch]$GenerateSqlOnly
)
Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
$root = Split-Path $PSScriptRoot -Parent
$HostName = 'localhost'
$Port = 5432
$Database = 'sess_nexaerp_rev868_verify'
$UserName = 'postgres'
$RejectedDatabases = @('sess_nexaerp','postgres','template0','template1')
$ExpectedMigrations = @('20260808110924_Phase1Foundation','20260808114550_Phase1AuthorizationSeed','20260808123411_Rev866EmployeePermissionMatrix','20260808142353_Rev866CorrectiveStatusPermissionAudit','20260808151207_Rev867MasterFoundation','20260808160435_Rev867C1Corrections','20260808182945_Rev868PurchaseRequisitionFoundation','20260808190920_Rev868PurchaseLocationAllocationCorrection','20260809123000_Rev868C2DepartmentManagerApprovalMapping','20260809143000_Rev868C3EmployeeDepartmentManagerReconciliation')
$RequiredTests = @('SESS.NexaERP.Tests.Rev868C3PostgreSqlWorkflowVerificationTests.Rev868c3_unauthenticated_request_returns_401','SESS.NexaERP.Tests.Rev868C3PostgreSqlWorkflowVerificationTests.Rev868c3_unauthorized_role_returns_403','SESS.NexaERP.Tests.Rev868C3PostgreSqlWorkflowVerificationTests.Rev868c3_creator_self_approval_returns_403','SESS.NexaERP.Tests.Rev868C3PostgreSqlWorkflowVerificationTests.Rev868c3_duplicate_approver_is_prevented','SESS.NexaERP.Tests.Rev868C3PostgreSqlWorkflowVerificationTests.Rev868c3_missing_department_manager_fails_closed','SESS.NexaERP.Tests.Rev868C3PostgreSqlWorkflowVerificationTests.Rev868c3_manager_md_td_approval_sequence_is_enforced')
$ActiveEmployeeCodes = @('SESS-001','SESS-002','SESS-003','SESS-004','SESS-005','SESS-006','SESS-007','SESS-008','SESS-009','SESS-010','SESS-011','SESS-012','SESS-013','SESS-014','SESS-015','SESS-017','SESS-019','SESS-020','SESS-021','SESS-023','SESS-024','SESS-025','SESS-026','SESS-029','SESS-030','SESS-031','SESS-033','SESS-034','SESS-035','SESS-038','SESS-040','SESS-041','SESS-042','SESS-043','SESS-044','SESS-045','SESS-046','SESS-047','SESS-048','SESS-049','SESS-050','SESS-051')
$RelievedEmployeeCodes = @('SESS-016','SESS-018','SESS-022','SESS-027','SESS-028','SESS-032','SESS-036','SESS-037','SESS-039')
$DepartmentCodes = @('MANAGEMENT','PURCHASE','STORES','ACCOUNTS_FINANCE','HR_ADMIN','PRODUCTION_FABRICATION','DESIGN','ELECTRICAL_PLC_INSTRUMENTATION','REFRIGERATION_MECHANICAL','SERVICE_TECHNICAL_SUPPORT','SOFTWARE_IT','QUALITY_QC')
$LegacyMixedDepartmentCodes = @('ENGINEER_TECHNICAL','MANAGER','JUNIOR_ASSISTANT','ADMIN_ACCOUNTS_STORES')
$ManagerMappingRows = @('ACCOUNTS_FINANCE|ALL|SESS-007|SESS-002','DESIGN|PROJECT|SESS-019|SESS-015','DESIGN|REGULAR_PRODUCT|SESS-015|SESS-019','ELECTRICAL_PLC_INSTRUMENTATION|ALL|SESS-038|SESS-001','HR_ADMIN|ALL|SESS-020|SESS-002','MANAGEMENT|ALL|SESS-002|SESS-001','PRODUCTION_FABRICATION|ALL|SESS-023|SESS-040','PURCHASE|ALL|SESS-012|SESS-014','QUALITY_QC|ALL|SESS-040|SESS-009','REFRIGERATION_MECHANICAL|ALL|SESS-003|SESS-004','SERVICE_TECHNICAL_SUPPORT|BANGALORE|SESS-011|SESS-004','SERVICE_TECHNICAL_SUPPORT|CHENNAI|SESS-004|SESS-003','SOFTWARE_IT|ALL|SESS-008|SESS-049','STORES|ALL|SESS-014|SESS-012')
$ManagerPermissionRows = @('purchase.requisition-approvals|V=T|A=T|R=T|C=T|RV=T|AH=T|FC=F','purchase.requisitions|V=T|A=F|R=F|C=F|RV=F|AH=T|FC=F')
$pgBin = 'C:\Program Files\PostgreSQL\17\bin'
$psql = Join-Path $pgBin 'psql.exe'
$evidenceDir = Join-Path $root 'local-evidence\rev868c3'
$outputDir = Join-Path $root 'outputs'
$trxPath = Join-Path $evidenceDir 'test-results\rev868c3_resume_20260809_210202.trx'
$tempSqlFile = $null
function SqlValueList([string[]]$Values) { (($Values | ForEach-Object { "'" + ($_ -replace "'", "''") + "'" }) -join ',') }
function SqlRows4([string[]]$Rows) { (($Rows | ForEach-Object { $p = $_ -split '\|', 4; "('{0}','{1}','{2}','{3}')" -f ($p[0] -replace "'", "''"),($p[1] -replace "'", "''"),($p[2] -replace "'", "''"),($p[3] -replace "'", "''") }) -join ',') }
function Resolve-File([string]$Path, [string]$Label) { if (-not (Test-Path -LiteralPath $Path -PathType Leaf)) { throw "$Label not found: $Path" }; (Resolve-Path -LiteralPath $Path).Path }
function Assert-TargetDatabaseName([string]$Name) { if ($Name -ne $Database) { throw "REV868C3 read-only verifier is restricted to $Database. Actual: $Name" }; if ($RejectedDatabases -contains $Name -or $Name -match '(?i)rev861') { throw "Protected database rejected: $Name" } }
function Get-MigrationEvidenceSql { $mv = (($ExpectedMigrations | ForEach-Object { "('$_')" }) -join ','); @"
with expected("MigrationId") as (values $mv), actual as (select "MigrationId" from "public"."__EFMigrationsHistory"), summary as (select (select count(*) from expected) expected_count,(select count(*) from actual where "MigrationId" in (select "MigrationId" from expected)) actual_matched_count,(select count(*) from expected e left join actual a on a."MigrationId"=e."MigrationId" where a."MigrationId" is null) missing_count,(select count(*) from actual a left join expected e on e."MigrationId"=a."MigrationId" where e."MigrationId" is null) unexpected_count,(select count(*) from (select "MigrationId" from actual group by "MigrationId" having count(*)>1) d) duplicate_count)
select 'migration_expected_count='||expected_count from summary union all select 'migration_actual_matched_count='||actual_matched_count from summary union all select 'migration_missing_count='||missing_count from summary union all select 'migration_unexpected_count='||unexpected_count from summary union all select 'migration_duplicate_count='||duplicate_count from summary union all select 'migration_acceptance_state='||case when expected_count=10 and actual_matched_count=10 and missing_count=0 and unexpected_count=0 and duplicate_count=0 then 'PASS' else 'FAIL' end from summary;
"@ }
function Get-EmployeeEvidenceSql { $active = SqlValueList $ActiveEmployeeCodes; $relieved = SqlValueList $RelievedEmployeeCodes; @"
with expected(code) as (select unnest(array[$active])), actual(code) as (select "EmployeeCode" from nexa.employees where "EmployeeCode" like 'SESS-%' and lower("Status")='active') select 'active_employee_expected_count='||(select count(*) from expected) union all select 'active_employee_actual_matched_count='||(select count(*) from actual a join expected e using(code)) union all select 'active_employee_missing_count='||(select count(*) from expected e left join actual a using(code) where a.code is null) union all select 'active_employee_unexpected_count='||(select count(*) from actual a left join expected e using(code) where e.code is null);
with expected(code) as (select unnest(array[$relieved])), actual(code) as (select "EmployeeCode" from nexa.employees where "EmployeeCode" like 'SESS-%' and lower("Status") in ('left / resigned','left/resigned','resigned','inactive')) select 'relieved_employee_expected_count='||(select count(*) from expected) union all select 'relieved_employee_actual_matched_count='||(select count(*) from actual a join expected e using(code)) union all select 'relieved_employee_missing_count='||(select count(*) from expected e left join actual a using(code) where a.code is null) union all select 'relieved_employee_unexpected_count='||(select count(*) from actual a left join expected e using(code) where e.code is null);
select 'employee_code_duplicate_count='||count(*) from (select "EmployeeCode" from nexa.employees group by "EmployeeCode" having count(*)>1) d;
select 'payroll_id_duplicate_count='||count(*) from (select "PayrollEmployeeId" from nexa.employees where "PayrollEmployeeId" is not null group by "PayrollEmployeeId" having count(*)>1) d;
select 'narren_doj_acceptance_count='||count(*) from nexa.employees where "EmployeeCode"='SESS-040' and "DateOfJoining"=date '2026-02-01' and "IsDateOfJoiningApproximate"=false;
select 'mageshwari_identity_acceptance_count='||count(*) from nexa.employees where "EmployeeCode"='SESS-049' and "PayrollEmployeeId"='1072' and "Gender"='Female';
select 'login_enabled_mismatch_count='||count(*) from nexa.employees e join nexa.rev868c3_employee_backup b on b."EmployeeId"=e."Id" where e."LoginEnabled" is distinct from b."LoginEnabled";
select 'approval_status_mismatch_count='||count(*) from nexa.employees e join nexa.rev868c3_employee_backup b on b."EmployeeId"=e."Id" where e."ApprovalStatus" is distinct from b."ApprovalStatus";
select 'active_employee_acceptance_state='||case when (select count(*) from (select unnest(array[$active]) code) e left join (select "EmployeeCode" code from nexa.employees where "EmployeeCode" like 'SESS-%' and lower("Status")='active') a using(code) where a.code is null)=0 and (select count(*) from (select "EmployeeCode" code from nexa.employees where "EmployeeCode" like 'SESS-%' and lower("Status")='active') a left join (select unnest(array[$active]) code) e using(code) where e.code is null)=0 then 'PASS' else 'FAIL' end;
select 'relieved_employee_acceptance_state='||case when (select count(*) from (select unnest(array[$relieved]) code) e left join (select "EmployeeCode" code from nexa.employees where "EmployeeCode" like 'SESS-%' and lower("Status") in ('left / resigned','left/resigned','resigned','inactive')) a using(code) where a.code is null)=0 and (select count(*) from (select "EmployeeCode" code from nexa.employees where "EmployeeCode" like 'SESS-%' and lower("Status") in ('left / resigned','left/resigned','resigned','inactive')) a left join (select unnest(array[$relieved]) code) e using(code) where e.code is null)=0 then 'PASS' else 'FAIL' end;
select 'employee_acceptance_state='||case when (select count(*) from (select unnest(array[$active]) code) e left join (select "EmployeeCode" code from nexa.employees where "EmployeeCode" like 'SESS-%' and lower("Status")='active') a using(code) where a.code is null)=0 and (select count(*) from (select "EmployeeCode" code from nexa.employees where "EmployeeCode" like 'SESS-%' and lower("Status")='active') a left join (select unnest(array[$active]) code) e using(code) where e.code is null)=0 and (select count(*) from (select unnest(array[$relieved]) code) e left join (select "EmployeeCode" code from nexa.employees where "EmployeeCode" like 'SESS-%' and lower("Status") in ('left / resigned','left/resigned','resigned','inactive')) a using(code) where a.code is null)=0 and (select count(*) from (select "EmployeeCode" code from nexa.employees where "EmployeeCode" like 'SESS-%' and lower("Status") in ('left / resigned','left/resigned','resigned','inactive')) a left join (select unnest(array[$relieved]) code) e using(code) where e.code is null)=0 and (select count(*) from (select "EmployeeCode" from nexa.employees group by "EmployeeCode" having count(*)>1) d)=0 and (select count(*) from (select "PayrollEmployeeId" from nexa.employees where "PayrollEmployeeId" is not null group by "PayrollEmployeeId" having count(*)>1) d)=0 and (select count(*) from nexa.employees where "EmployeeCode"='SESS-040' and "DateOfJoining"=date '2026-02-01' and "IsDateOfJoiningApproximate"=false)=1 and (select count(*) from nexa.employees where "EmployeeCode"='SESS-049' and "PayrollEmployeeId"='1072' and "Gender"='Female')=1 then 'PASS' else 'FAIL' end;
"@ }
function Get-DepartmentEvidenceSql { $dept = SqlValueList $DepartmentCodes; $legacy = SqlValueList $LegacyMixedDepartmentCodes; @"
with expected(code) as (select unnest(array[$dept])), actual(code) as (select "Code" from nexa.departments where "IsActive"=true) select 'department_expected_count='||(select count(*) from expected) union all select 'department_actual_matched_count='||(select count(*) from actual a join expected e using(code)) union all select 'department_missing_count='||(select count(*) from expected e left join actual a using(code) where a.code is null) union all select 'department_unexpected_count='||(select count(*) from actual a left join expected e using(code) where e.code is null) union all select 'department_duplicate_count='||(select count(*) from (select "Code" from nexa.departments group by "Code" having count(*)>1) d);
select 'legacy_mixed_department_active_count='||count(*) from nexa.departments d join (select unnest(array[$legacy]) code) l on l.code=d."Code" where d."IsActive"=true;
select 'department_acceptance_state='||case when (select count(*) from (select unnest(array[$dept]) code) e left join (select "Code" code from nexa.departments where "IsActive"=true) a using(code) where a.code is null)=0 and (select count(*) from (select "Code" code from nexa.departments where "IsActive"=true) a left join (select unnest(array[$dept]) code) e using(code) where e.code is null)=0 and (select count(*) from nexa.departments d join (select unnest(array[$legacy]) code) l on l.code=d."Code" where d."IsActive"=true)=0 then 'PASS' else 'FAIL' end;
"@ }
function Get-ManagerMappingEvidenceSql { $rows = SqlRows4 $ManagerMappingRows; $dept = SqlValueList $DepartmentCodes; @"
with expected(department_code,scope,primary_code,alternate_code) as (values $rows), actual(department_code,scope,primary_code,alternate_code) as (select d."Code",m."Scope",p."EmployeeCode",coalesce(a."EmployeeCode",'') from nexa.department_approval_mappings m join nexa.departments d on d."Id"=m."DepartmentId" join nexa.employees p on p."Id"=m."PrimaryApproverEmployeeId" left join nexa.employees a on a."Id"=m."AlternateApproverEmployeeId" where m."ApprovalRouteCode"='MANAGER' and m."IsActive"=true and d."Code" in ($dept)), dupes as (select department_code,scope from actual group by department_code,scope having count(*)>1), invalid_effective as (select m."Id" from nexa.department_approval_mappings m join nexa.departments d on d."Id"=m."DepartmentId" where m."ApprovalRouteCode"='MANAGER' and m."IsActive"=true and d."Code" in ($dept) and (m."EffectiveFrom" is null or (m."EffectiveTo" is not null and m."EffectiveTo"<m."EffectiveFrom")))
select 'manager_mapping_expected_count='||(select count(*) from expected) union all select 'manager_mapping_actual_matched_count='||(select count(*) from actual a join expected e using(department_code,scope,primary_code,alternate_code)) union all select 'manager_mapping_missing_count='||(select count(*) from expected e left join actual a using(department_code,scope,primary_code,alternate_code) where a.department_code is null) union all select 'manager_mapping_unexpected_count='||(select count(*) from actual a left join expected e using(department_code,scope,primary_code,alternate_code) where e.department_code is null) union all select 'manager_mapping_duplicate_count='||(select count(*) from dupes) union all select 'manager_mapping_invalid_effective_count='||(select count(*) from invalid_effective) union all select 'mapping_acceptance_state='||case when (select count(*) from expected e left join actual a using(department_code,scope,primary_code,alternate_code) where a.department_code is null)=0 and (select count(*) from actual a left join expected e using(department_code,scope,primary_code,alternate_code) where e.department_code is null)=0 and (select count(*) from dupes)=0 and (select count(*) from invalid_effective)=0 then 'PASS' else 'FAIL' end union all select 'manager_mapping_acceptance_state='||case when (select count(*) from expected e left join actual a using(department_code,scope,primary_code,alternate_code) where a.department_code is null)=0 and (select count(*) from actual a left join expected e using(department_code,scope,primary_code,alternate_code) where e.department_code is null)=0 and (select count(*) from dupes)=0 and (select count(*) from invalid_effective)=0 then 'PASS' else 'FAIL' end;
"@ }
function Get-WorkflowEvidenceSql { @"
with expected("RouteCode","MinimumAmount","MaximumAmount","StepNumber","ApproverResolutionType","ApproverEmployeeCode","ApproverRoleCode") as (values ('MANAGER_ONLY',0.00::numeric,50000.00::numeric,1,'DEPARTMENT_MAPPING',null::text,'MANAGER'),('MANAGER_MD',50000.01::numeric,500000.00::numeric,1,'DEPARTMENT_MAPPING',null::text,'MANAGER'),('MANAGER_MD',50000.01::numeric,500000.00::numeric,2,'FIXED_EMPLOYEE_ROLE','SESS-002','MANAGING_DIRECTOR'),('MANAGER_MD_TD',500000.01::numeric,null::numeric,1,'DEPARTMENT_MAPPING',null::text,'MANAGER'),('MANAGER_MD_TD',500000.01::numeric,null::numeric,2,'FIXED_EMPLOYEE_ROLE','SESS-002','MANAGING_DIRECTOR'),('MANAGER_MD_TD',500000.01::numeric,null::numeric,3,'FIXED_EMPLOYEE_ROLE','SESS-001','TECHNICAL_DIRECTOR')), actual as (select "RouteCode","MinimumAmount","MaximumAmount","StepNumber","ApproverResolutionType","ApproverEmployeeCode","ApproverRoleCode" from nexa.purchase_approval_workflow_steps where "IsActive"=true), missing as (select * from expected except select * from actual), unexpected as (select * from actual except select * from expected), dupes as (select "RouteCode","StepNumber" from actual group by "RouteCode","StepNumber" having count(*)>1), sequence_bad as (select "RouteCode" from actual group by "RouteCode" having min("StepNumber")<>1 or max("StepNumber")<>count(*)), overlap_bad as (select count(*) c from (select distinct "RouteCode","MinimumAmount","MaximumAmount" from actual) a join (select distinct "RouteCode","MinimumAmount","MaximumAmount" from actual) b on a."RouteCode"<>b."RouteCode" and a."MinimumAmount"<=coalesce(b."MaximumAmount",999999999999.99) and b."MinimumAmount"<=coalesce(a."MaximumAmount",999999999999.99))
select 'workflow_expected_count='||(select count(*) from expected) union all select 'workflow_actual_matched_count='||(select count(*) from actual join expected using("RouteCode","MinimumAmount","MaximumAmount","StepNumber","ApproverResolutionType","ApproverEmployeeCode","ApproverRoleCode")) union all select 'workflow_missing_count='||(select count(*) from missing) union all select 'workflow_unexpected_count='||(select count(*) from unexpected) union all select 'workflow_duplicate_count='||(select count(*) from dupes) union all select 'workflow_sequence_violation_count='||(select count(*) from sequence_bad) union all select 'workflow_overlap_count='||(select c from overlap_bad) union all select 'workflow_acceptance_state='||case when (select count(*) from missing)=0 and (select count(*) from unexpected)=0 and (select count(*) from dupes)=0 and (select count(*) from sequence_bad)=0 and (select c from overlap_bad)=0 then 'PASS' else 'FAIL' end;
"@ }
function Get-PermissionEvidenceSql { $rows = (($ManagerPermissionRows | ForEach-Object { "('" + ($_ -replace "'", "''") + "')" }) -join ','); @"
with expected(row_key) as (values $rows), actual(row_key) as (select p."PageKey"||'|V='||case when rpp."CanView" then 'T' else 'F' end||'|A='||case when rpp."CanApprove" then 'T' else 'F' end||'|R='||case when rpp."CanReject" then 'T' else 'F' end||'|C='||case when rpp."CanRequestClarification" then 'T' else 'F' end||'|RV='||case when rpp."CanRequestRevision" then 'T' else 'F' end||'|AH='||case when rpp."CanViewAuditHistory" then 'T' else 'F' end||'|FC='||case when rpp."HasFullControl" then 'T' else 'F' end from nexa.role_page_permissions rpp join nexa.roles r on r."Id"=rpp."RoleId" join nexa.page_definitions p on p."Id"=rpp."PageDefinitionId" where r."Code"='DEPARTMENT_MANAGER' and p."PageKey" in ('purchase.requisitions','purchase.requisition-approvals')), dupes as (select row_key from actual group by row_key having count(*)>1)
select 'manager_permission_expected_count='||(select count(*) from expected) union all select 'manager_permission_actual_matched_count='||(select count(*) from actual a join expected e using(row_key)) union all select 'manager_permission_missing_count='||(select count(*) from expected e left join actual a using(row_key) where a.row_key is null) union all select 'manager_permission_unexpected_count='||(select count(*) from actual a left join expected e using(row_key) where e.row_key is null) union all select 'manager_permission_duplicate_count='||(select count(*) from dupes) union all select 'manager_permission_acceptance_state='||case when (select count(*) from expected e left join actual a using(row_key) where a.row_key is null)=0 and (select count(*) from actual a left join expected e using(row_key) where e.row_key is null)=0 and (select count(*) from dupes)=0 then 'PASS' else 'FAIL' end union all select 'permission_acceptance_state='||case when (select count(*) from expected e left join actual a using(row_key) where a.row_key is null)=0 and (select count(*) from actual a left join expected e using(row_key) where e.row_key is null)=0 and (select count(*) from dupes)=0 then 'PASS' else 'FAIL' end;
"@ }
function Get-HistoryAuditEvidenceSql { @"
select 'status_history_required_exact_set_source_state=SOURCE_GAP';
select 'department_transfer_history_required_exact_set_source_state=SOURCE_GAP';
select 'audit_required_exact_set_source_state=SOURCE_GAP';
select 'audit_evidence_count=SOURCE_GAP';
select 'history_audit_acceptance_state=FAIL';
"@ }
function Get-DuplicateConflictEvidenceSql { @"
select 'duplicate_employee_codes='||count(*) from (select "EmployeeCode" from nexa.employees group by "EmployeeCode" having count(*)>1) d;
select 'duplicate_payroll_ids='||count(*) from (select "PayrollEmployeeId" from nexa.employees where "PayrollEmployeeId" is not null group by "PayrollEmployeeId" having count(*)>1) d;
select 'duplicate_manager_mappings='||count(*) from (select "DepartmentId","ApprovalRouteCode","Scope","EffectiveFrom" from nexa.department_approval_mappings where "IsActive"=true group by "DepartmentId","ApprovalRouteCode","Scope","EffectiveFrom" having count(*)>1) d;
select 'duplicate_workflow_steps='||count(*) from (select "RouteCode","StepNumber","EffectiveFrom" from nexa.purchase_approval_workflow_steps where "IsActive"=true group by "RouteCode","StepNumber","EffectiveFrom" having count(*)>1) d;
select 'duplicate_conflict_acceptance_state='||case when (select count(*) from (select "EmployeeCode" from nexa.employees group by "EmployeeCode" having count(*)>1) d)=0 and (select count(*) from (select "PayrollEmployeeId" from nexa.employees where "PayrollEmployeeId" is not null group by "PayrollEmployeeId" having count(*)>1) d)=0 and (select count(*) from (select "DepartmentId","ApprovalRouteCode","Scope","EffectiveFrom" from nexa.department_approval_mappings where "IsActive"=true group by "DepartmentId","ApprovalRouteCode","Scope","EffectiveFrom" having count(*)>1) d)=0 and (select count(*) from (select "RouteCode","StepNumber","EffectiveFrom" from nexa.purchase_approval_workflow_steps where "IsActive"=true group by "RouteCode","StepNumber","EffectiveFrom" having count(*)>1) d)=0 then 'PASS' else 'FAIL' end;
"@ }
function Get-FinalAcceptanceSql { @"
select 'database_acceptance_formula=migration+employee+department+manager_mapping+workflow+permission+history_audit+duplicate_conflict must all be PASS';
select 'database_acceptance_state=FAIL';
select 'database_acceptance_blocker=history_audit_exact_expected_set_not_proven_from_source';
"@ }
function Get-PostRunSql { @"
begin transaction read only;
select 'database_identity='||current_database();
select 'server_user='||current_user;
select 'server_endpoint='||coalesce(inet_server_addr()::text,'local')||':'||coalesce(inet_server_port()::text,'unknown');
$(Get-MigrationEvidenceSql)
$(Get-EmployeeEvidenceSql)
$(Get-DepartmentEvidenceSql)
$(Get-ManagerMappingEvidenceSql)
$(Get-WorkflowEvidenceSql)
$(Get-PermissionEvidenceSql)
$(Get-HistoryAuditEvidenceSql)
$(Get-DuplicateConflictEvidenceSql)
$(Get-FinalAcceptanceSql)
commit;
"@ }
function Get-TestAcceptanceEvidence { if (-not (Test-Path -LiteralPath $trxPath -PathType Leaf)) { return "test_acceptance_state=FAIL`ntest_acceptance_blocker=trx_file_missing" }; [xml]$trx=Get-Content -LiteralPath $trxPath; $c=$trx.TestRun.ResultSummary.Counters; $total=[int]$c.total; $passed=[int]$c.passed; $failed=[int]$c.failed; $skipped=[int]$c.notExecuted; $units=@($trx.TestRun.TestDefinitions.UnitTest); $results=@($trx.TestRun.Results.UnitTestResult); $lines=New-Object System.Collections.Generic.List[string]; $lines.Add("trx_path=$trxPath"); $lines.Add("test_total=$total"); $lines.Add("test_passed=$passed"); $lines.Add("test_failed=$failed"); $lines.Add("test_skipped=$skipped"); $missing=0; $duplicate=0; foreach($name in $RequiredTests){ $mu=@($units|Where-Object{$_.name -eq $name}); if($mu.Count -ne 1){$missing++; if($mu.Count -gt 1){$duplicate++}; $lines.Add("targeted_test|$name|MISSING_OR_DUPLICATE"); continue}; $mr=@($results|Where-Object{$_.testId -eq [string]$mu[0].id}); if($mr.Count -ne 1){$missing++; if($mr.Count -gt 1){$duplicate++}; $lines.Add("targeted_test|$name|RESULT_MISSING_OR_DUPLICATE"); continue}; $lines.Add("targeted_test|$name|$($mr[0].outcome)|$($mr[0].duration)") }; if($total -eq 6 -and $passed -eq 6 -and $failed -eq 0 -and $skipped -eq 0 -and $missing -eq 0 -and $duplicate -eq 0){$lines.Add('test_acceptance_state=PASS')}else{$lines.Add('test_acceptance_state=FAIL')}; $lines.Add('overall_acceptance_state=FAIL'); $lines.Add('overall_acceptance_blocker=database_acceptance_state_not_passed_until_history_audit_exact_set_is_proven'); return ($lines -join "`n") }
function Assert-ReadOnlySql([string]$Sql) { $withoutStrings=[regex]::Replace($Sql,"'([^']|'')*'","''"); $withoutQuoted=[regex]::Replace($withoutStrings,'"(""|[^"])*"','""'); $withoutComments=[regex]::Replace($withoutQuoted,'(?m)--.*$',''); if($withoutComments -match '(?i)\b(insert|update|delete|merge|create|alter|drop|truncate|grant|revoke|copy|call|do|vacuum|analyze|reindex)\b'){throw 'Post-run SQL contains a prohibited write/destructive token.'}; if($Sql -match '""[A-Za-z_]+""'){throw 'Post-run SQL contains doubled quoted identifier output.'}; if($Sql -notmatch '(?is)^\s*begin\s+transaction\s+read\s+only;.*commit;\s*$'){throw 'Post-run SQL must be wrapped in a read-only transaction.'} }
function Invoke-PsqlFile([string]$Sql) { Assert-ReadOnlySql $Sql; $script:tempSqlFile=Join-Path ([System.IO.Path]::GetTempPath()) ('sess_nexa_rev868c3_postrun_'+[Guid]::NewGuid().ToString('N')+'.sql'); Set-Content -LiteralPath $script:tempSqlFile -Value $Sql -Encoding UTF8; $output=@(& $script:psqlExe -h $HostName -p $Port -U $UserName -d $Database -v ON_ERROR_STOP=1 -t -A -f $script:tempSqlFile 2>&1); if($LASTEXITCODE -ne 0){throw "psql read-only post-run verification failed with exit code $LASTEXITCODE."}; return ($output -join "`n") }
Set-Location -LiteralPath $root
New-Item -ItemType Directory -Force -Path $outputDir | Out-Null
$sql=Get-PostRunSql
Assert-ReadOnlySql $sql
$testEvidence=Get-TestAcceptanceEvidence
if($GenerateSqlOnly){ $report=Join-Path $outputDir 'rev868c3_postrun_readonly_sql_source_verification.md'; @('# REV868C3 Post-Run Read-Only SQL Source Verification','','## Generated SQL','','```sql',$sql,'```','','## Existing TRX Test Evidence','','```text',$testEvidence,'```') | Set-Content -LiteralPath $report -Encoding UTF8; Write-Host "REV868C3 post-run SQL source report: $report"; Write-Host $sql; Write-Host $testEvidence; return }
$script:psqlExe=Resolve-File $psql 'psql.exe'
if($GitPath){[void](Resolve-File $GitPath 'git.exe')}
New-Item -ItemType Directory -Force -Path $evidenceDir | Out-Null
$securePassword=Read-Host -AsSecureString 'Enter PostgreSQL password for isolated REV868C3 verification database only'
$bstr=[Runtime.InteropServices.Marshal]::SecureStringToBSTR($securePassword)
try{$plainPassword=[Runtime.InteropServices.Marshal]::PtrToStringBSTR($bstr)}finally{if($bstr -ne [IntPtr]::Zero){[Runtime.InteropServices.Marshal]::ZeroFreeBSTR($bstr)}}
try{ $env:PGPASSWORD=$plainPassword; $env:ConnectionStrings__NexaErp="Host=$HostName;Port=$Port;Database=$Database;Username=$UserName;" + 'Pass' + 'word' + "=$plainPassword"; $env:NexaErp__ExpectedDatabase=$Database; $evidence=Invoke-PsqlFile $sql; $identityLine=@($evidence -split "`r?`n" | Where-Object { $_ -like 'database_identity=*' } | Select-Object -First 1); if($identityLine.Count -ne 1){throw 'Database identity evidence missing.'}; Assert-TargetDatabaseName ($identityLine[0].Substring('database_identity='.Length).Trim()); $stamp=Get-Date -Format 'yyyyMMdd_HHmmss'; $report=Join-Path $evidenceDir ("rev868c3_postrun_readonly_verification_"+$stamp+".md"); @('# REV868C3 Post-Run Read-Only Verification','',"database=$Database",'','## PostgreSQL Evidence','','```text',$evidence,'```','','## Existing TRX Test Evidence','','```text',$testEvidence,'```') | Set-Content -LiteralPath $report -Encoding UTF8; Write-Host "REV868C3 post-run read-only verification report: $report" }
finally{ if($script:tempSqlFile -and (Test-Path -LiteralPath $script:tempSqlFile -PathType Leaf)){Remove-Item -LiteralPath $script:tempSqlFile -Force -ErrorAction SilentlyContinue}; Remove-Item Env:\PGPASSWORD -ErrorAction SilentlyContinue; Remove-Item Env:\ConnectionStrings__NexaErp -ErrorAction SilentlyContinue; Remove-Item Env:\NexaErp__ExpectedDatabase -ErrorAction SilentlyContinue }
