namespace SESS.NexaERP.Infrastructure.Persistence.Migrations;

/// <summary>Frozen Correction 19 target-local command, purge and export ledgers.</summary>
internal static class Rev869BCommandContextSql
{
    internal const string Install = """
        DO $roles$ DECLARE r text; BEGIN
          FOREACH r IN ARRAY ARRAY['nexa_rev869b_security_owner','nexa_rev869b_app_runtime','nexa_rev869b_command_audit','nexa_rev869b_management_writer','nexa_rev869b_purge_worker','nexa_rev869b_export_service','nexa_rev869b_target_verifier'] LOOP
            IF NOT EXISTS(SELECT 1 FROM pg_roles WHERE rolname=r AND NOT rolsuper AND NOT rolcreatedb AND NOT rolcreaterole AND NOT rolreplication AND NOT rolbypassrls) THEN RAISE EXCEPTION 'Missing capability-free frozen role %',r; END IF;
          END LOOP;
          IF EXISTS(SELECT 1 FROM pg_auth_members m JOIN pg_roles a ON a.oid=m.roleid JOIN pg_roles b ON b.oid=m.member WHERE a.rolname LIKE 'nexa_rev869b_%' OR b.rolname LIKE 'nexa_rev869b_%') THEN RAISE EXCEPTION 'REV869B roles must have no memberships'; END IF;
        END $roles$;
        CREATE TABLE nexa.rev869b_command_requests(
          "CommandId" uuid PRIMARY KEY,"OrganizationId" text NOT NULL,"Operation" text NOT NULL,"IdempotencyKeySha256" bytea NOT NULL CHECK(octet_length("IdempotencyKeySha256")=32),"RequestSha256" bytea NOT NULL CHECK(octet_length("RequestSha256")=32),
          "ActorEmployeeId" uuid NOT NULL,"IdentityIssuer" text NOT NULL,"IdentitySubject" text NOT NULL,"ActorRole" text NOT NULL,"RegisteredAt" timestamptz NOT NULL DEFAULT clock_timestamp(),"RegisteredBy" name NOT NULL DEFAULT session_user,
          UNIQUE("OrganizationId","Operation","IdempotencyKeySha256"));
        CREATE TABLE nexa.rev869b_command_attempts(
          "AttemptId" uuid PRIMARY KEY,"CommandId" uuid NOT NULL REFERENCES nexa.rev869b_command_requests("CommandId"),"AttemptOrdinal" integer NOT NULL CHECK("AttemptOrdinal">0),"ExecutionInstanceId" uuid NOT NULL,
          "ServiceInstanceSha256" bytea NOT NULL CHECK(octet_length("ServiceInstanceSha256")=32),"OwnershipLeaseSha256" bytea NOT NULL CHECK(octet_length("OwnershipLeaseSha256")=32),"RuntimePrincipal" name NOT NULL,
          "TargetBackendPid" integer NOT NULL,"TargetTransactionId" bigint NOT NULL,"IsActive" boolean NOT NULL DEFAULT true,"StartedAt" timestamptz NOT NULL DEFAULT clock_timestamp(),"StartedBy" name NOT NULL DEFAULT session_user,UNIQUE("CommandId","AttemptOrdinal"));
        CREATE UNIQUE INDEX "UX_rev869b_one_active_command_attempt" ON nexa.rev869b_command_attempts("CommandId") WHERE "IsActive";
        CREATE TABLE nexa.rev869b_command_contexts(
          "ContextToken" uuid PRIMARY KEY,"AttemptId" uuid NOT NULL UNIQUE REFERENCES nexa.rev869b_command_attempts("AttemptId"),"BackendPid" integer NOT NULL,"TransactionId" bigint NOT NULL,"RuntimePrincipal" name NOT NULL,
          "SlotSha256" bytea NOT NULL CHECK(octet_length("SlotSha256")=32),"Slots" jsonb NOT NULL CHECK(jsonb_typeof("Slots")='array' AND jsonb_array_length("Slots")>0),"SlotCount" integer NOT NULL CHECK("SlotCount">0),"OpenedAt" timestamptz NOT NULL DEFAULT transaction_timestamp());
        CREATE TABLE nexa.rev869b_command_claims(
          "ClaimId" bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,"ContextToken" uuid NOT NULL REFERENCES nexa.rev869b_command_contexts("ContextToken"),"ClaimKind" text NOT NULL,"HistoryId" uuid NOT NULL,"EntityType" text NOT NULL,"EntityId" uuid NOT NULL,
          "Operation" text NOT NULL,"ParentVersion" bigint NOT NULL,"FromStatus" text NULL,"ToStatus" text NOT NULL,"Correlation" text NOT NULL,"RemarksSha256" bytea NOT NULL CHECK(octet_length("RemarksSha256")=32),UNIQUE("ContextToken","ClaimKind","HistoryId"));
        CREATE TABLE nexa.rev869b_command_attempt_outcomes(
          "OutcomeId" uuid PRIMARY KEY,"AttemptId" uuid NOT NULL UNIQUE REFERENCES nexa.rev869b_command_attempts("AttemptId"),"TerminalState" text NOT NULL CHECK("TerminalState" IN ('Committed','Rejected','RolledBack','Abandoned')),
          "Category" text NULL,"BusinessSha256" bytea NULL,"OccurredAt" timestamptz NOT NULL DEFAULT clock_timestamp(),"RecordedBy" name NOT NULL DEFAULT session_user,
          CHECK(("TerminalState"='Committed' AND octet_length("BusinessSha256")=32 AND "Category" IS NULL) OR ("TerminalState"<>'Committed' AND "BusinessSha256" IS NULL AND length("Category") BETWEEN 1 AND 100)));
        CREATE TABLE nexa.rev869b_command_receipts(
          "ReceiptId" uuid PRIMARY KEY,"AttemptId" uuid NOT NULL UNIQUE REFERENCES nexa.rev869b_command_attempts("AttemptId"),"CommandId" uuid NOT NULL UNIQUE REFERENCES nexa.rev869b_command_requests("CommandId"),
          "BusinessSha256" bytea NOT NULL CHECK(octet_length("BusinessSha256")=32),"ResponseJson" jsonb NOT NULL,"CommittedAt" timestamptz NOT NULL DEFAULT transaction_timestamp());
        CREATE TABLE nexa.rev869b_purge_authorizations(
          "AuthorizationId" uuid PRIMARY KEY,"ManagementDecisionId" uuid NOT NULL UNIQUE,"PriorAttemptId" uuid NULL,"Scope" text NOT NULL,"Cutoff" timestamptz NOT NULL,"MaximumRows" integer NOT NULL CHECK("MaximumRows" BETWEEN 1 AND 1000),
          "NonceSha256" bytea NOT NULL CHECK(octet_length("NonceSha256")=32),"ExpiresAt" timestamptz NOT NULL,"State" text NOT NULL DEFAULT 'Approved' CHECK("State" IN ('Approved','ZeroRows','Started','Succeeded','Failed','Interrupted')),
          "IssuedAt" timestamptz NOT NULL DEFAULT clock_timestamp(),"IssuedBy" name NOT NULL DEFAULT session_user,CHECK("ExpiresAt">"IssuedAt" AND "ExpiresAt"<="IssuedAt"+interval '15 minutes'));
        CREATE TABLE nexa.rev869b_purge_attempts(
          "PurgeAttemptId" uuid PRIMARY KEY,"AuthorizationId" uuid NOT NULL UNIQUE REFERENCES nexa.rev869b_purge_authorizations("AuthorizationId"),"CandidateCount" integer NOT NULL,"CandidateSha256" bytea NOT NULL CHECK(octet_length("CandidateSha256")=32),
          "State" text NOT NULL CHECK("State" IN ('ZeroRows','Started','Succeeded','Failed','Interrupted')),"StartedAt" timestamptz NOT NULL DEFAULT clock_timestamp(),"TerminalAt" timestamptz NULL,"FailureCategory" text NULL);
        CREATE TABLE nexa.rev869b_purge_candidates("PurgeAttemptId" uuid NOT NULL REFERENCES nexa.rev869b_purge_attempts("PurgeAttemptId"),"LedgerName" text NOT NULL,"RowId" uuid NOT NULL,PRIMARY KEY("PurgeAttemptId","LedgerName","RowId"));
        CREATE TABLE nexa.rev869b_purge_events("EventId" bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,"PurgeAttemptId" uuid NOT NULL,"State" text NOT NULL,"EvidenceSha256" bytea NOT NULL CHECK(octet_length("EvidenceSha256")=32),"OccurredAt" timestamptz NOT NULL DEFAULT clock_timestamp(),"Principal" name NOT NULL DEFAULT session_user,UNIQUE("PurgeAttemptId","State"));
        CREATE TABLE nexa.rev869b_export_authorizations(
          "AuthorizationId" uuid PRIMARY KEY,"ManagementDecisionId" uuid NOT NULL UNIQUE,"OrganizationId" text NOT NULL,"Fields" text[] NOT NULL,"MaximumRows" integer NOT NULL CHECK("MaximumRows" BETWEEN 1 AND 1000),"AsOf" timestamptz NOT NULL,"ExpiresAt" timestamptz NOT NULL,
          "State" text NOT NULL DEFAULT 'Approved' CHECK("State" IN ('Approved','Prepared','Expired')),"IssuedAt" timestamptz NOT NULL DEFAULT clock_timestamp(),"IssuedBy" name NOT NULL DEFAULT session_user,CHECK("ExpiresAt">"IssuedAt" AND "ExpiresAt"<="IssuedAt"+interval '15 minutes'));
        CREATE TABLE nexa.rev869b_export_batches(
          "BatchId" uuid PRIMARY KEY,"AuthorizationId" uuid NOT NULL UNIQUE REFERENCES nexa.rev869b_export_authorizations("AuthorizationId"),"ManagementDecisionId" uuid NOT NULL UNIQUE,"OrganizationId" text NOT NULL,"Fields" text[] NOT NULL,"MaximumRows" integer NOT NULL CHECK("MaximumRows" BETWEEN 1 AND 1000),"AsOf" timestamptz NOT NULL,"ExpiresAt" timestamptz NOT NULL,
          "RowCount" integer NOT NULL,"BatchSha256" bytea NOT NULL CHECK(octet_length("BatchSha256")=32),"PreparedAt" timestamptz NOT NULL DEFAULT clock_timestamp(),CHECK("ExpiresAt">"PreparedAt" AND "ExpiresAt"<="PreparedAt"+interval '15 minutes'));
        CREATE TABLE nexa.rev869b_export_batch_rows("BatchId" uuid NOT NULL REFERENCES nexa.rev869b_export_batches("BatchId"),"Ordinal" integer NOT NULL,"Payload" jsonb NOT NULL,"RowSha256" bytea NOT NULL CHECK(octet_length("RowSha256")=32),PRIMARY KEY("BatchId","Ordinal"));
        CREATE TABLE nexa.rev869b_export_releases("ReleaseId" uuid PRIMARY KEY,"BatchId" uuid NOT NULL REFERENCES nexa.rev869b_export_batches("BatchId"),"State" text NOT NULL CHECK("State" IN ('ReleaseStarted','Delivered','Failed','Interrupted')),"StartedAt" timestamptz NOT NULL DEFAULT clock_timestamp(),"TerminalAt" timestamptz NULL,"OutcomeCategory" text NULL);

        CREATE FUNCTION nexa.rev869b_deny_ledger_mutation() RETURNS trigger LANGUAGE plpgsql AS $f$ BEGIN RAISE EXCEPTION 'REV869B durable ledger is append-only'; END $f$;
        CREATE TRIGGER "TR_rev869b_command_outcomes_immutable" BEFORE UPDATE OR DELETE ON nexa.rev869b_command_attempt_outcomes FOR EACH ROW EXECUTE FUNCTION nexa.rev869b_deny_ledger_mutation();
        CREATE TRIGGER "TR_rev869b_command_receipts_immutable" BEFORE UPDATE OR DELETE ON nexa.rev869b_command_receipts FOR EACH ROW EXECUTE FUNCTION nexa.rev869b_deny_ledger_mutation();
        CREATE TRIGGER "TR_rev869b_purge_events_immutable" BEFORE UPDATE OR DELETE ON nexa.rev869b_purge_events FOR EACH ROW EXECUTE FUNCTION nexa.rev869b_deny_ledger_mutation();
        CREATE TRIGGER "TR_rev869b_export_rows_immutable" BEFORE UPDATE OR DELETE ON nexa.rev869b_export_batch_rows FOR EACH ROW EXECUTE FUNCTION nexa.rev869b_deny_ledger_mutation();

        CREATE FUNCTION nexa.rev869b_register_command_request(organization text,operation text,idempotency_sha bytea,request_sha bytea,actor_employee uuid,identity_issuer text,identity_subject text,actor_role text)
        RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,nexa AS $f$ DECLARE command_id uuid; existing nexa.rev869b_command_requests%ROWTYPE; BEGIN
          IF session_user<>'nexa_rev869b_command_audit' OR organization='' OR operation='' OR octet_length(idempotency_sha)<>32 OR octet_length(request_sha)<>32 THEN RAISE EXCEPTION USING ERRCODE='42501',MESSAGE='Exact command request required'; END IF;
          SELECT * INTO existing FROM nexa.rev869b_command_requests r WHERE r."OrganizationId"=organization AND r."Operation"=operation AND r."IdempotencyKeySha256"=idempotency_sha FOR UPDATE;
          IF FOUND THEN IF existing."RequestSha256"<>request_sha OR existing."ActorEmployeeId"<>actor_employee OR existing."IdentityIssuer"<>identity_issuer OR existing."IdentitySubject"<>identity_subject OR existing."ActorRole"<>actor_role THEN RAISE EXCEPTION USING ERRCODE='23505',CONSTRAINT='rev869b_command_request_replay_mismatch',MESSAGE='Idempotency replay mismatch'; END IF; RETURN existing."CommandId"; END IF;
          command_id:=gen_random_uuid(); INSERT INTO nexa.rev869b_command_requests VALUES(command_id,organization,operation,idempotency_sha,request_sha,actor_employee,identity_issuer,identity_subject,actor_role,clock_timestamp(),session_user); RETURN command_id;
        END $f$;
        CREATE FUNCTION nexa.rev869b_start_command_attempt(command_id uuid,execution_instance uuid,service_sha bytea,ownership_sha bytea,runtime_principal name,backend_pid integer,transaction_id bigint)
        RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,nexa AS $f$ DECLARE attempt_id uuid:=gen_random_uuid(); ordinal integer; active nexa.rev869b_command_attempts%ROWTYPE; BEGIN
          IF session_user<>'nexa_rev869b_command_audit' OR octet_length(service_sha)<>32 OR octet_length(ownership_sha)<>32 OR runtime_principal<>'nexa_rev869b_app_runtime' THEN RAISE EXCEPTION USING ERRCODE='42501',MESSAGE='Exact command attempt required'; END IF;
          PERFORM 1 FROM nexa.rev869b_command_requests WHERE "CommandId"=command_id FOR UPDATE; IF EXISTS(SELECT 1 FROM nexa.rev869b_command_receipts WHERE "CommandId"=command_id) THEN RETURN NULL; END IF;
          SELECT * INTO active FROM nexa.rev869b_command_attempts WHERE "CommandId"=command_id AND "IsActive"; IF FOUND THEN IF active."ExecutionInstanceId"=execution_instance AND active."ServiceInstanceSha256"=service_sha AND active."OwnershipLeaseSha256"=ownership_sha AND active."RuntimePrincipal"=runtime_principal AND active."TargetBackendPid"=backend_pid AND active."TargetTransactionId"=transaction_id THEN RETURN active."AttemptId"; END IF; RAISE EXCEPTION USING ERRCODE='40001',CONSTRAINT='rev869b_command_attempt_active',MESSAGE='Another bound command attempt is active'; END IF;
          SELECT coalesce(max("AttemptOrdinal"),0)+1 INTO ordinal FROM nexa.rev869b_command_attempts WHERE "CommandId"=command_id; INSERT INTO nexa.rev869b_command_attempts VALUES(attempt_id,command_id,ordinal,execution_instance,service_sha,ownership_sha,runtime_principal,backend_pid,transaction_id,true,clock_timestamp(),session_user); RETURN attempt_id;
        END $f$;
        CREATE FUNCTION nexa.rev869b_open_command_attempt(attempt_id uuid,actor_employee uuid,identity_issuer text,identity_subject text,actor_role text,organization text,slot_sha bytea,slots jsonb)
        RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,nexa AS $f$ DECLARE token uuid:=gen_random_uuid(); BEGIN
          IF session_user<>'nexa_rev869b_app_runtime' OR jsonb_typeof(slots)<>'array' OR jsonb_array_length(slots)=0 OR octet_length(slot_sha)<>32 THEN RAISE EXCEPTION USING ERRCODE='42501',MESSAGE='Exact runtime context required'; END IF;
          IF NOT EXISTS(SELECT 1 FROM nexa.rev869b_command_attempts a JOIN nexa.rev869b_command_requests r ON r."CommandId"=a."CommandId" WHERE a."AttemptId"=attempt_id AND a."IsActive" AND a."RuntimePrincipal"=session_user AND a."TargetBackendPid"=pg_backend_pid() AND a."TargetTransactionId"=txid_current() AND r."ActorEmployeeId"=actor_employee AND r."IdentityIssuer"=identity_issuer AND r."IdentitySubject"=identity_subject AND r."ActorRole"=actor_role AND r."OrganizationId"=organization) THEN RAISE EXCEPTION USING ERRCODE='42501',CONSTRAINT='rev869b_attempt_binding',MESSAGE='Attempt binding mismatch'; END IF;
          SELECT "ContextToken" INTO token FROM nexa.rev869b_command_contexts WHERE "AttemptId"=attempt_id AND "BackendPid"=pg_backend_pid() AND "TransactionId"=txid_current();
          IF FOUND THEN
            UPDATE nexa.rev869b_command_contexts SET "SlotSha256"=digest("SlotSha256"||slot_sha,'sha256'),"Slots"="Slots"||slots,"SlotCount"="SlotCount"+jsonb_array_length(slots) WHERE "ContextToken"=token;
          ELSE
            token:=gen_random_uuid(); INSERT INTO nexa.rev869b_command_contexts VALUES(token,attempt_id,pg_backend_pid(),txid_current(),session_user,slot_sha,slots,jsonb_array_length(slots),transaction_timestamp());
          END IF;
          PERFORM set_config('nexa.rev869b_command_token',token::text,true); PERFORM set_config('nexa.rev869b_actor_employee_id',actor_employee::text,true); PERFORM set_config('nexa.rev869b_identity_issuer',identity_issuer,true); PERFORM set_config('nexa.rev869b_identity_subject',identity_subject,true); PERFORM set_config('nexa.rev869b_actor_login',identity_subject,true); PERFORM set_config('nexa.rev869b_actor_role',actor_role,true); PERFORM set_config('nexa.rev869b_organization',organization,true); RETURN token;
        END $f$;
        CREATE FUNCTION nexa.rev869b_command_context_valid(organization text,actor_employee uuid,identity_issuer text,identity_subject text,actor_role text)
        RETURNS boolean LANGUAGE sql SECURITY DEFINER STABLE SET search_path=pg_catalog,nexa AS $f$ SELECT count(*)=1 FROM nexa.rev869b_command_contexts c JOIN nexa.rev869b_command_attempts a ON a."AttemptId"=c."AttemptId" JOIN nexa.rev869b_command_requests r ON r."CommandId"=a."CommandId" WHERE c."ContextToken"=nullif(current_setting('nexa.rev869b_command_token',true),'')::uuid AND c."BackendPid"=pg_backend_pid() AND c."TransactionId"=txid_current() AND c."RuntimePrincipal"=session_user AND a."IsActive" AND r."OrganizationId"=$1 AND r."ActorEmployeeId"=$2 AND r."IdentityIssuer"=$3 AND r."IdentitySubject"=$4 AND r."ActorRole"=$5 $f$;
        CREATE FUNCTION nexa.rev869b_claim_command_context(claim_kind text,history_id uuid,entity_type text,entity_id uuid,operation text,parent_version bigint,from_status text,to_status text,correlation text,remarks text)
        RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,nexa AS $f$ DECLARE token uuid:=nullif(current_setting('nexa.rev869b_command_token',true),'')::uuid; expected jsonb; BEGIN
          SELECT value INTO expected FROM nexa.rev869b_command_contexts c,jsonb_array_elements(c."Slots") value WHERE c."ContextToken"=token AND value->>'claimKind'=claim_kind AND (value->>'historyId')::uuid=history_id AND value->>'entityType'=entity_type AND (value->>'entityId')::uuid=entity_id AND value->>'operation'=operation AND (value->>'parentVersion')::bigint=parent_version AND value->>'toStatus'=to_status AND value->>'correlation'=correlation;
          IF expected IS NULL OR (expected->>'fromStatus') IS DISTINCT FROM from_status OR expected->>'remarks' IS DISTINCT FROM remarks THEN RAISE EXCEPTION USING ERRCODE='42501',CONSTRAINT='rev869b_exact_command_slot',MESSAGE='Exact command slot mismatch'; END IF;
          INSERT INTO nexa.rev869b_command_claims("ContextToken","ClaimKind","HistoryId","EntityType","EntityId","Operation","ParentVersion","FromStatus","ToStatus","Correlation","RemarksSha256") VALUES(token,claim_kind,history_id,entity_type,entity_id,operation,parent_version,from_status,to_status,correlation,digest(remarks,'sha256'));
        END $f$;
        CREATE FUNCTION nexa.rev869b_commit_command_attempt(attempt_id uuid,business_sha bytea,response_json jsonb,receipt_id uuid)
        RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,nexa AS $f$ DECLARE command_id uuid; expected integer; actual integer; exact_business_sha bytea; BEGIN
          IF session_user<>'nexa_rev869b_app_runtime' OR octet_length(business_sha)<>32 THEN RAISE EXCEPTION USING ERRCODE='42501',MESSAGE='Exact runtime commit required'; END IF;
          SELECT a."CommandId",c."SlotCount",c."SlotSha256" INTO STRICT command_id,expected,exact_business_sha FROM nexa.rev869b_command_attempts a JOIN nexa.rev869b_command_contexts c ON c."AttemptId"=a."AttemptId" WHERE a."AttemptId"=attempt_id AND a."IsActive" AND c."BackendPid"=pg_backend_pid() AND c."TransactionId"=txid_current(); SELECT count(*) INTO actual FROM nexa.rev869b_command_claims q JOIN nexa.rev869b_command_contexts c ON c."ContextToken"=q."ContextToken" WHERE c."AttemptId"=attempt_id;
          IF business_sha<>exact_business_sha THEN RAISE EXCEPTION USING ERRCODE='23514',CONSTRAINT='rev869b_command_business_fingerprint',MESSAGE='Committed business fingerprint mismatch'; END IF;
          IF actual<>expected THEN RAISE EXCEPTION USING ERRCODE='23514',CONSTRAINT='rev869b_command_claim_coverage',MESSAGE='Claim coverage mismatch'; END IF;
          INSERT INTO nexa.rev869b_command_receipts VALUES(receipt_id,attempt_id,command_id,exact_business_sha,response_json,transaction_timestamp()); INSERT INTO nexa.rev869b_command_attempt_outcomes VALUES(gen_random_uuid(),attempt_id,'Committed',NULL,exact_business_sha,transaction_timestamp(),session_user); UPDATE nexa.rev869b_command_attempts SET "IsActive"=false WHERE "AttemptId"=attempt_id; RETURN receipt_id;
        END $f$;
        CREATE FUNCTION nexa.rev869b_record_noncommit_outcome(attempt_id uuid,terminal_state text,category text,outcome_id uuid)
        RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,nexa AS $f$ BEGIN
          IF session_user<>'nexa_rev869b_command_audit' OR terminal_state NOT IN ('Rejected','RolledBack','Abandoned') OR length(category) NOT BETWEEN 1 AND 100 THEN RAISE EXCEPTION USING ERRCODE='42501',MESSAGE='Exact noncommit outcome required'; END IF;
          INSERT INTO nexa.rev869b_command_attempt_outcomes VALUES(outcome_id,attempt_id,terminal_state,category,NULL,clock_timestamp(),session_user) ON CONFLICT("AttemptId") DO NOTHING; UPDATE nexa.rev869b_command_attempts SET "IsActive"=false WHERE "AttemptId"=attempt_id AND NOT EXISTS(SELECT 1 FROM nexa.rev869b_command_receipts WHERE "AttemptId"=attempt_id); RETURN (SELECT "OutcomeId" FROM nexa.rev869b_command_attempt_outcomes WHERE "AttemptId"=attempt_id);
        END $f$;
        CREATE FUNCTION nexa.rev869b_reconcile_command_attempt(attempt_id uuid) RETURNS jsonb LANGUAGE sql SECURITY DEFINER STABLE SET search_path=pg_catalog,nexa AS $f$ SELECT jsonb_build_object('attemptId',a."AttemptId",'ordinal',a."AttemptOrdinal",'active',a."IsActive",'terminal',o."TerminalState",'receiptId',r."ReceiptId",'response',r."ResponseJson") FROM nexa.rev869b_command_attempts a LEFT JOIN nexa.rev869b_command_attempt_outcomes o ON o."AttemptId"=a."AttemptId" LEFT JOIN nexa.rev869b_command_receipts r ON r."AttemptId"=a."AttemptId" WHERE a."AttemptId"=$1 AND session_user IN ('nexa_rev869b_command_audit','nexa_rev869b_target_verifier') $f$;
        CREATE FUNCTION nexa.rev869b_read_target_security_state() RETURNS TABLE(request_count bigint,context_count bigint,receipt_count bigint,outcome_count bigint,attempt_count bigint,attempt_sha256 text) LANGUAGE sql SECURITY DEFINER STABLE SET search_path=pg_catalog,nexa AS $f$
          SELECT (SELECT count(*) FROM nexa.rev869b_command_requests),(SELECT count(*) FROM nexa.rev869b_command_contexts),(SELECT count(*) FROM nexa.rev869b_command_receipts),(SELECT count(*) FROM nexa.rev869b_command_attempt_outcomes),(SELECT count(*) FROM nexa.rev869b_command_attempts),(SELECT encode(digest(coalesce(string_agg("AttemptId"::text,',' ORDER BY "AttemptId"),''),'sha256'),'hex') FROM nexa.rev869b_command_attempts) WHERE session_user='nexa_rev869b_target_verifier' $f$;

        CREATE FUNCTION nexa.rev869b_register_purge_authorization(authorization_id uuid,decision_id uuid,prior_attempt uuid,scope text,cutoff timestamptz,maximum_rows integer,nonce_sha bytea,expires_at timestamptz) RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,nexa AS $f$ BEGIN IF session_user<>'nexa_rev869b_management_writer' THEN RAISE EXCEPTION USING ERRCODE='42501',MESSAGE='Management writer required'; END IF; INSERT INTO nexa.rev869b_purge_authorizations("AuthorizationId","ManagementDecisionId","PriorAttemptId","Scope","Cutoff","MaximumRows","NonceSha256","ExpiresAt") VALUES(authorization_id,decision_id,prior_attempt,scope,cutoff,maximum_rows,nonce_sha,expires_at); RETURN authorization_id; END $f$;
        CREATE FUNCTION nexa.rev869b_start_purge(authorization_id uuid,purge_attempt_id uuid) RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,nexa AS $f$ DECLARE count_rows integer; candidate_sha bytea; BEGIN
          IF session_user<>'nexa_rev869b_purge_worker' THEN RAISE EXCEPTION USING ERRCODE='42501',MESSAGE='Purge worker required'; END IF; PERFORM 1 FROM nexa.rev869b_purge_authorizations WHERE "AuthorizationId"=authorization_id AND "State"='Approved' AND "ExpiresAt">clock_timestamp() FOR UPDATE; IF NOT FOUND THEN RAISE EXCEPTION 'Purge authorization unavailable'; END IF;
          INSERT INTO nexa.rev869b_purge_attempts VALUES(purge_attempt_id,authorization_id,0,digest('','sha256'),'Started',clock_timestamp(),NULL,NULL);
          INSERT INTO nexa.rev869b_purge_candidates SELECT purge_attempt_id,'command_contexts',c."ContextToken" FROM nexa.rev869b_command_contexts c WHERE c."OpenedAt"<(SELECT "Cutoff" FROM nexa.rev869b_purge_authorizations WHERE "AuthorizationId"=authorization_id) ORDER BY c."ContextToken" LIMIT (SELECT "MaximumRows" FROM nexa.rev869b_purge_authorizations WHERE "AuthorizationId"=authorization_id); GET DIAGNOSTICS count_rows=ROW_COUNT;
          SELECT digest(coalesce(string_agg("LedgerName"||':'||"RowId"::text,',' ORDER BY "LedgerName","RowId"),''),'sha256') INTO candidate_sha FROM nexa.rev869b_purge_candidates WHERE "PurgeAttemptId"=purge_attempt_id;
          UPDATE nexa.rev869b_purge_attempts SET "CandidateCount"=count_rows,"CandidateSha256"=candidate_sha,"State"=CASE WHEN count_rows=0 THEN 'ZeroRows' ELSE 'Started' END,"TerminalAt"=CASE WHEN count_rows=0 THEN clock_timestamp() ELSE NULL END WHERE "PurgeAttemptId"=purge_attempt_id; UPDATE nexa.rev869b_purge_authorizations SET "State"=CASE WHEN count_rows=0 THEN 'ZeroRows' ELSE 'Started' END WHERE "AuthorizationId"=authorization_id; INSERT INTO nexa.rev869b_purge_events VALUES(DEFAULT,purge_attempt_id,CASE WHEN count_rows=0 THEN 'ZeroRows' ELSE 'Started' END,candidate_sha,clock_timestamp(),session_user); RETURN purge_attempt_id;
        END $f$;
        CREATE FUNCTION nexa.rev869b_execute_purge(purge_attempt_id uuid) RETURNS integer LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,nexa AS $f$ DECLARE expected integer; deleted integer; evidence bytea; BEGIN
          IF session_user<>'nexa_rev869b_purge_worker' THEN RAISE EXCEPTION USING ERRCODE='42501',MESSAGE='Purge worker required'; END IF; SELECT "CandidateCount" INTO STRICT expected FROM nexa.rev869b_purge_attempts WHERE "PurgeAttemptId"=purge_attempt_id AND "State"='Started' FOR UPDATE;
          IF EXISTS(SELECT 1 FROM nexa.rev869b_purge_candidates p JOIN nexa.rev869b_command_contexts c ON c."ContextToken"=p."RowId" JOIN nexa.rev869b_command_attempts a ON a."AttemptId"=c."AttemptId" WHERE p."PurgeAttemptId"=purge_attempt_id AND a."IsActive") THEN RAISE EXCEPTION USING ERRCODE='40001',CONSTRAINT='rev869b_purge_candidate_drift',MESSAGE='Frozen candidates drifted'; END IF; DELETE FROM nexa.rev869b_command_claims q USING nexa.rev869b_purge_candidates p WHERE p."PurgeAttemptId"=purge_attempt_id AND p."LedgerName"='command_contexts' AND q."ContextToken"=p."RowId"; DELETE FROM nexa.rev869b_command_contexts c USING nexa.rev869b_purge_candidates p WHERE p."PurgeAttemptId"=purge_attempt_id AND p."LedgerName"='command_contexts' AND c."ContextToken"=p."RowId"; GET DIAGNOSTICS deleted=ROW_COUNT; IF deleted<>expected THEN RAISE EXCEPTION USING ERRCODE='40001',CONSTRAINT='rev869b_purge_candidate_drift',MESSAGE='Frozen candidates drifted'; END IF;
          evidence:=digest(purge_attempt_id::text||':'||deleted::text,'sha256'); UPDATE nexa.rev869b_purge_attempts SET "State"='Succeeded',"TerminalAt"=clock_timestamp() WHERE "PurgeAttemptId"=purge_attempt_id; UPDATE nexa.rev869b_purge_authorizations SET "State"='Succeeded' WHERE "AuthorizationId"=(SELECT "AuthorizationId" FROM nexa.rev869b_purge_attempts WHERE "PurgeAttemptId"=purge_attempt_id); INSERT INTO nexa.rev869b_purge_events VALUES(DEFAULT,purge_attempt_id,'Succeeded',evidence,clock_timestamp(),session_user); RETURN deleted;
        END $f$;
        CREATE FUNCTION nexa.rev869b_record_purge_failure(purge_attempt_id uuid,terminal_state text,category text,evidence bytea) RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,nexa AS $f$ BEGIN IF session_user<>'nexa_rev869b_purge_worker' OR terminal_state NOT IN ('Failed','Interrupted') OR length(category) NOT BETWEEN 1 AND 100 THEN RAISE EXCEPTION USING ERRCODE='42501',MESSAGE='Exact purge failure required'; END IF; UPDATE nexa.rev869b_purge_attempts SET "State"=terminal_state,"TerminalAt"=clock_timestamp(),"FailureCategory"=category WHERE "PurgeAttemptId"=purge_attempt_id AND "State"='Started'; IF NOT FOUND THEN RAISE EXCEPTION 'Purge attempt not Started'; END IF; UPDATE nexa.rev869b_purge_authorizations SET "State"=terminal_state WHERE "AuthorizationId"=(SELECT "AuthorizationId" FROM nexa.rev869b_purge_attempts WHERE "PurgeAttemptId"=purge_attempt_id); INSERT INTO nexa.rev869b_purge_events VALUES(DEFAULT,purge_attempt_id,terminal_state,evidence,clock_timestamp(),session_user); RETURN purge_attempt_id; END $f$;
        CREATE FUNCTION nexa.rev869b_reconcile_purge(purge_attempt_id uuid) RETURNS jsonb LANGUAGE sql SECURITY DEFINER STABLE SET search_path=pg_catalog,nexa AS $f$ SELECT to_jsonb(p) FROM nexa.rev869b_purge_attempts p WHERE p."PurgeAttemptId"=$1 AND session_user IN ('nexa_rev869b_purge_worker','nexa_rev869b_target_verifier') $f$;

        CREATE FUNCTION nexa.rev869b_register_export_authorization(authorization_id uuid,decision_id uuid,organization text,fields text[],maximum_rows integer,as_of timestamptz,expires_at timestamptz) RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,nexa AS $f$ DECLARE allowed text[]:=ARRAY['occurredAt','eventType','organizationId','attemptId']; BEGIN IF session_user<>'nexa_rev869b_management_writer' OR fields<@allowed IS NOT TRUE OR array_length(fields,1) IS NULL THEN RAISE EXCEPTION USING ERRCODE='42501',MESSAGE='Management-approved export allowlist required'; END IF; INSERT INTO nexa.rev869b_export_authorizations("AuthorizationId","ManagementDecisionId","OrganizationId","Fields","MaximumRows","AsOf","ExpiresAt") VALUES(authorization_id,decision_id,organization,fields,maximum_rows,as_of,expires_at); RETURN authorization_id; END $f$;
        CREATE FUNCTION nexa.rev869b_prepare_export_batch(batch_id uuid,authorization_id uuid) RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,nexa AS $f$ DECLARE a nexa.rev869b_export_authorizations%ROWTYPE; rows_count integer; batch_sha bytea; BEGIN
          IF session_user<>'nexa_rev869b_export_service' THEN RAISE EXCEPTION USING ERRCODE='42501',MESSAGE='Controlled export service required'; END IF; SELECT * INTO STRICT a FROM nexa.rev869b_export_authorizations WHERE "AuthorizationId"=authorization_id AND "State"='Approved' AND "ExpiresAt">clock_timestamp() FOR UPDATE;
          INSERT INTO nexa.rev869b_export_batches VALUES(batch_id,authorization_id,a."ManagementDecisionId",a."OrganizationId",a."Fields",a."MaximumRows",a."AsOf",a."ExpiresAt",0,digest('','sha256'),clock_timestamp()); INSERT INTO nexa.rev869b_export_batch_rows SELECT batch_id,row_number() OVER(ORDER BY o."OccurredAt",o."OutcomeId")::integer,jsonb_strip_nulls(jsonb_build_object('occurredAt',o."OccurredAt",'eventType',o."TerminalState",'organizationId',r."OrganizationId",'attemptId',o."AttemptId")),digest(jsonb_strip_nulls(jsonb_build_object('occurredAt',o."OccurredAt",'eventType',o."TerminalState",'organizationId',r."OrganizationId",'attemptId',o."AttemptId"))::text,'sha256') FROM nexa.rev869b_command_attempt_outcomes o JOIN nexa.rev869b_command_attempts a2 ON a2."AttemptId"=o."AttemptId" JOIN nexa.rev869b_command_requests r ON r."CommandId"=a2."CommandId" WHERE r."OrganizationId"=a."OrganizationId" AND o."OccurredAt"<=a."AsOf" ORDER BY o."OccurredAt",o."OutcomeId" LIMIT a."MaximumRows";
          GET DIAGNOSTICS rows_count=ROW_COUNT; SELECT digest(coalesce(string_agg(encode("RowSha256",'hex'),',' ORDER BY "Ordinal"),''),'sha256') INTO batch_sha FROM nexa.rev869b_export_batch_rows WHERE "BatchId"=batch_id; UPDATE nexa.rev869b_export_batches SET "RowCount"=rows_count,"BatchSha256"=batch_sha WHERE "BatchId"=batch_id; UPDATE nexa.rev869b_export_authorizations SET "State"='Prepared' WHERE "AuthorizationId"=authorization_id; RETURN batch_id;
        END $f$;
        CREATE FUNCTION nexa.rev869b_authorize_export_release(batch_id uuid,release_id uuid) RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,nexa AS $f$ BEGIN IF session_user<>'nexa_rev869b_export_service' OR NOT EXISTS(SELECT 1 FROM nexa.rev869b_export_batches WHERE "BatchId"=batch_id AND "ExpiresAt">clock_timestamp()) THEN RAISE EXCEPTION USING ERRCODE='42501',MESSAGE='Prepared unexpired batch required'; END IF; INSERT INTO nexa.rev869b_export_releases VALUES(release_id,batch_id,'ReleaseStarted',clock_timestamp(),NULL,NULL); RETURN release_id; END $f$;
        CREATE FUNCTION nexa.rev869b_read_prepared_export_batch(batch_id uuid,release_id uuid) RETURNS TABLE(ordinal integer,payload jsonb,row_sha256 bytea) LANGUAGE sql SECURITY DEFINER STABLE SET search_path=pg_catalog,nexa AS $f$ SELECT r."Ordinal",r."Payload",r."RowSha256" FROM nexa.rev869b_export_batch_rows r JOIN nexa.rev869b_export_releases x ON x."BatchId"=r."BatchId" WHERE r."BatchId"=$1 AND x."ReleaseId"=$2 AND x."State"='ReleaseStarted' AND session_user='nexa_rev869b_export_service' ORDER BY r."Ordinal" $f$;
        CREATE FUNCTION nexa.rev869b_record_export_release_outcome(release_id uuid,terminal_state text,category text) RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,nexa AS $f$ BEGIN IF session_user<>'nexa_rev869b_export_service' OR terminal_state NOT IN ('Delivered','Failed','Interrupted') THEN RAISE EXCEPTION USING ERRCODE='42501',MESSAGE='Exact release outcome required'; END IF; UPDATE nexa.rev869b_export_releases SET "State"=terminal_state,"TerminalAt"=clock_timestamp(),"OutcomeCategory"=CASE WHEN terminal_state='Delivered' THEN NULL ELSE category END WHERE "ReleaseId"=release_id AND "State"='ReleaseStarted'; IF NOT FOUND THEN RAISE EXCEPTION 'Release missing or terminal'; END IF; RETURN release_id; END $f$;

        DO $ownership$ DECLARE o regclass; f regprocedure; BEGIN
          FOR o IN SELECT c.oid::regclass FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='nexa' AND c.relname LIKE 'rev869b_%' AND c.relkind IN ('r','S') LOOP EXECUTE format('ALTER TABLE %s OWNER TO nexa_rev869b_security_owner',o); END LOOP;
          FOR f IN SELECT p.oid::regprocedure FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='nexa' AND p.proname LIKE 'rev869b_%' LOOP EXECUTE format('ALTER FUNCTION %s OWNER TO nexa_rev869b_security_owner',f); END LOOP;
        END $ownership$;
        REVOKE ALL ON ALL TABLES IN SCHEMA nexa FROM PUBLIC,nexa_rev869b_app_runtime,nexa_rev869b_command_audit,nexa_rev869b_management_writer,nexa_rev869b_purge_worker,nexa_rev869b_export_service,nexa_rev869b_target_verifier;
        REVOKE EXECUTE ON ALL FUNCTIONS IN SCHEMA nexa FROM PUBLIC,nexa_rev869b_app_runtime,nexa_rev869b_command_audit,nexa_rev869b_management_writer,nexa_rev869b_purge_worker,nexa_rev869b_export_service,nexa_rev869b_target_verifier;
        GRANT USAGE ON SCHEMA nexa TO nexa_rev869b_app_runtime,nexa_rev869b_command_audit,nexa_rev869b_management_writer,nexa_rev869b_purge_worker,nexa_rev869b_export_service,nexa_rev869b_target_verifier;
        GRANT SELECT ON nexa.employees,nexa.employee_identity_mappings,nexa.employee_role_assignments,nexa.employee_operational_scopes,nexa.roles,nexa.role_page_permissions,nexa.page_definitions,nexa.items,nexa.uoms,nexa.uom_conversions,nexa.vendors,nexa.tax_gst_settings,nexa.organization_policies,nexa.warehouses,nexa.purchase_requisitions,nexa.purchase_requisition_lines,nexa.purchase_requirement_handoffs,nexa.purchase_approval_route_settings,nexa.purchase_approval_workflow_steps,nexa.purchase_transaction_approval_policies TO nexa_rev869b_app_runtime;
        GRANT SELECT,INSERT,UPDATE ON nexa.vendor_qualifications,nexa.controlled_configuration_histories,nexa.request_for_quotations,nexa.request_for_quotation_lines,nexa.rfq_vendor_invitations,nexa.vendor_quotations,nexa.vendor_quotation_lines,nexa.quotation_technical_verifications,nexa.commercial_comparisons,nexa.commercial_comparison_lines,nexa.purchase_transaction_status_history,nexa.purchase_transaction_approval_history,nexa.purchase_orders,nexa.purchase_order_lines,nexa.purchase_order_history,nexa.material_followup_handoffs,nexa.purchase_number_sequences TO nexa_rev869b_app_runtime;
        GRANT SELECT,INSERT ON nexa.audit_logs TO nexa_rev869b_app_runtime;
        GRANT EXECUTE ON FUNCTION nexa.rev869b_open_command_attempt(uuid,uuid,text,text,text,text,bytea,jsonb),nexa.rev869b_command_context_valid(text,uuid,text,text,text),nexa.rev869b_claim_command_context(text,uuid,text,uuid,text,bigint,text,text,text,text),nexa.rev869b_commit_command_attempt(uuid,bytea,jsonb,uuid) TO nexa_rev869b_app_runtime;
        GRANT EXECUTE ON FUNCTION nexa.rev869b_register_command_request(text,text,bytea,bytea,uuid,text,text,text),nexa.rev869b_start_command_attempt(uuid,uuid,bytea,bytea,name,integer,bigint),nexa.rev869b_record_noncommit_outcome(uuid,text,text,uuid),nexa.rev869b_reconcile_command_attempt(uuid) TO nexa_rev869b_command_audit;
        GRANT EXECUTE ON FUNCTION nexa.rev869b_register_purge_authorization(uuid,uuid,uuid,text,timestamptz,integer,bytea,timestamptz),nexa.rev869b_register_export_authorization(uuid,uuid,text,text[],integer,timestamptz,timestamptz) TO nexa_rev869b_management_writer;
        GRANT EXECUTE ON FUNCTION nexa.rev869b_start_purge(uuid,uuid),nexa.rev869b_execute_purge(uuid),nexa.rev869b_record_purge_failure(uuid,text,text,bytea),nexa.rev869b_reconcile_purge(uuid) TO nexa_rev869b_purge_worker;
        GRANT EXECUTE ON FUNCTION nexa.rev869b_prepare_export_batch(uuid,uuid),nexa.rev869b_authorize_export_release(uuid,uuid),nexa.rev869b_read_prepared_export_batch(uuid,uuid),nexa.rev869b_record_export_release_outcome(uuid,text,text) TO nexa_rev869b_export_service;
        GRANT EXECUTE ON FUNCTION nexa.rev869b_reconcile_command_attempt(uuid),nexa.rev869b_reconcile_purge(uuid),nexa.rev869b_read_target_security_state() TO nexa_rev869b_target_verifier;
        ALTER DEFAULT PRIVILEGES FOR ROLE nexa_rev869b_security_owner IN SCHEMA nexa REVOKE ALL ON TABLES FROM PUBLIC;
        ALTER DEFAULT PRIVILEGES FOR ROLE nexa_rev869b_security_owner IN SCHEMA nexa REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC;
        """;

    internal const string Remove = """
        DROP FUNCTION IF EXISTS nexa.rev869b_record_export_release_outcome(uuid,text,text);
        DROP FUNCTION IF EXISTS nexa.rev869b_read_prepared_export_batch(uuid,uuid);
        DROP FUNCTION IF EXISTS nexa.rev869b_authorize_export_release(uuid,uuid);
        DROP FUNCTION IF EXISTS nexa.rev869b_prepare_export_batch(uuid,uuid);
        DROP FUNCTION IF EXISTS nexa.rev869b_register_export_authorization(uuid,uuid,text,text[],integer,timestamptz,timestamptz);
        DROP FUNCTION IF EXISTS nexa.rev869b_reconcile_purge(uuid);
        DROP FUNCTION IF EXISTS nexa.rev869b_record_purge_failure(uuid,text,text,bytea);
        DROP FUNCTION IF EXISTS nexa.rev869b_execute_purge(uuid);
        DROP FUNCTION IF EXISTS nexa.rev869b_start_purge(uuid,uuid);
        DROP FUNCTION IF EXISTS nexa.rev869b_register_purge_authorization(uuid,uuid,uuid,text,timestamptz,integer,bytea,timestamptz);
        DROP FUNCTION IF EXISTS nexa.rev869b_read_target_security_state();
        DROP FUNCTION IF EXISTS nexa.rev869b_reconcile_command_attempt(uuid);
        DROP FUNCTION IF EXISTS nexa.rev869b_record_noncommit_outcome(uuid,text,text,uuid);
        DROP FUNCTION IF EXISTS nexa.rev869b_commit_command_attempt(uuid,bytea,jsonb,uuid);
        DROP FUNCTION IF EXISTS nexa.rev869b_claim_command_context(text,uuid,text,uuid,text,bigint,text,text,text,text);
        DROP FUNCTION IF EXISTS nexa.rev869b_command_context_valid(text,uuid,text,text,text);
        DROP FUNCTION IF EXISTS nexa.rev869b_open_command_attempt(uuid,uuid,text,text,text,text,bytea,jsonb);
        DROP FUNCTION IF EXISTS nexa.rev869b_start_command_attempt(uuid,uuid,bytea,bytea,name,integer,bigint);
        DROP FUNCTION IF EXISTS nexa.rev869b_register_command_request(text,text,bytea,bytea,uuid,text,text,text);
        DROP TABLE IF EXISTS nexa.rev869b_export_releases,nexa.rev869b_export_batch_rows,nexa.rev869b_export_batches,nexa.rev869b_export_authorizations;
        DROP TABLE IF EXISTS nexa.rev869b_purge_events,nexa.rev869b_purge_candidates,nexa.rev869b_purge_attempts,nexa.rev869b_purge_authorizations;
        DROP TABLE IF EXISTS nexa.rev869b_command_receipts,nexa.rev869b_command_attempt_outcomes,nexa.rev869b_command_claims,nexa.rev869b_command_contexts,nexa.rev869b_command_attempts,nexa.rev869b_command_requests;
        DROP FUNCTION IF EXISTS nexa.rev869b_deny_ledger_mutation();
        """;
}
