namespace SESS.NexaERP.Infrastructure.Persistence.Migrations;

/// <summary>Frozen Correction 19 target-local command, purge and export ledgers.</summary>
internal static class Rev869BCommandContextSql
{
    internal const string Install = """
        DO $roles$ DECLARE r text; expected_login boolean; BEGIN
          FOR r,expected_login IN SELECT * FROM (VALUES
            ('nexa_rev869b_security_owner',false),('nexa_rev869b_app_runtime',true),('nexa_rev869b_command_audit',true),
            ('nexa_rev869b_management_writer',true),('nexa_rev869b_purge_worker',true),('nexa_rev869b_purge_audit',true),
            ('nexa_rev869b_export_service',true),('nexa_rev869b_target_verifier',true)) AS expected(name,can_login) LOOP
            IF NOT EXISTS(SELECT 1 FROM pg_roles WHERE rolname=r AND rolcanlogin=expected_login AND NOT rolinherit AND NOT rolsuper AND NOT rolcreatedb AND NOT rolcreaterole AND NOT rolreplication AND NOT rolbypassrls AND rolconnlimit=-1 AND rolvaliduntil IS NULL) THEN RAISE EXCEPTION 'Missing or noncanonical capability-free frozen role %',r; END IF;
          END LOOP;
          IF EXISTS(SELECT 1 FROM pg_auth_members m JOIN pg_roles a ON a.oid=m.roleid JOIN pg_roles b ON b.oid=m.member WHERE a.rolname LIKE 'nexa_rev869b_%' OR b.rolname LIKE 'nexa_rev869b_%') THEN RAISE EXCEPTION 'REV869B roles must have no memberships'; END IF;
        END $roles$;
        CREATE TABLE nexa.rev869b_command_requests(
          "CommandId" uuid PRIMARY KEY,"OrganizationId" text NOT NULL,"Operation" text NOT NULL,"IdempotencyKeySha256" bytea NOT NULL CHECK(octet_length("IdempotencyKeySha256")=32),"RequestSha256" bytea NOT NULL CHECK(octet_length("RequestSha256")=32),
          "ActorEmployeeId" uuid NOT NULL,"IdentityIssuer" text NOT NULL,"IdentitySubject" text NOT NULL,"ActorRole" text NOT NULL,"RegisteredAt" timestamptz NOT NULL DEFAULT clock_timestamp(),"RegisteredBy" name NOT NULL DEFAULT session_user,
          UNIQUE("OrganizationId","Operation","IdempotencyKeySha256"));
        CREATE TABLE nexa.rev869b_command_attempts(
          "AttemptId" uuid PRIMARY KEY,"CommandId" uuid NOT NULL REFERENCES nexa.rev869b_command_requests("CommandId"),"AttemptOrdinal" integer NOT NULL CHECK("AttemptOrdinal">0),"ExecutionInstanceId" uuid NOT NULL,
          "ServiceInstanceSha256" bytea NOT NULL CHECK(octet_length("ServiceInstanceSha256")=32),"OwnershipLeaseSha256" bytea NOT NULL CHECK(octet_length("OwnershipLeaseSha256")=32),"RuntimePrincipal" name NOT NULL,
          "TargetBackendPid" integer NOT NULL,"TargetTransactionId" bigint NOT NULL,"IsActive" boolean NOT NULL DEFAULT true,"StartedAt" timestamptz NOT NULL DEFAULT clock_timestamp(),"StartedBy" name NOT NULL DEFAULT session_user,UNIQUE("CommandId","AttemptOrdinal"));
        CREATE UNIQUE INDEX "UX_rev869b_one_active_command_attempt" ON nexa.rev869b_command_attempts("CommandId") WHERE "IsActive";
        CREATE TABLE nexa.rev869b_command_contexts(
          "ContextToken" uuid PRIMARY KEY,"AttemptId" uuid NOT NULL UNIQUE REFERENCES nexa.rev869b_command_attempts("AttemptId"),"BackendPid" integer NOT NULL,"TransactionId" bigint NOT NULL,"RuntimePrincipal" name NOT NULL,
          "SlotSha256" bytea NOT NULL CHECK(octet_length("SlotSha256")=32),"Slots" jsonb NOT NULL CHECK(jsonb_typeof("Slots")='array' AND jsonb_array_length("Slots")>0),"SlotCount" integer NOT NULL CHECK("SlotCount">0),"OpenedAt" timestamptz NOT NULL DEFAULT transaction_timestamp());
        CREATE TABLE nexa.rev869b_command_claims(
          "ClaimId" bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,"ContextToken" uuid NOT NULL REFERENCES nexa.rev869b_command_contexts("ContextToken"),"ClaimKind" text NOT NULL,"HistoryId" uuid NOT NULL,"EntityType" text NOT NULL,"EntityId" uuid NOT NULL,
          "Operation" text NOT NULL,"ParentVersion" bigint NOT NULL,"FromStatus" text NULL,"ToStatus" text NOT NULL,"Correlation" text NOT NULL,"RemarksSha256" bytea NOT NULL CHECK(octet_length("RemarksSha256")=32),UNIQUE("ContextToken","ClaimKind","HistoryId"));
        CREATE TABLE nexa.rev869b_command_attempt_outcomes(
          "OutcomeId" uuid PRIMARY KEY,"AttemptId" uuid NOT NULL UNIQUE REFERENCES nexa.rev869b_command_attempts("AttemptId"),"TerminalState" text NOT NULL CHECK("TerminalState" IN ('Committed','Rejected','RolledBack','Abandoned')),
          "Category" text NULL,"BusinessSha256" bytea NULL,"OccurredAt" timestamptz NOT NULL DEFAULT clock_timestamp(),"RecordedBy" name NOT NULL DEFAULT session_user,
          CHECK(("TerminalState"='Committed' AND octet_length("BusinessSha256")=32 AND "Category" IS NULL) OR ("TerminalState"<>'Committed' AND "BusinessSha256" IS NULL AND length("Category") BETWEEN 1 AND 100)));
        CREATE TABLE nexa.rev869b_command_receipts(
          "ReceiptId" uuid PRIMARY KEY,"AttemptId" uuid NOT NULL UNIQUE REFERENCES nexa.rev869b_command_attempts("AttemptId"),"CommandId" uuid NOT NULL UNIQUE REFERENCES nexa.rev869b_command_requests("CommandId"),
          "BusinessSha256" bytea NOT NULL CHECK(octet_length("BusinessSha256")=32),"ResponseJson" jsonb NOT NULL,"CommittedAt" timestamptz NOT NULL DEFAULT transaction_timestamp());
        CREATE TABLE nexa.rev869b_purge_authorizations(
          "AuthorizationId" uuid PRIMARY KEY,"ManagementDecisionId" uuid NOT NULL UNIQUE,"PriorAttemptId" uuid NULL,"Scope" text NOT NULL,"Cutoff" timestamptz NOT NULL,"MaximumRows" integer NOT NULL CHECK("MaximumRows" BETWEEN 1 AND 1000),
          "NonceSha256" bytea NOT NULL CHECK(octet_length("NonceSha256")=32),"ExpiresAt" timestamptz NOT NULL,"State" text NOT NULL DEFAULT 'Approved' CHECK("State" IN ('Approved','ZeroRows','Started','Succeeded','Failed','Interrupted')),
          "IssuedAt" timestamptz NOT NULL DEFAULT clock_timestamp(),"IssuedBy" name NOT NULL DEFAULT session_user,CHECK("ExpiresAt">"IssuedAt" AND "ExpiresAt"<="IssuedAt"+interval '15 minutes'));
        CREATE TABLE nexa.rev869b_purge_attempts(
          "PurgeAttemptId" uuid PRIMARY KEY,"AuthorizationId" uuid NOT NULL UNIQUE REFERENCES nexa.rev869b_purge_authorizations("AuthorizationId"),"CandidateCount" integer NOT NULL,"CandidateSha256" bytea NOT NULL CHECK(octet_length("CandidateSha256")=32),
          "State" text NOT NULL CHECK("State" IN ('ZeroRows','Started','Succeeded','Failed','Interrupted')),"StartedAt" timestamptz NOT NULL DEFAULT clock_timestamp(),"TerminalAt" timestamptz NULL,"FailureCategory" text NULL);
        ALTER TABLE nexa.rev869b_purge_authorizations ADD CONSTRAINT "FK_rev869b_purge_authorizations_prior_attempt" FOREIGN KEY("PriorAttemptId") REFERENCES nexa.rev869b_purge_attempts("PurgeAttemptId");
        CREATE TABLE nexa.rev869b_purge_candidates("PurgeAttemptId" uuid NOT NULL REFERENCES nexa.rev869b_purge_attempts("PurgeAttemptId"),"LedgerName" text NOT NULL,"RowId" uuid NOT NULL,PRIMARY KEY("PurgeAttemptId","LedgerName","RowId"));
        CREATE TABLE nexa.rev869b_purge_events("EventId" bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,"PurgeAttemptId" uuid NOT NULL,"State" text NOT NULL,"EvidenceSha256" bytea NOT NULL CHECK(octet_length("EvidenceSha256")=32),"OccurredAt" timestamptz NOT NULL DEFAULT clock_timestamp(),"Principal" name NOT NULL DEFAULT session_user,UNIQUE("PurgeAttemptId","State"));
        CREATE TABLE nexa.rev869b_export_authorizations(
          "AuthorizationId" uuid PRIMARY KEY,"ManagementDecisionId" uuid NOT NULL UNIQUE,"OrganizationId" text NOT NULL,"Fields" text[] NOT NULL,"MaximumRows" integer NOT NULL CHECK("MaximumRows" BETWEEN 1 AND 1000),"AsOf" timestamptz NOT NULL,"ExpiresAt" timestamptz NOT NULL,
          "State" text NOT NULL DEFAULT 'Approved' CHECK("State" IN ('Approved','Prepared','Expired')),"IssuedAt" timestamptz NOT NULL DEFAULT clock_timestamp(),"IssuedBy" name NOT NULL DEFAULT session_user,CHECK("ExpiresAt">"IssuedAt" AND "ExpiresAt"<="IssuedAt"+interval '15 minutes'));
        CREATE TABLE nexa.rev869b_export_batches(
          "BatchId" uuid PRIMARY KEY,"AuthorizationId" uuid NOT NULL UNIQUE REFERENCES nexa.rev869b_export_authorizations("AuthorizationId"),"ManagementDecisionId" uuid NOT NULL UNIQUE,"OrganizationId" text NOT NULL,"Fields" text[] NOT NULL,"MaximumRows" integer NOT NULL CHECK("MaximumRows" BETWEEN 1 AND 1000),"AsOf" timestamptz NOT NULL,"ExpiresAt" timestamptz NOT NULL,
          "RowCount" integer NOT NULL,"BatchSha256" bytea NOT NULL CHECK(octet_length("BatchSha256")=32),"PreparedAt" timestamptz NOT NULL DEFAULT clock_timestamp(),CHECK("ExpiresAt">"PreparedAt" AND "ExpiresAt"<="PreparedAt"+interval '15 minutes'));
        CREATE TABLE nexa.rev869b_export_batch_rows("BatchId" uuid NOT NULL REFERENCES nexa.rev869b_export_batches("BatchId"),"Ordinal" integer NOT NULL,"Payload" jsonb NOT NULL,"RowSha256" bytea NOT NULL CHECK(octet_length("RowSha256")=32),PRIMARY KEY("BatchId","Ordinal"));
        CREATE TABLE nexa.rev869b_export_releases("ReleaseId" uuid PRIMARY KEY,"BatchId" uuid NOT NULL REFERENCES nexa.rev869b_export_batches("BatchId"),"State" text NOT NULL CHECK("State" IN ('ReleaseStarted','Delivered','Failed','Interrupted')),"StartedAt" timestamptz NOT NULL DEFAULT clock_timestamp(),"TerminalAt" timestamptz NULL,"OutcomeCategory" text NULL);
        CREATE UNIQUE INDEX "UX_rev869b_one_active_export_release" ON nexa.rev869b_export_releases("BatchId") WHERE "State"='ReleaseStarted';
        CREATE TABLE nexa.rev869b_target_catalogue_manifest("ManifestId" boolean PRIMARY KEY DEFAULT true CHECK("ManifestId"),"CatalogueSha256" text NULL CHECK("CatalogueSha256" IS NULL OR "CatalogueSha256"~'^[0-9a-f]{64}$'));
        INSERT INTO nexa.rev869b_target_catalogue_manifest VALUES(true,NULL);

        CREATE FUNCTION nexa.rev869b_deny_ledger_mutation() RETURNS trigger LANGUAGE plpgsql AS $f$ BEGIN RAISE EXCEPTION 'REV869B durable ledger is append-only'; END $f$;
        CREATE TRIGGER "TR_rev869b_command_outcomes_immutable" BEFORE UPDATE OR DELETE ON nexa.rev869b_command_attempt_outcomes FOR EACH ROW EXECUTE FUNCTION nexa.rev869b_deny_ledger_mutation();
        CREATE TRIGGER "TR_rev869b_command_receipts_immutable" BEFORE UPDATE OR DELETE ON nexa.rev869b_command_receipts FOR EACH ROW EXECUTE FUNCTION nexa.rev869b_deny_ledger_mutation();
        CREATE TRIGGER "TR_rev869b_purge_events_immutable" BEFORE UPDATE OR DELETE ON nexa.rev869b_purge_events FOR EACH ROW EXECUTE FUNCTION nexa.rev869b_deny_ledger_mutation();
        CREATE TRIGGER "TR_rev869b_export_rows_immutable" BEFORE UPDATE OR DELETE ON nexa.rev869b_export_batch_rows FOR EACH ROW EXECUTE FUNCTION nexa.rev869b_deny_ledger_mutation();

        CREATE FUNCTION nexa.rev869b_register_command_request(organization text,operation text,idempotency_sha bytea,request_sha bytea,actor_employee uuid,identity_issuer text,identity_subject text,actor_role text)
        RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,nexa AS $f$ DECLARE command_id uuid; existing nexa.rev869b_command_requests%ROWTYPE; BEGIN
          IF session_user<>'nexa_rev869b_command_audit' OR organization='' OR operation='' OR octet_length(idempotency_sha)<>32 OR octet_length(request_sha)<>32 THEN RAISE EXCEPTION USING ERRCODE='42501',MESSAGE='Exact command request required'; END IF;
          SELECT * INTO existing FROM nexa.rev869b_command_requests r WHERE r."OrganizationId"=organization AND r."Operation"=operation AND r."IdempotencyKeySha256"=idempotency_sha FOR UPDATE;
          IF FOUND THEN IF existing."RequestSha256"<>request_sha OR existing."ActorEmployeeId"<>actor_employee OR existing."IdentityIssuer"<>identity_issuer OR existing."IdentitySubject"<>identity_subject OR existing."ActorRole"<>actor_role THEN RAISE EXCEPTION USING ERRCODE='23505',CONSTRAINT='rev869b_command_request_replay_mismatch',MESSAGE='Idempotency replay mismatch'; END IF; RETURN existing."CommandId"; END IF;
          command_id:=gen_random_uuid(); INSERT INTO nexa.rev869b_command_requests VALUES(command_id,organization,operation,idempotency_sha,request_sha,actor_employee,identity_issuer,identity_subject,actor_role,clock_timestamp(),session_user); RETURN command_id;
        END $f$;
        CREATE FUNCTION nexa.rev869b_start_command_attempt(command_id uuid,execution_instance uuid,service_sha bytea,ownership_sha bytea,runtime_principal name,backend_pid integer,transaction_id bigint)
        RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,nexa AS $f$ DECLARE attempt_id uuid:=gen_random_uuid(); ordinal integer; active nexa.rev869b_command_attempts%ROWTYPE; BEGIN
          IF session_user<>'nexa_rev869b_command_audit' OR octet_length(service_sha)<>32 OR octet_length(ownership_sha)<>32 OR runtime_principal<>'nexa_rev869b_app_runtime' THEN RAISE EXCEPTION USING ERRCODE='42501',MESSAGE='Exact command attempt required'; END IF;
          PERFORM 1 FROM nexa.rev869b_command_requests WHERE "CommandId"=command_id FOR UPDATE; IF EXISTS(SELECT 1 FROM nexa.rev869b_command_receipts WHERE "CommandId"=command_id) THEN RETURN NULL; END IF;
          SELECT * INTO active FROM nexa.rev869b_command_attempts WHERE "CommandId"=command_id AND "IsActive"; IF FOUND THEN IF active."ExecutionInstanceId"=execution_instance AND active."ServiceInstanceSha256"=service_sha AND active."OwnershipLeaseSha256"=ownership_sha AND active."RuntimePrincipal"=runtime_principal AND active."TargetBackendPid"=backend_pid AND active."TargetTransactionId"=transaction_id THEN RETURN active."AttemptId"; END IF; RAISE EXCEPTION USING ERRCODE='40001',CONSTRAINT='rev869b_command_attempt_active',MESSAGE='Another bound command attempt is active'; END IF;
          SELECT coalesce(max("AttemptOrdinal"),0)+1 INTO ordinal FROM nexa.rev869b_command_attempts WHERE "CommandId"=command_id; INSERT INTO nexa.rev869b_command_attempts VALUES(attempt_id,command_id,ordinal,execution_instance,service_sha,ownership_sha,runtime_principal,backend_pid,transaction_id,true,clock_timestamp(),session_user); RETURN attempt_id;
        END $f$;
        CREATE FUNCTION nexa.rev869b_open_command_attempt(attempt_id uuid,actor_employee uuid,identity_issuer text,identity_subject text,actor_role text,organization text,slot_sha bytea,slots jsonb)
        RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,nexa AS $f$ DECLARE token uuid:=gen_random_uuid(); BEGIN
          IF session_user<>'nexa_rev869b_app_runtime' OR jsonb_typeof(slots)<>'array' OR jsonb_array_length(slots)=0 OR octet_length(slot_sha)<>32 THEN RAISE EXCEPTION USING ERRCODE='42501',MESSAGE='Exact runtime context required'; END IF;
          IF NOT EXISTS(SELECT 1 FROM nexa.rev869b_command_attempts a JOIN nexa.rev869b_command_requests r ON r."CommandId"=a."CommandId" WHERE a."AttemptId"=attempt_id AND a."IsActive" AND a."RuntimePrincipal"=session_user AND a."TargetBackendPid"=pg_backend_pid() AND a."TargetTransactionId"=txid_current() AND r."ActorEmployeeId"=actor_employee AND r."IdentityIssuer"=identity_issuer AND r."IdentitySubject"=identity_subject AND r."ActorRole"=actor_role AND r."OrganizationId"=organization) THEN RAISE EXCEPTION USING ERRCODE='42501',CONSTRAINT='rev869b_attempt_binding',MESSAGE='Attempt binding mismatch'; END IF;
          SELECT "ContextToken" INTO token FROM nexa.rev869b_command_contexts WHERE "AttemptId"=attempt_id AND "BackendPid"=pg_backend_pid() AND "TransactionId"=txid_current();
          IF FOUND THEN
            UPDATE nexa.rev869b_command_contexts SET "SlotSha256"=digest("SlotSha256"||slot_sha,'sha256'),"Slots"="Slots"||slots,"SlotCount"="SlotCount"+jsonb_array_length(slots) WHERE "ContextToken"=token;
          ELSE
            token:=gen_random_uuid(); INSERT INTO nexa.rev869b_command_contexts VALUES(token,attempt_id,pg_backend_pid(),txid_current(),session_user,slot_sha,slots,jsonb_array_length(slots),transaction_timestamp());
          END IF;
          PERFORM set_config('nexa.rev869b_command_token',token::text,true); PERFORM set_config('nexa.rev869b_actor_employee_id',actor_employee::text,true); PERFORM set_config('nexa.rev869b_identity_issuer',identity_issuer,true); PERFORM set_config('nexa.rev869b_identity_subject',identity_subject,true); PERFORM set_config('nexa.rev869b_actor_login',identity_subject,true); PERFORM set_config('nexa.rev869b_actor_role',actor_role,true); PERFORM set_config('nexa.rev869b_organization',organization,true); RETURN token;
        END $f$;
        CREATE FUNCTION nexa.rev869b_command_context_valid(organization text,actor_employee uuid,identity_issuer text,identity_subject text,actor_role text)
        RETURNS boolean LANGUAGE sql SECURITY DEFINER STABLE SET search_path=pg_catalog,nexa AS $f$ SELECT count(*)=1 FROM nexa.rev869b_command_contexts c JOIN nexa.rev869b_command_attempts a ON a."AttemptId"=c."AttemptId" JOIN nexa.rev869b_command_requests r ON r."CommandId"=a."CommandId" WHERE c."ContextToken"=nullif(current_setting('nexa.rev869b_command_token',true),'')::uuid AND c."BackendPid"=pg_backend_pid() AND c."TransactionId"=txid_current() AND c."RuntimePrincipal"=session_user AND a."IsActive" AND r."OrganizationId"=$1 AND r."ActorEmployeeId"=$2 AND r."IdentityIssuer"=$3 AND r."IdentitySubject"=$4 AND r."ActorRole"=$5 $f$;
        CREATE FUNCTION nexa.rev869b_claim_command_context(claim_kind text,history_id uuid,entity_type text,entity_id uuid,operation text,parent_version bigint,from_status text,to_status text,correlation text,remarks text)
        RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,nexa AS $f$ DECLARE token uuid:=nullif(current_setting('nexa.rev869b_command_token',true),'')::uuid; expected jsonb; BEGIN
          SELECT value INTO expected FROM nexa.rev869b_command_contexts c,jsonb_array_elements(c."Slots") value WHERE c."ContextToken"=token AND value->>'claimKind'=claim_kind AND (value->>'historyId')::uuid=history_id AND value->>'entityType'=entity_type AND (value->>'entityId')::uuid=entity_id AND value->>'operation'=operation AND (value->>'parentVersion')::bigint=parent_version AND value->>'toStatus'=to_status AND value->>'correlation'=correlation;
          IF expected IS NULL OR (expected->>'fromStatus') IS DISTINCT FROM from_status OR expected->>'remarks' IS DISTINCT FROM remarks THEN RAISE EXCEPTION USING ERRCODE='42501',CONSTRAINT='rev869b_exact_command_slot',MESSAGE='Exact command slot mismatch'; END IF;
          INSERT INTO nexa.rev869b_command_claims("ContextToken","ClaimKind","HistoryId","EntityType","EntityId","Operation","ParentVersion","FromStatus","ToStatus","Correlation","RemarksSha256") VALUES(token,claim_kind,history_id,entity_type,entity_id,operation,parent_version,from_status,to_status,correlation,digest(remarks,'sha256'));
        END $f$;
        CREATE FUNCTION nexa.rev869b_commit_command_attempt(attempt_id uuid,business_sha bytea,response_json jsonb,receipt_id uuid)
        RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,nexa AS $f$ DECLARE command_id uuid; expected integer; actual integer; exact_business_sha bytea; BEGIN
          IF session_user<>'nexa_rev869b_app_runtime' OR octet_length(business_sha)<>32 THEN RAISE EXCEPTION USING ERRCODE='42501',MESSAGE='Exact runtime commit required'; END IF;
          SELECT a."CommandId",c."SlotCount",c."SlotSha256" INTO STRICT command_id,expected,exact_business_sha FROM nexa.rev869b_command_attempts a JOIN nexa.rev869b_command_contexts c ON c."AttemptId"=a."AttemptId" WHERE a."AttemptId"=attempt_id AND a."IsActive" AND c."BackendPid"=pg_backend_pid() AND c."TransactionId"=txid_current(); SELECT count(*) INTO actual FROM nexa.rev869b_command_claims q JOIN nexa.rev869b_command_contexts c ON c."ContextToken"=q."ContextToken" WHERE c."AttemptId"=attempt_id;
          IF business_sha<>exact_business_sha THEN RAISE EXCEPTION USING ERRCODE='23514',CONSTRAINT='rev869b_command_business_fingerprint',MESSAGE='Committed business fingerprint mismatch'; END IF;
          IF actual<>expected THEN RAISE EXCEPTION USING ERRCODE='23514',CONSTRAINT='rev869b_command_claim_coverage',MESSAGE='Claim coverage mismatch'; END IF;
          INSERT INTO nexa.rev869b_command_receipts VALUES(receipt_id,attempt_id,command_id,exact_business_sha,response_json,transaction_timestamp()); INSERT INTO nexa.rev869b_command_attempt_outcomes VALUES(gen_random_uuid(),attempt_id,'Committed',NULL,exact_business_sha,transaction_timestamp(),session_user); UPDATE nexa.rev869b_command_attempts SET "IsActive"=false WHERE "AttemptId"=attempt_id; RETURN receipt_id;
        END $f$;
        CREATE FUNCTION nexa.rev869b_record_noncommit_outcome(attempt_id uuid,execution_instance uuid,service_sha bytea,ownership_sha bytea,terminal_state text,category text,outcome_id uuid)
        RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,nexa AS $f$ DECLARE existing nexa.rev869b_command_attempt_outcomes%ROWTYPE; BEGIN
          IF session_user<>'nexa_rev869b_command_audit' OR terminal_state NOT IN ('Rejected','RolledBack','Abandoned') OR length(category) NOT BETWEEN 1 AND 100 OR octet_length(service_sha)<>32 OR octet_length(ownership_sha)<>32 THEN RAISE EXCEPTION USING ERRCODE='42501',MESSAGE='Exact noncommit outcome required'; END IF;
          SELECT * INTO existing FROM nexa.rev869b_command_attempt_outcomes WHERE "AttemptId"=attempt_id;
          IF FOUND THEN IF existing."OutcomeId"<>outcome_id OR existing."TerminalState"<>terminal_state OR existing."Category"<>category OR existing."RecordedBy"<>session_user OR NOT EXISTS(SELECT 1 FROM nexa.rev869b_command_attempts a WHERE a."AttemptId"=attempt_id AND a."ExecutionInstanceId"=execution_instance AND a."ServiceInstanceSha256"=service_sha AND a."OwnershipLeaseSha256"=ownership_sha) THEN RAISE EXCEPTION USING ERRCODE='23505',CONSTRAINT='rev869b_noncommit_replay_mismatch',MESSAGE='Noncommit outcome replay mismatch'; END IF; RETURN existing."OutcomeId"; END IF;
          IF NOT EXISTS(SELECT 1 FROM nexa.rev869b_command_attempts a WHERE a."AttemptId"=attempt_id AND a."IsActive" AND a."ExecutionInstanceId"=execution_instance AND a."ServiceInstanceSha256"=service_sha AND a."OwnershipLeaseSha256"=ownership_sha AND ((terminal_state='Rejected' AND a."OpenedAt" IS NULL AND a."BackendPid" IS NULL AND a."TransactionId" IS NULL) OR (terminal_state='Abandoned' AND a."OpenedAt" IS NULL) OR (terminal_state IN ('RolledBack','Abandoned') AND a."OpenedAt" IS NOT NULL AND NOT EXISTS(SELECT 1 FROM pg_stat_activity s WHERE s.pid=a."BackendPid" AND s.backend_xid IS NOT NULL AND s.backend_xid::text::bigint=(a."TransactionId" % 4294967296))))) OR EXISTS(SELECT 1 FROM nexa.rev869b_command_receipts WHERE "AttemptId"=attempt_id) THEN RAISE EXCEPTION USING ERRCODE='42501',CONSTRAINT='rev869b_noncommit_terminalizer_binding',MESSAGE='Noncommit terminalizer binding or authoritative no-commit proof mismatch'; END IF;
          INSERT INTO nexa.rev869b_command_attempt_outcomes VALUES(outcome_id,attempt_id,terminal_state,category,NULL,clock_timestamp(),session_user); UPDATE nexa.rev869b_command_attempts SET "IsActive"=false WHERE "AttemptId"=attempt_id AND "IsActive" AND "ExecutionInstanceId"=execution_instance AND "ServiceInstanceSha256"=service_sha AND "OwnershipLeaseSha256"=ownership_sha; IF NOT FOUND THEN RAISE EXCEPTION USING ERRCODE='40001',MESSAGE='Attempt terminalization conflict'; END IF; RETURN outcome_id;
        END $f$;
        CREATE FUNCTION nexa.rev869b_reconcile_command_attempt(attempt_id uuid) RETURNS jsonb LANGUAGE sql SECURITY DEFINER STABLE SET search_path=pg_catalog,nexa AS $f$ SELECT jsonb_build_object('attemptId',a."AttemptId",'ordinal',a."AttemptOrdinal",'active',a."IsActive",'terminal',o."TerminalState",'receiptId',r."ReceiptId",'response',r."ResponseJson") FROM nexa.rev869b_command_attempts a LEFT JOIN nexa.rev869b_command_attempt_outcomes o ON o."AttemptId"=a."AttemptId" LEFT JOIN nexa.rev869b_command_receipts r ON r."AttemptId"=a."AttemptId" WHERE a."AttemptId"=$1 AND session_user IN ('nexa_rev869b_command_audit','nexa_rev869b_target_verifier') $f$;
        CREATE FUNCTION nexa.rev869b_read_target_security_state() RETURNS TABLE(request_count bigint,context_count bigint,receipt_count bigint,outcome_count bigint,attempt_count bigint,attempt_sha256 text) LANGUAGE sql SECURITY DEFINER STABLE SET search_path=pg_catalog,nexa AS $f$
          SELECT (SELECT count(*) FROM nexa.rev869b_command_requests),(SELECT count(*) FROM nexa.rev869b_command_contexts),(SELECT count(*) FROM nexa.rev869b_command_receipts),(SELECT count(*) FROM nexa.rev869b_command_attempt_outcomes),(SELECT count(*) FROM nexa.rev869b_command_attempts),(SELECT encode(digest(coalesce(string_agg("AttemptId"::text,',' ORDER BY "AttemptId"),''),'sha256'),'hex') FROM nexa.rev869b_command_attempts) WHERE session_user='nexa_rev869b_target_verifier' $f$;
        CREATE FUNCTION nexa.rev869b_target_catalogue_fingerprint() RETURNS text LANGUAGE sql SECURITY DEFINER STABLE SET search_path=pg_catalog,nexa AS $f$
          WITH facts(fact) AS (
            SELECT 'relation|'||c.oid::regclass::text||'|'||c.relkind||'|'||pg_get_userbyid(c.relowner)||'|'||coalesce(c.relacl::text,'') FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='nexa' AND c.relname LIKE 'rev869b_%'
            UNION ALL SELECT 'column|'||c.oid::regclass::text||'|'||a.attnum||'|'||a.attname||'|'||format_type(a.atttypid,a.atttypmod)||'|'||a.attnotnull||'|'||coalesce(pg_get_expr(d.adbin,d.adrelid),'') FROM pg_attribute a JOIN pg_class c ON c.oid=a.attrelid JOIN pg_namespace n ON n.oid=c.relnamespace LEFT JOIN pg_attrdef d ON d.adrelid=a.attrelid AND d.adnum=a.attnum WHERE n.nspname='nexa' AND c.relname LIKE 'rev869b_%' AND a.attnum>0 AND NOT a.attisdropped
            UNION ALL SELECT 'constraint|'||conrelid::regclass::text||'|'||conname||'|'||pg_get_constraintdef(oid,true) FROM pg_constraint WHERE conrelid IN (SELECT c.oid FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='nexa' AND c.relname LIKE 'rev869b_%')
            UNION ALL SELECT 'index|'||indexrelid::regclass::text||'|'||pg_get_indexdef(indexrelid) FROM pg_index WHERE indrelid IN (SELECT c.oid FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='nexa' AND c.relname LIKE 'rev869b_%')
            UNION ALL SELECT 'trigger|'||tgrelid::regclass::text||'|'||tgname||'|'||pg_get_triggerdef(oid,true) FROM pg_trigger WHERE NOT tgisinternal AND tgrelid IN (SELECT c.oid FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='nexa' AND c.relname LIKE 'rev869b_%')
            UNION ALL SELECT 'function|'||p.oid::regprocedure::text||'|'||pg_get_userbyid(p.proowner)||'|'||pg_get_function_result(p.oid)||'|'||p.prosecdef||'|'||p.provolatile||'|'||coalesce(array_to_string(p.proconfig,','),'')||'|'||encode(digest(p.prosrc,'sha256'),'hex')||'|'||coalesce(p.proacl::text,'') FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='nexa' AND p.proname LIKE 'rev869b_%'
            UNION ALL SELECT 'defaultacl|'||pg_get_userbyid(d.defaclrole)||'|'||d.defaclobjtype||'|'||coalesce(d.defaclacl::text,'') FROM pg_default_acl d WHERE d.defaclnamespace='nexa'::regnamespace AND pg_get_userbyid(d.defaclrole)='nexa_rev869b_security_owner')
          SELECT encode(digest(string_agg(fact,E'\n' ORDER BY fact),'sha256'),'hex') FROM facts $f$;

        CREATE FUNCTION nexa.rev869b_register_purge_authorization(authorization_id uuid,decision_id uuid,prior_attempt uuid,scope text,cutoff timestamptz,maximum_rows integer,nonce_sha bytea,expires_at timestamptz) RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,nexa AS $f$ DECLARE prior_scope text; prior_cutoff timestamptz; prior_maximum integer; BEGIN IF session_user<>'nexa_rev869b_management_writer' OR scope!~'^organization:[A-Za-z0-9._-]{1,100}$' OR octet_length(nonce_sha)<>32 THEN RAISE EXCEPTION USING ERRCODE='42501',MESSAGE='Exact management purge authorization required'; END IF; IF prior_attempt IS NOT NULL THEN SELECT a."Scope",a."Cutoff",a."MaximumRows" INTO prior_scope,prior_cutoff,prior_maximum FROM nexa.rev869b_purge_attempts p JOIN nexa.rev869b_purge_authorizations a ON a."AuthorizationId"=p."AuthorizationId" WHERE p."PurgeAttemptId"=prior_attempt AND p."State" IN ('Failed','Interrupted'); IF prior_scope IS NULL OR prior_scope<>scope OR prior_cutoff<>cutoff OR prior_maximum<>maximum_rows THEN RAISE EXCEPTION USING ERRCODE='42501',CONSTRAINT='rev869b_purge_retry_binding',MESSAGE='Purge retry must bind the exact failed or interrupted attempt policy'; END IF; END IF; INSERT INTO nexa.rev869b_purge_authorizations("AuthorizationId","ManagementDecisionId","PriorAttemptId","Scope","Cutoff","MaximumRows","NonceSha256","ExpiresAt") VALUES(authorization_id,decision_id,prior_attempt,scope,cutoff,maximum_rows,nonce_sha,expires_at); RETURN authorization_id; END $f$;
        CREATE FUNCTION nexa.rev869b_start_purge(authorization_id uuid,purge_attempt_id uuid) RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,nexa AS $f$ DECLARE count_rows integer; candidate_sha bytea; approved_organization text; BEGIN
          IF session_user<>'nexa_rev869b_purge_worker' THEN RAISE EXCEPTION USING ERRCODE='42501',MESSAGE='Purge worker required'; END IF; PERFORM 1 FROM nexa.rev869b_purge_authorizations WHERE "AuthorizationId"=authorization_id AND "State"='Approved' AND "ExpiresAt">clock_timestamp() FOR UPDATE; IF NOT FOUND THEN RAISE EXCEPTION 'Purge authorization unavailable'; END IF;
          SELECT substring("Scope" from 14) INTO STRICT approved_organization FROM nexa.rev869b_purge_authorizations WHERE "AuthorizationId"=authorization_id;
          INSERT INTO nexa.rev869b_purge_attempts VALUES(purge_attempt_id,authorization_id,0,digest('','sha256'),'Started',clock_timestamp(),NULL,NULL);
          INSERT INTO nexa.rev869b_purge_candidates SELECT purge_attempt_id,'command_contexts',c."ContextToken" FROM nexa.rev869b_command_contexts c JOIN nexa.rev869b_command_attempts ca ON ca."AttemptId"=c."AttemptId" JOIN nexa.rev869b_command_requests cr ON cr."CommandId"=ca."CommandId" WHERE cr."OrganizationId"=approved_organization AND c."OpenedAt"<(SELECT "Cutoff" FROM nexa.rev869b_purge_authorizations WHERE "AuthorizationId"=authorization_id) ORDER BY c."ContextToken" LIMIT (SELECT "MaximumRows" FROM nexa.rev869b_purge_authorizations WHERE "AuthorizationId"=authorization_id); GET DIAGNOSTICS count_rows=ROW_COUNT;
          SELECT digest(coalesce(string_agg("LedgerName"||':'||"RowId"::text,',' ORDER BY "LedgerName","RowId"),''),'sha256') INTO candidate_sha FROM nexa.rev869b_purge_candidates WHERE "PurgeAttemptId"=purge_attempt_id;
          UPDATE nexa.rev869b_purge_attempts SET "CandidateCount"=count_rows,"CandidateSha256"=candidate_sha,"State"=CASE WHEN count_rows=0 THEN 'ZeroRows' ELSE 'Started' END,"TerminalAt"=CASE WHEN count_rows=0 THEN clock_timestamp() ELSE NULL END WHERE "PurgeAttemptId"=purge_attempt_id; UPDATE nexa.rev869b_purge_authorizations SET "State"=CASE WHEN count_rows=0 THEN 'ZeroRows' ELSE 'Started' END WHERE "AuthorizationId"=authorization_id; INSERT INTO nexa.rev869b_purge_events VALUES(DEFAULT,purge_attempt_id,CASE WHEN count_rows=0 THEN 'ZeroRows' ELSE 'Started' END,candidate_sha,clock_timestamp(),session_user); RETURN purge_attempt_id;
        END $f$;
        CREATE FUNCTION nexa.rev869b_execute_purge(purge_attempt_id uuid) RETURNS integer LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,nexa AS $f$ DECLARE expected integer; deleted integer; evidence bytea; BEGIN
          IF session_user<>'nexa_rev869b_purge_worker' THEN RAISE EXCEPTION USING ERRCODE='42501',MESSAGE='Purge worker required'; END IF; SELECT "CandidateCount" INTO STRICT expected FROM nexa.rev869b_purge_attempts WHERE "PurgeAttemptId"=purge_attempt_id AND "State"='Started' FOR UPDATE;
          IF EXISTS(SELECT 1 FROM nexa.rev869b_purge_candidates p JOIN nexa.rev869b_command_contexts c ON c."ContextToken"=p."RowId" JOIN nexa.rev869b_command_attempts a ON a."AttemptId"=c."AttemptId" WHERE p."PurgeAttemptId"=purge_attempt_id AND a."IsActive") THEN RAISE EXCEPTION USING ERRCODE='40001',CONSTRAINT='rev869b_purge_candidate_drift',MESSAGE='Frozen candidates drifted'; END IF; DELETE FROM nexa.rev869b_command_claims q USING nexa.rev869b_purge_candidates p WHERE p."PurgeAttemptId"=purge_attempt_id AND p."LedgerName"='command_contexts' AND q."ContextToken"=p."RowId"; DELETE FROM nexa.rev869b_command_contexts c USING nexa.rev869b_purge_candidates p WHERE p."PurgeAttemptId"=purge_attempt_id AND p."LedgerName"='command_contexts' AND c."ContextToken"=p."RowId"; GET DIAGNOSTICS deleted=ROW_COUNT; IF deleted<>expected THEN RAISE EXCEPTION USING ERRCODE='40001',CONSTRAINT='rev869b_purge_candidate_drift',MESSAGE='Frozen candidates drifted'; END IF;
          evidence:=digest(purge_attempt_id::text||':'||deleted::text,'sha256'); UPDATE nexa.rev869b_purge_attempts SET "State"='Succeeded',"TerminalAt"=clock_timestamp() WHERE "PurgeAttemptId"=purge_attempt_id; UPDATE nexa.rev869b_purge_authorizations SET "State"='Succeeded' WHERE "AuthorizationId"=(SELECT "AuthorizationId" FROM nexa.rev869b_purge_attempts WHERE "PurgeAttemptId"=purge_attempt_id); INSERT INTO nexa.rev869b_purge_events VALUES(DEFAULT,purge_attempt_id,'Succeeded',evidence,clock_timestamp(),session_user); RETURN deleted;
        END $f$;
        CREATE FUNCTION nexa.rev869b_record_purge_failure(purge_attempt_id uuid,terminal_state text,category text,evidence bytea) RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,nexa AS $f$ DECLARE existing nexa.rev869b_purge_events%ROWTYPE; existing_category text; BEGIN IF session_user<>'nexa_rev869b_purge_audit' OR terminal_state NOT IN ('Failed','Interrupted') OR length(category) NOT BETWEEN 1 AND 100 OR octet_length(evidence)<>32 THEN RAISE EXCEPTION USING ERRCODE='42501',MESSAGE='Exact independent purge failure required'; END IF; SELECT * INTO existing FROM nexa.rev869b_purge_events e WHERE e."PurgeAttemptId"=purge_attempt_id AND e."State"=terminal_state; IF FOUND THEN SELECT p."FailureCategory" INTO STRICT existing_category FROM nexa.rev869b_purge_attempts p WHERE p."PurgeAttemptId"=purge_attempt_id; IF existing."EvidenceSha256"<>evidence OR existing."Principal"<>session_user OR existing_category<>category THEN RAISE EXCEPTION USING ERRCODE='23505',CONSTRAINT='rev869b_purge_failure_replay_mismatch',MESSAGE='Purge failure replay mismatch'; END IF; RETURN purge_attempt_id; END IF; UPDATE nexa.rev869b_purge_attempts SET "State"=terminal_state,"TerminalAt"=clock_timestamp(),"FailureCategory"=category WHERE "PurgeAttemptId"=purge_attempt_id AND "State"='Started'; IF NOT FOUND THEN RAISE EXCEPTION 'Purge attempt not Started'; END IF; UPDATE nexa.rev869b_purge_authorizations SET "State"=terminal_state WHERE "AuthorizationId"=(SELECT "AuthorizationId" FROM nexa.rev869b_purge_attempts WHERE "PurgeAttemptId"=purge_attempt_id); INSERT INTO nexa.rev869b_purge_events VALUES(DEFAULT,purge_attempt_id,terminal_state,evidence,clock_timestamp(),session_user); RETURN purge_attempt_id; END $f$;
        CREATE FUNCTION nexa.rev869b_reconcile_purge(purge_attempt_id uuid) RETURNS jsonb LANGUAGE sql SECURITY DEFINER STABLE SET search_path=pg_catalog,nexa AS $f$ SELECT to_jsonb(p) FROM nexa.rev869b_purge_attempts p WHERE p."PurgeAttemptId"=$1 AND session_user IN ('nexa_rev869b_purge_worker','nexa_rev869b_purge_audit','nexa_rev869b_target_verifier') $f$;

        CREATE FUNCTION nexa.rev869b_register_export_authorization(authorization_id uuid,decision_id uuid,organization text,fields text[],maximum_rows integer,as_of timestamptz,expires_at timestamptz) RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,nexa AS $f$ DECLARE allowed text[]:=ARRAY['occurredAt','eventType','organizationId','attemptId']; BEGIN IF session_user<>'nexa_rev869b_management_writer' OR organization='' OR fields<@allowed IS NOT TRUE OR array_length(fields,1) IS NULL OR cardinality(fields)<>(SELECT count(DISTINCT value) FROM unnest(fields) value) OR as_of>clock_timestamp() THEN RAISE EXCEPTION USING ERRCODE='42501',MESSAGE='Management-approved export allowlist required'; END IF; INSERT INTO nexa.rev869b_export_authorizations("AuthorizationId","ManagementDecisionId","OrganizationId","Fields","MaximumRows","AsOf","ExpiresAt") VALUES(authorization_id,decision_id,organization,fields,maximum_rows,as_of,expires_at); RETURN authorization_id; END $f$;
        CREATE FUNCTION nexa.rev869b_prepare_export_batch(batch_id uuid,authorization_id uuid) RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,nexa AS $f$ DECLARE a nexa.rev869b_export_authorizations%ROWTYPE; rows_count integer; batch_sha bytea; BEGIN
          IF session_user<>'nexa_rev869b_export_service' THEN RAISE EXCEPTION USING ERRCODE='42501',MESSAGE='Controlled export service required'; END IF; SELECT * INTO STRICT a FROM nexa.rev869b_export_authorizations WHERE "AuthorizationId"=authorization_id AND "State"='Approved' AND "ExpiresAt">clock_timestamp() FOR UPDATE;
          INSERT INTO nexa.rev869b_export_batches VALUES(batch_id,authorization_id,a."ManagementDecisionId",a."OrganizationId",a."Fields",a."MaximumRows",a."AsOf",a."ExpiresAt",0,digest('','sha256'),clock_timestamp()); INSERT INTO nexa.rev869b_export_batch_rows SELECT batch_id,row_number() OVER(ORDER BY o."OccurredAt",o."OutcomeId")::integer,minimized.payload,digest(minimized.payload::text,'sha256') FROM nexa.rev869b_command_attempt_outcomes o JOIN nexa.rev869b_command_attempts a2 ON a2."AttemptId"=o."AttemptId" JOIN nexa.rev869b_command_requests r ON r."CommandId"=a2."CommandId" CROSS JOIN LATERAL (SELECT coalesce(jsonb_object_agg(field.key,field.value),'{}'::jsonb) payload FROM jsonb_each(jsonb_strip_nulls(jsonb_build_object('occurredAt',o."OccurredAt",'eventType',o."TerminalState",'organizationId',r."OrganizationId",'attemptId',o."AttemptId"))) field WHERE field.key=ANY(a."Fields")) minimized WHERE r."OrganizationId"=a."OrganizationId" AND o."OccurredAt"<=a."AsOf" ORDER BY o."OccurredAt",o."OutcomeId" LIMIT a."MaximumRows";
          GET DIAGNOSTICS rows_count=ROW_COUNT; SELECT digest(coalesce(string_agg(encode("RowSha256",'hex'),',' ORDER BY "Ordinal"),''),'sha256') INTO batch_sha FROM nexa.rev869b_export_batch_rows WHERE "BatchId"=batch_id; UPDATE nexa.rev869b_export_batches SET "RowCount"=rows_count,"BatchSha256"=batch_sha WHERE "BatchId"=batch_id; UPDATE nexa.rev869b_export_authorizations SET "State"='Prepared' WHERE "AuthorizationId"=authorization_id; RETURN batch_id;
        END $f$;
        CREATE FUNCTION nexa.rev869b_authorize_export_release(batch_id uuid,release_id uuid) RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,nexa AS $f$ BEGIN IF session_user<>'nexa_rev869b_export_service' OR NOT EXISTS(SELECT 1 FROM nexa.rev869b_export_batches WHERE "BatchId"=batch_id AND "ExpiresAt">clock_timestamp()) OR EXISTS(SELECT 1 FROM nexa.rev869b_export_releases WHERE "BatchId"=batch_id AND "State" NOT IN ('Failed','Interrupted')) THEN RAISE EXCEPTION USING ERRCODE='42501',CONSTRAINT='rev869b_export_release_sequence',MESSAGE='Prepared unexpired retry-eligible batch required'; END IF; INSERT INTO nexa.rev869b_export_releases VALUES(release_id,batch_id,'ReleaseStarted',clock_timestamp(),NULL,NULL); RETURN release_id; END $f$;
        CREATE FUNCTION nexa.rev869b_read_prepared_export_batch(batch_id uuid,release_id uuid) RETURNS TABLE(ordinal integer,payload jsonb,row_sha256 bytea) LANGUAGE sql SECURITY DEFINER STABLE SET search_path=pg_catalog,nexa AS $f$ SELECT r."Ordinal",r."Payload",r."RowSha256" FROM nexa.rev869b_export_batch_rows r JOIN nexa.rev869b_export_releases x ON x."BatchId"=r."BatchId" JOIN nexa.rev869b_export_batches b ON b."BatchId"=r."BatchId" WHERE r."BatchId"=$1 AND x."ReleaseId"=$2 AND x."State"='ReleaseStarted' AND b."ExpiresAt">clock_timestamp() AND session_user='nexa_rev869b_export_service' ORDER BY r."Ordinal" $f$;
        CREATE FUNCTION nexa.rev869b_record_export_release_outcome(release_id uuid,terminal_state text,category text) RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,nexa AS $f$ BEGIN IF session_user<>'nexa_rev869b_export_service' OR terminal_state NOT IN ('Delivered','Failed','Interrupted') OR (terminal_state='Delivered' AND category IS NOT NULL) OR (terminal_state<>'Delivered' AND length(category) NOT BETWEEN 1 AND 100) THEN RAISE EXCEPTION USING ERRCODE='42501',MESSAGE='Exact release outcome required'; END IF; UPDATE nexa.rev869b_export_releases SET "State"=terminal_state,"TerminalAt"=clock_timestamp(),"OutcomeCategory"=category WHERE "ReleaseId"=release_id AND "State"='ReleaseStarted'; IF NOT FOUND THEN RAISE EXCEPTION 'Release missing or terminal'; END IF; RETURN release_id; END $f$;

        CREATE FUNCTION nexa.rev869b_verify_target_catalogue_acl() RETURNS text LANGUAGE plpgsql SECURITY DEFINER STABLE SET search_path=pg_catalog,nexa AS $f$ DECLARE mismatch boolean; BEGIN
          IF session_user<>'nexa_rev869b_target_verifier' THEN RAISE EXCEPTION USING ERRCODE='42501',MESSAGE='Target verifier required'; END IF;
          IF (SELECT "CatalogueSha256"<>nexa.rev869b_target_catalogue_fingerprint() FROM nexa.rev869b_target_catalogue_manifest) IS DISTINCT FROM false THEN RAISE EXCEPTION 'Target catalogue fingerprint mismatch'; END IF;
          WITH expected(role_name,signature) AS (VALUES
            ('nexa_rev869b_app_runtime','nexa.rev869b_open_command_attempt(uuid,uuid,text,text,text,text,bytea,jsonb)'),('nexa_rev869b_app_runtime','nexa.rev869b_command_context_valid(text,uuid,text,text,text)'),('nexa_rev869b_app_runtime','nexa.rev869b_claim_command_context(text,uuid,text,uuid,text,bigint,text,text,text,text)'),('nexa_rev869b_app_runtime','nexa.rev869b_commit_command_attempt(uuid,bytea,jsonb,uuid)'),
            ('nexa_rev869b_command_audit','nexa.rev869b_register_command_request(text,text,bytea,bytea,uuid,text,text,text)'),('nexa_rev869b_command_audit','nexa.rev869b_start_command_attempt(uuid,uuid,bytea,bytea,name,integer,bigint)'),('nexa_rev869b_command_audit','nexa.rev869b_record_noncommit_outcome(uuid,uuid,bytea,bytea,text,text,uuid)'),('nexa_rev869b_command_audit','nexa.rev869b_reconcile_command_attempt(uuid)'),
            ('nexa_rev869b_management_writer','nexa.rev869b_register_purge_authorization(uuid,uuid,uuid,text,timestamp with time zone,integer,bytea,timestamp with time zone)'),('nexa_rev869b_management_writer','nexa.rev869b_register_export_authorization(uuid,uuid,text,text[],integer,timestamp with time zone,timestamp with time zone)'),
            ('nexa_rev869b_purge_worker','nexa.rev869b_start_purge(uuid,uuid)'),('nexa_rev869b_purge_worker','nexa.rev869b_execute_purge(uuid)'),('nexa_rev869b_purge_worker','nexa.rev869b_reconcile_purge(uuid)'),
            ('nexa_rev869b_purge_audit','nexa.rev869b_record_purge_failure(uuid,text,text,bytea)'),('nexa_rev869b_purge_audit','nexa.rev869b_reconcile_purge(uuid)'),
            ('nexa_rev869b_export_service','nexa.rev869b_prepare_export_batch(uuid,uuid)'),('nexa_rev869b_export_service','nexa.rev869b_authorize_export_release(uuid,uuid)'),('nexa_rev869b_export_service','nexa.rev869b_read_prepared_export_batch(uuid,uuid)'),('nexa_rev869b_export_service','nexa.rev869b_record_export_release_outcome(uuid,text,text)'),
            ('nexa_rev869b_target_verifier','nexa.rev869b_reconcile_command_attempt(uuid)'),('nexa_rev869b_target_verifier','nexa.rev869b_reconcile_purge(uuid)'),('nexa_rev869b_target_verifier','nexa.rev869b_read_target_security_state()'),('nexa_rev869b_target_verifier','nexa.rev869b_target_catalogue_fingerprint()'),('nexa_rev869b_target_verifier','nexa.rev869b_verify_target_catalogue_acl()')),
          actual AS (SELECT r.rolname::text role_name,p.oid::regprocedure::text signature FROM pg_roles r CROSS JOIN pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='nexa' AND p.proname LIKE 'rev869b_%' AND NOT r.rolsuper AND r.rolname NOT IN ('nexa_rev869b_security_owner','nexa_rev869b_lifecycle_administrator') AND has_function_privilege(r.oid,p.oid,'EXECUTE')),
          delta AS ((SELECT * FROM expected EXCEPT SELECT * FROM actual) UNION ALL (SELECT * FROM actual EXCEPT SELECT * FROM expected)) SELECT EXISTS(SELECT 1 FROM delta) INTO mismatch;
          IF mismatch THEN RAISE EXCEPTION 'Target function ACL mismatch'; END IF;
          IF EXISTS(SELECT 1 FROM pg_roles r CROSS JOIN pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='nexa' AND c.relname LIKE 'rev869b_%' AND c.relkind='r' AND NOT r.rolsuper AND r.rolname NOT IN ('nexa_rev869b_security_owner','nexa_rev869b_lifecycle_administrator') AND has_table_privilege(r.oid,c.oid,'SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER')) THEN RAISE EXCEPTION 'Target relation ACL mismatch'; END IF;
          IF EXISTS(SELECT 1 FROM pg_roles r CROSS JOIN pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='nexa' AND c.relname LIKE 'rev869b_%' AND c.relkind='S' AND NOT r.rolsuper AND r.rolname NOT IN ('nexa_rev869b_security_owner','nexa_rev869b_lifecycle_administrator') AND has_sequence_privilege(r.oid,c.oid,'SELECT,UPDATE,USAGE')) THEN RAISE EXCEPTION 'Target sequence ACL mismatch'; END IF;
          IF EXISTS(SELECT 1 FROM pg_auth_members m JOIN pg_roles a ON a.oid=m.roleid JOIN pg_roles b ON b.oid=m.member WHERE a.rolname IN ('nexa_rev869b_security_owner','nexa_rev869b_app_runtime','nexa_rev869b_command_audit','nexa_rev869b_management_writer','nexa_rev869b_purge_worker','nexa_rev869b_purge_audit','nexa_rev869b_export_service','nexa_rev869b_target_verifier') OR b.rolname IN ('nexa_rev869b_security_owner','nexa_rev869b_app_runtime','nexa_rev869b_command_audit','nexa_rev869b_management_writer','nexa_rev869b_purge_worker','nexa_rev869b_purge_audit','nexa_rev869b_export_service','nexa_rev869b_target_verifier')) THEN RAISE EXCEPTION 'Target role membership mismatch'; END IF;
          IF EXISTS(SELECT 1 FROM pg_roles r WHERE NOT r.rolsuper AND r.rolname NOT IN ('nexa_rev869b_security_owner','nexa_rev869b_lifecycle_administrator','nexa_rev869b_app_runtime','nexa_rev869b_command_audit','nexa_rev869b_management_writer','nexa_rev869b_purge_worker','nexa_rev869b_purge_audit','nexa_rev869b_export_service','nexa_rev869b_target_verifier') AND has_database_privilege(r.oid,current_database(),'CONNECT,TEMPORARY')) OR EXISTS(SELECT 1 FROM pg_roles r WHERE r.rolname IN ('nexa_rev869b_app_runtime','nexa_rev869b_command_audit','nexa_rev869b_management_writer','nexa_rev869b_purge_worker','nexa_rev869b_purge_audit','nexa_rev869b_export_service','nexa_rev869b_target_verifier') AND (NOT has_database_privilege(r.oid,current_database(),'CONNECT') OR has_database_privilege(r.oid,current_database(),'TEMPORARY'))) THEN RAISE EXCEPTION 'Target database ACL mismatch'; END IF;
          IF EXISTS(SELECT 1 FROM pg_roles r WHERE NOT r.rolsuper AND r.rolname NOT IN ('nexa_rev869b_security_owner','nexa_rev869b_lifecycle_administrator') AND (has_schema_privilege(r.oid,'nexa','CREATE') OR has_schema_privilege(r.oid,'nexa','USAGE') IS DISTINCT FROM (r.rolname IN ('nexa_rev869b_app_runtime','nexa_rev869b_command_audit','nexa_rev869b_management_writer','nexa_rev869b_purge_worker','nexa_rev869b_purge_audit','nexa_rev869b_export_service','nexa_rev869b_target_verifier')))) THEN RAISE EXCEPTION 'Target schema ACL mismatch'; END IF;
          RETURN 'REV869B_TARGET_CATALOGUE_ACL_EXACT'; END $f$;

        DO $ownership$ DECLARE o regclass; f regprocedure; BEGIN
          FOR o IN SELECT c.oid::regclass FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='nexa' AND c.relname LIKE 'rev869b_%' AND c.relkind IN ('r','S') LOOP EXECUTE format('ALTER TABLE %s OWNER TO nexa_rev869b_security_owner',o); END LOOP;
          FOR f IN SELECT p.oid::regprocedure FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='nexa' AND p.proname LIKE 'rev869b_%' LOOP EXECUTE format('ALTER FUNCTION %s OWNER TO nexa_rev869b_security_owner',f); END LOOP;
        END $ownership$;
        REVOKE ALL ON ALL TABLES IN SCHEMA nexa FROM PUBLIC,nexa_rev869b_app_runtime,nexa_rev869b_command_audit,nexa_rev869b_management_writer,nexa_rev869b_purge_worker,nexa_rev869b_purge_audit,nexa_rev869b_export_service,nexa_rev869b_target_verifier;
        REVOKE EXECUTE ON ALL FUNCTIONS IN SCHEMA nexa FROM PUBLIC,nexa_rev869b_app_runtime,nexa_rev869b_command_audit,nexa_rev869b_management_writer,nexa_rev869b_purge_worker,nexa_rev869b_purge_audit,nexa_rev869b_export_service,nexa_rev869b_target_verifier;
        GRANT USAGE ON SCHEMA nexa TO nexa_rev869b_app_runtime,nexa_rev869b_command_audit,nexa_rev869b_management_writer,nexa_rev869b_purge_worker,nexa_rev869b_purge_audit,nexa_rev869b_export_service,nexa_rev869b_target_verifier;
        GRANT SELECT ON nexa.employees,nexa.employee_identity_mappings,nexa.employee_role_assignments,nexa.employee_operational_scopes,nexa.roles,nexa.role_page_permissions,nexa.page_definitions,nexa.items,nexa.uoms,nexa.uom_conversions,nexa.vendors,nexa.tax_gst_settings,nexa.organization_policies,nexa.warehouses,nexa.purchase_requisitions,nexa.purchase_requisition_lines,nexa.purchase_requirement_handoffs,nexa.purchase_approval_route_settings,nexa.purchase_approval_workflow_steps,nexa.purchase_transaction_approval_policies TO nexa_rev869b_app_runtime;
        GRANT SELECT,INSERT,UPDATE ON nexa.vendor_qualifications,nexa.controlled_configuration_histories,nexa.request_for_quotations,nexa.request_for_quotation_lines,nexa.rfq_vendor_invitations,nexa.vendor_quotations,nexa.vendor_quotation_lines,nexa.quotation_technical_verifications,nexa.commercial_comparisons,nexa.commercial_comparison_lines,nexa.purchase_transaction_status_history,nexa.purchase_transaction_approval_history,nexa.purchase_orders,nexa.purchase_order_lines,nexa.purchase_order_history,nexa.material_followup_handoffs,nexa.purchase_number_sequences TO nexa_rev869b_app_runtime;
        GRANT SELECT,INSERT ON nexa.audit_logs TO nexa_rev869b_app_runtime;
        GRANT EXECUTE ON FUNCTION nexa.rev869b_open_command_attempt(uuid,uuid,text,text,text,text,bytea,jsonb),nexa.rev869b_command_context_valid(text,uuid,text,text,text),nexa.rev869b_claim_command_context(text,uuid,text,uuid,text,bigint,text,text,text,text),nexa.rev869b_commit_command_attempt(uuid,bytea,jsonb,uuid) TO nexa_rev869b_app_runtime;
        GRANT EXECUTE ON FUNCTION nexa.rev869b_register_command_request(text,text,bytea,bytea,uuid,text,text,text),nexa.rev869b_start_command_attempt(uuid,uuid,bytea,bytea,name,integer,bigint),nexa.rev869b_record_noncommit_outcome(uuid,uuid,bytea,bytea,text,text,uuid),nexa.rev869b_reconcile_command_attempt(uuid) TO nexa_rev869b_command_audit;
        GRANT EXECUTE ON FUNCTION nexa.rev869b_register_purge_authorization(uuid,uuid,uuid,text,timestamptz,integer,bytea,timestamptz),nexa.rev869b_register_export_authorization(uuid,uuid,text,text[],integer,timestamptz,timestamptz) TO nexa_rev869b_management_writer;
        GRANT EXECUTE ON FUNCTION nexa.rev869b_start_purge(uuid,uuid),nexa.rev869b_execute_purge(uuid),nexa.rev869b_reconcile_purge(uuid) TO nexa_rev869b_purge_worker;
        GRANT EXECUTE ON FUNCTION nexa.rev869b_record_purge_failure(uuid,text,text,bytea),nexa.rev869b_reconcile_purge(uuid) TO nexa_rev869b_purge_audit;
        GRANT EXECUTE ON FUNCTION nexa.rev869b_prepare_export_batch(uuid,uuid),nexa.rev869b_authorize_export_release(uuid,uuid),nexa.rev869b_read_prepared_export_batch(uuid,uuid),nexa.rev869b_record_export_release_outcome(uuid,text,text) TO nexa_rev869b_export_service;
        GRANT EXECUTE ON FUNCTION nexa.rev869b_reconcile_command_attempt(uuid),nexa.rev869b_reconcile_purge(uuid),nexa.rev869b_read_target_security_state() TO nexa_rev869b_target_verifier;
        GRANT EXECUTE ON FUNCTION nexa.rev869b_target_catalogue_fingerprint(),nexa.rev869b_verify_target_catalogue_acl() TO nexa_rev869b_target_verifier;
        ALTER DEFAULT PRIVILEGES FOR ROLE nexa_rev869b_security_owner IN SCHEMA nexa REVOKE ALL ON TABLES FROM PUBLIC;
        ALTER DEFAULT PRIVILEGES FOR ROLE nexa_rev869b_security_owner IN SCHEMA nexa REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC;
        UPDATE nexa.rev869b_target_catalogue_manifest SET "CatalogueSha256"=nexa.rev869b_target_catalogue_fingerprint();
        """;

    internal const string Remove = """
        DROP FUNCTION IF EXISTS nexa.rev869b_record_export_release_outcome(uuid,text,text);
        DROP FUNCTION IF EXISTS nexa.rev869b_verify_target_catalogue_acl();
        DROP FUNCTION IF EXISTS nexa.rev869b_target_catalogue_fingerprint();
        DROP FUNCTION IF EXISTS nexa.rev869b_read_prepared_export_batch(uuid,uuid);
        DROP FUNCTION IF EXISTS nexa.rev869b_authorize_export_release(uuid,uuid);
        DROP FUNCTION IF EXISTS nexa.rev869b_prepare_export_batch(uuid,uuid);
        DROP FUNCTION IF EXISTS nexa.rev869b_register_export_authorization(uuid,uuid,text,text[],integer,timestamptz,timestamptz);
        DROP FUNCTION IF EXISTS nexa.rev869b_reconcile_purge(uuid);
        DROP FUNCTION IF EXISTS nexa.rev869b_record_purge_failure(uuid,text,text,bytea);
        DROP FUNCTION IF EXISTS nexa.rev869b_execute_purge(uuid);
        DROP FUNCTION IF EXISTS nexa.rev869b_start_purge(uuid,uuid);
        DROP FUNCTION IF EXISTS nexa.rev869b_register_purge_authorization(uuid,uuid,uuid,text,timestamptz,integer,bytea,timestamptz);
        DROP FUNCTION IF EXISTS nexa.rev869b_read_target_security_state();
        DROP FUNCTION IF EXISTS nexa.rev869b_reconcile_command_attempt(uuid);
        DROP FUNCTION IF EXISTS nexa.rev869b_record_noncommit_outcome(uuid,uuid,bytea,bytea,text,text,uuid);
        DROP FUNCTION IF EXISTS nexa.rev869b_commit_command_attempt(uuid,bytea,jsonb,uuid);
        DROP FUNCTION IF EXISTS nexa.rev869b_claim_command_context(text,uuid,text,uuid,text,bigint,text,text,text,text);
        DROP FUNCTION IF EXISTS nexa.rev869b_command_context_valid(text,uuid,text,text,text);
        DROP FUNCTION IF EXISTS nexa.rev869b_open_command_attempt(uuid,uuid,text,text,text,text,bytea,jsonb);
        DROP FUNCTION IF EXISTS nexa.rev869b_start_command_attempt(uuid,uuid,bytea,bytea,name,integer,bigint);
        DROP FUNCTION IF EXISTS nexa.rev869b_register_command_request(text,text,bytea,bytea,uuid,text,text,text);
        DROP TABLE IF EXISTS nexa.rev869b_target_catalogue_manifest;
        DROP TABLE IF EXISTS nexa.rev869b_export_releases,nexa.rev869b_export_batch_rows,nexa.rev869b_export_batches,nexa.rev869b_export_authorizations;
        DROP TABLE IF EXISTS nexa.rev869b_purge_events,nexa.rev869b_purge_candidates,nexa.rev869b_purge_attempts,nexa.rev869b_purge_authorizations;
        DROP TABLE IF EXISTS nexa.rev869b_command_receipts,nexa.rev869b_command_attempt_outcomes,nexa.rev869b_command_claims,nexa.rev869b_command_contexts,nexa.rev869b_command_attempts,nexa.rev869b_command_requests;
        DROP FUNCTION IF EXISTS nexa.rev869b_deny_ledger_mutation();
        """;
}
