import { useCallback, useEffect, useState } from 'react'
import { ApiError } from '../../api/client'
import { getActualBom } from '../../api/production'
import type { ActualBomView } from '../../types/production'
import { StatusBadge } from '../employees/StatusBadge'
import { ErrorAlert } from '../../components/ErrorAlert'

const money = new Intl.NumberFormat('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 })

/**
 * GET /api/v1/production/component-fitments/job-orders/{id}/actual-bom.
 * Generated from fitments, never authored: every entry carries the GRN and
 * vendor-bill provenance of the exact stock that was fitted, and a reversal
 * appears as its own negative entry rather than editing the fitment.
 */
export function ActualBomPanel({ jobOrderId }: { jobOrderId: string }) {
  const [bom, setBom] = useState<ActualBomView | null>(null)
  const [missing, setMissing] = useState(false)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<unknown>(null)

  const load = useCallback(async () => {
    setLoading(true)
    setError(null)
    setMissing(false)
    try {
      setBom(await getActualBom(jobOrderId))
    } catch (err) {
      setBom(null)
      if (err instanceof ApiError && err.status === 404) setMissing(true)
      else setError(err)
    } finally {
      setLoading(false)
    }
  }, [jobOrderId])

  useEffect(() => {
    void load()
  }, [load])

  if (loading) return <p>Loading…</p>

  if (missing) {
    return <div className="alert">No Actual BOM yet. It is generated by the first confirmed component fitment on this job.</div>
  }

  if (!bom) {
    return <ErrorAlert error={error} onReload={() => void load()} fallback="Actual BOM could not be loaded." />
  }

  return (
    <div>
      <div className="detail-grid" style={{ marginBottom: 16 }}>
        <div><span className="field-label">Generated</span> {new Date(bom.GeneratedAt).toLocaleString()}</div>
        <div><span className="field-label">Material value</span> <span className="mono">{money.format(bom.TotalAcceptedMaterialValue)}</span></div>
        <div><span className="field-label">Allocated charges</span> <span className="mono">{money.format(bom.TotalAllocatedChargeValue)}</span></div>
        <div><span className="field-label">Total accepted value</span> <span className="mono">{money.format(bom.TotalAcceptedValue)}</span></div>
      </div>
      <div className="table-wrap">
        <table className="table">
          <thead>
            <tr>
              <th>When</th>
              <th>Kind</th>
              <th>Item</th>
              <th className="text-right">Qty (base)</th>
              <th>Serial</th>
              <th>GRN</th>
              <th>Vendor bill</th>
              <th className="text-right">Material</th>
              <th className="text-right">Charges</th>
              <th className="text-right">Total</th>
            </tr>
          </thead>
          <tbody>
            {bom.Entries.length === 0 && <tr><td colSpan={10} className="table-empty">No entries.</td></tr>}
            {bom.Entries.map((entry) => (
              <tr key={entry.Id}>
                <td>{new Date(entry.OccurredAt).toLocaleString()}</td>
                <td><StatusBadge value={entry.EntryKind} /></td>
                <td><span className="mono">{entry.ItemCode}</span> — {entry.ItemName}</td>
                <td className="text-right mono">{entry.QuantityBase} {entry.UomCode}</td>
                <td className="mono">{entry.SerialNumber ?? '—'}</td>
                <td className="mono">{entry.GrnNumber}</td>
                <td className="mono">{entry.BillNumber}</td>
                <td className="text-right mono">{money.format(entry.AcceptedMaterialValue)}</td>
                <td className="text-right mono">{money.format(entry.AllocatedChargeValue)}</td>
                <td className="text-right mono">{money.format(entry.TotalAcceptedValue)}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  )
}
