namespace SESS.NexaERP.Application.Rev869A;

public sealed record CreateEmployeeIdentityMappingRequest(string OrganizationId, string Issuer, string Subject, string EmployeeCode, string IdentityType, DateOnly EffectiveFrom, DateOnly? EffectiveTo, string Remarks);
public sealed record CreateOperationalScopeRequest(string OrganizationId, string EmployeeCode, string? DepartmentCode, string? WarehouseCode, Guid? RackBinId, bool OwnRecordsOnly, bool AllowsPrivilegedCrossScope, DateOnly EffectiveFrom, DateOnly? EffectiveTo, string Remarks);
public sealed record CreateUomRequest(string Code, string Name, string MeasurementDimension);
public sealed record CreateUomConversionRequest(string OrganizationId, string FromUomCode, string ToUomCode, string MeasurementDimension, decimal ConversionFactor, DateOnly EffectiveFrom, DateOnly? EffectiveTo, string Remarks);
public sealed record CreateTaxGstSettingRequest(string OrganizationId, string JurisdictionCode, string HsnSacCode, string SupplierStateCode, string PlaceOfSupplyStateCode, string VendorRegistrationType, decimal GstRate, decimal CgstRate, decimal SgstRate, decimal IgstRate, decimal CessRate, bool IsExempt, bool IsReverseCharge, string CurrencyCode, int RoundingScale, DateOnly EffectiveFrom, DateOnly? EffectiveTo, string Remarks, Guid? SupersedesTaxGstSettingId = null);
public sealed record DecideTaxGstSettingRequest(uint ExpectedVersion, string Remarks, string IdempotencyKey);
public sealed record TaxGstWorkflowResult(Guid Id, string ApprovalStatus, uint Version, Guid CreatorEmployeeId, Guid? DecisionEmployeeId, string? DecisionRoleCode);
public interface ITaxGstWorkflowService
{
    Task<TaxGstWorkflowResult> CreateAsync(CreateTaxGstSettingRequest request, string idempotencyKey, CancellationToken cancellationToken);
    Task<TaxGstWorkflowResult> ApproveAsync(Guid id, DecideTaxGstSettingRequest request, CancellationToken cancellationToken);
    Task<TaxGstWorkflowResult> RejectAsync(Guid id, DecideTaxGstSettingRequest request, CancellationToken cancellationToken);
}
public sealed record CreateVendorQualificationRequest(string OrganizationId, string VendorCode, string? ItemCategoryCode, string QualificationCode, DateOnly EffectiveFrom, DateOnly? EffectiveTo, string Remarks);
public sealed record ChangeVendorQualificationLifecycleRequest(uint ExpectedVersion, string Remarks);
public sealed record CreateWarehouseConditionLocationRequest(string OrganizationId, string WarehouseCode, Guid RackBinId, string ConditionCode, DateOnly EffectiveFrom, DateOnly? EffectiveTo, string Remarks);
public sealed record CloseWarehouseConditionLocationRequest(DateOnly EffectiveTo, uint Version, string Remarks);
public sealed record CreateQcInspectionPolicyRequest(string OrganizationId, string? ItemCode, string? ItemCategoryCode, string ParameterCode, string MeasurementUomCode, decimal? LowerLimit, decimal? UpperLimit, string InspectionMethod, int SampleSize, DateOnly EffectiveFrom, DateOnly? EffectiveTo, string Remarks);
public sealed record ResolveCommercialValueRequest(string CurrencyCode, decimal TaxableValue, decimal TaxValue, decimal FreightAndOtherCharges, decimal DiscountValue, int RoundingScale);
public sealed record EmployeeIdentityMappingSummary(Guid Id, string OrganizationId, string Issuer, string SubjectSha256, Guid EmployeeId, string EmployeeCode, string IdentityType, DateOnly EffectiveFrom, DateOnly? EffectiveTo, bool IsActive, string Remarks, uint Version);
public sealed record OperationalScopeSummary(Guid Id, string OrganizationId, Guid EmployeeId, string EmployeeCode, Guid? DepartmentId, string? DepartmentCode, Guid? WarehouseId, string? WarehouseCode, Guid? RackBinId, string? BinCode, bool OwnRecordsOnly, bool AllowsPrivilegedCrossScope, DateOnly EffectiveFrom, DateOnly? EffectiveTo, bool IsActive, string Remarks, uint Version);
public sealed record UomConversionSummary(Guid Id, string OrganizationId, Guid FromUomId, string FromUomCode, Guid ToUomId, string ToUomCode, string MeasurementDimension, decimal ConversionFactor, int QuantityPrecision, DateOnly EffectiveFrom, DateOnly? EffectiveTo, string ApprovalStatus, bool IsActive, DateTimeOffset? FirstUsedAt, string Remarks, uint Version);
public sealed record TaxGstSettingSummary(Guid Id, string OrganizationId, string JurisdictionCode, string HsnSacCode, string SupplyType, string SupplierStateCode, string PlaceOfSupplyStateCode, string VendorRegistrationType, decimal GstRate, decimal CgstRate, decimal SgstRate, decimal IgstRate, decimal CessRate, bool IsExempt, bool IsReverseCharge, string CurrencyCode, int RoundingScale, DateOnly EffectiveFrom, DateOnly? EffectiveTo, string ApprovalStatus, Guid CreatorEmployeeId, Guid? DecisionEmployeeId, string? DecisionRoleCode, DateTimeOffset? DecisionAt, string? DecisionRemarks, Guid? SupersedesTaxGstSettingId, bool IsActive, string Remarks, uint Version);
public sealed record VendorQualificationSummary(Guid Id, string OrganizationId, Guid VendorId, string VendorCode, Guid? ItemCategoryId, string? ItemCategoryCode, string QualificationCode, DateOnly EffectiveFrom, DateOnly? EffectiveTo, string VerificationStatus, Guid? VerifiedByEmployeeId, string ApprovalStatus, Guid? ApprovedByEmployeeId, bool IsActive, string Remarks, uint Version);