using System.Text.Json;
using System.IO.Compression;
using System.Security.Cryptography;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using SESS.NexaERP.Infrastructure.Persistence;

namespace SESS.NexaERP.Tests;

public sealed partial class AdvanceMigrationSqlSyntaxTests
{
#if WORKFLOW_WITNESS
    [Fact]
    public async Task HistoricalAcceptedReturnsGainRestorationsWithoutRewritingHistory()
    {
        const string target = "20260914080000_FifoReturnRestorations";
        using var model = new NexaErpDbContext(new DbContextOptionsBuilder<NexaErpDbContext>()
            .UseNpgsql("Host=127.0.0.1;Port=1;Database=no_connect;Username=no_connect").Options);
        var migrator = model.GetService<IMigrator>();
        var migrations = model.Database.GetMigrations().ToArray();
        var index = Array.IndexOf(migrations, target);
        Assert.True(index > 0);
        var predecessor = migrations[index - 1];
        using var server = DisposablePostgreSql.Start(FindPostgreSqlBin());
        server.Execute("historical-predecessor.sql", migrator.GenerateScript("0", predecessor));
        using var environment = new OrdinaryPrincipalEnvironment(server.ConnectionString, "historical-fifo-runtime-123456789");
        Assert.Equal(0, await DatabasePrincipalCommand.RunAsync(["database-principals", "provision"]));

        // Frozen synthetic data generated by the real HTTP purchase/return witness at 433f968.
        // Loading a retained predecessor image is fixture setup, never a production import path.
        // Its current API replacement cannot author data against this historical schema.
        server.Execute("historical-fixture-reset.sql", """
            DO $fixture$
            DECLARE r record; tables text;
            BEGIN
              IF current_database()<>'advance_parser' OR inet_server_addr()<>'127.0.0.1'::inet
                OR inet_server_port()=5432 THEN RAISE EXCEPTION 'Disposable historical fixture only.'; END IF;
              FOR r IN SELECT tablename FROM pg_tables WHERE schemaname='advance' AND tablename<>'__EFMigrationsHistory' LOOP
                EXECUTE format('ALTER TABLE advance.%I DISABLE TRIGGER ALL',r.tablename);
              END LOOP;
              SELECT string_agg(format('advance.%I',tablename),',') INTO tables
                FROM pg_tables WHERE schemaname='advance' AND tablename<>'__EFMigrationsHistory';
              EXECUTE 'TRUNCATE TABLE '||tables||' CASCADE';
            END $fixture$;
            """);
        using (var file = File.OpenRead(Path.Combine(FindRepositoryRoot(), "tests", "SESS.NexaERP.Tests",
                   "Fixtures", "historical-fifo-predecessor.sql.gz")))
        using (var compressed = new GZipStream(file, CompressionMode.Decompress))
        using (var data = new MemoryStream())
        {
            compressed.CopyTo(data);
            var bytes = data.ToArray();
            Assert.Equal("d2318bba9d54c8feb2ca191a193236a9767c7f0e5349922ca8ce04686b5015f0", Convert.ToHexString(SHA256.HashData(bytes)).ToLowerInvariant());
            server.Execute("historical-fixture-load.sql", System.Text.Encoding.UTF8.GetString(bytes));
        }
        server.Execute("historical-fixture-check.sql", """
            DO $check$ BEGIN
              IF EXISTS(SELECT 1 FROM pg_trigger t JOIN pg_class c ON c.oid=t.tgrelid
                JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='advance' AND t.tgenabled='D')
                OR to_regclass('advance.fifo_cost_restorations') IS NOT NULL
                OR (SELECT count(*) FROM advance.material_returns WHERE "Status"='ACCEPTED')<>3
                OR (SELECT sum("ReturnedQuantityBase") FROM advance.material_return_lines)<>1.63 THEN
                RAISE EXCEPTION 'Historical fixture state or trigger restoration is invalid.';
              END IF;
            END $check$;
            """);
        var options = new DbContextOptionsBuilder<NexaErpDbContext>().UseNpgsql(server.ConnectionString).Options;
        var original = await ReadOriginalFifoHistory(options);
        server.Execute("historical-fifo-up.sql", migrator.GenerateScript(predecessor, target));
        // At the exact migration boundary even the full JSON rows must be unchanged.
        Assert.Equal(original, await ReadOriginalFifoHistory(options));
        await VerifyHistoricalFifoRestoration(options);
        server.AssertRejected("historical-fifo-populated-down.sql", migrator.GenerateScript(target, predecessor),
            "refuses retained costing evidence");
        server.Execute("historical-current-head.sql", migrator.GenerateScript(target, migrations[^1]));
        Assert.Equal(0, await DatabasePrincipalCommand.RunAsync(["database-principals", "provision"]));
        AssertOriginalHistoryUnchanged(original, await ReadOriginalFifoHistory(options));
        await VerifyHistoricalFifoRestoration(options);
        await using var db = new NexaErpDbContext(options);
        Assert.Equal(migrations, (await db.Database.GetAppliedMigrationsAsync()).ToArray());
        var beforeReplay = await ReadOriginalFifoHistory(options);
        var restorations = await db.Database.SqlQueryRaw<string>(
            """SELECT jsonb_agg(to_jsonb(r) ORDER BY r."Id")::text AS "Value" FROM advance.fifo_cost_restorations r""").SingleAsync();
        server.Execute("historical-replay.sql", migrator.GenerateScript("0", migrations[^1], MigrationsSqlGenerationOptions.Idempotent));
        Assert.Equal(beforeReplay, await ReadOriginalFifoHistory(options));
        Assert.Equal(restorations, await db.Database.SqlQueryRaw<string>(
            """SELECT jsonb_agg(to_jsonb(r) ORDER BY r."Id")::text AS "Value" FROM advance.fifo_cost_restorations r""").SingleAsync());
    }
#endif

    private static async Task<string> ReadOriginalFifoHistory(DbContextOptions<NexaErpDbContext> options)
    {
        await using var db=new NexaErpDbContext(options);
        return await db.Database.SqlQueryRaw<string>("""
            SELECT jsonb_build_object(
              'layers',(SELECT jsonb_agg(to_jsonb(f) ORDER BY f."Id") FROM advance.fifo_inventory_cost_layers f),
              'consumptions',(SELECT jsonb_agg(to_jsonb(c) ORDER BY c."Id") FROM advance.fifo_cost_consumptions c),
              'returns',(SELECT jsonb_agg(to_jsonb(r) ORDER BY r."Id") FROM advance.material_returns r),
              'returnLines',(SELECT jsonb_agg(to_jsonb(r) ORDER BY r."Id") FROM advance.material_return_lines r),
              'returnHistory',(SELECT jsonb_agg(to_jsonb(h) ORDER BY h."Id") FROM advance.material_return_history h),
              'movements',(SELECT jsonb_agg(to_jsonb(m) ORDER BY m."Id") FROM advance.stock_movements m),
              'adjustments',(SELECT jsonb_agg(to_jsonb(a) ORDER BY a."Id") FROM advance.fifo_landed_cost_adjustments a)
            )::text AS "Value"
            """).SingleAsync();
    }

    private static void AssertOriginalHistoryUnchanged(string original, string upgraded)
    {
        using var before = JsonDocument.Parse(original);
        using var after = JsonDocument.Parse(upgraded);
        foreach (var table in before.RootElement.EnumerateObject())
        {
            var oldRows = table.Value.EnumerateArray().ToArray();
            var newRows = after.RootElement.GetProperty(table.Name).EnumerateArray().ToArray();
            Assert.Equal(oldRows.Length, newRows.Length);
            for (var i = 0; i < oldRows.Length; i++)
                foreach (var column in oldRows[i].EnumerateObject())
                    Assert.Equal(column.Value.GetRawText(), newRows[i].GetProperty(column.Name).GetRawText());
            // Later migrations may add columns; every original column/row must remain identical.
        }
    }

    private static async Task VerifyHistoricalFifoRestoration(DbContextOptions<NexaErpDbContext> options)
    {
        await using var db=new NexaErpDbContext(options);
        Assert.Equal(1.63m,await db.Database.SqlQueryRaw<decimal>("""
            SELECT sum("Quantity") AS "Value" FROM advance.fifo_cost_restorations
            WHERE "IsHistoricalReconciliation"
            """).SingleAsync());
        Assert.Equal(0,await db.Database.SqlQueryRaw<int>("""
            SELECT count(*)::integer AS "Value" FROM advance.fifo_cost_restorations r
            JOIN advance.material_return_lines rl ON rl."Id"=r."MaterialReturnLineId"
            JOIN advance.material_returns h ON h."Id"=rl."MaterialReturnId"
            WHERE NOT r."IsHistoricalReconciliation" OR r."EffectiveAt"<>h."AcceptedAt"
              OR r."RecordedAt"<r."EffectiveAt"
            """).SingleAsync());
    }
}
