using System.Globalization;
using Microsoft.EntityFrameworkCore;
using SESS.NexaERP.Application.Audit;
using SESS.NexaERP.Application.Common;
using SESS.NexaERP.Application.Inventory;
using SESS.NexaERP.Application.Masters;
using SESS.NexaERP.Domain.Inventory;
using SESS.NexaERP.Domain.Masters;
using SESS.NexaERP.Infrastructure.Persistence;

namespace SESS.NexaERP.Infrastructure.Masters;

public sealed class EfWarehouseMasterDataService(NexaErpDbContext db, ICurrentUser user, IAuditWriter audit) : IWarehouseMasterDataService
{
    public async Task<IReadOnlyList<MasterDataExportRow>> ExportAsync(MasterDataExportQuery query, CancellationToken ct)
    {
        var company = await Company(ct); var rows = db.Warehouses.AsNoTracking().Include(x=>x.ResponsibleEmployee).Include(x=>x.Department).Where(x => x.CompanyId == company.Id);
        if (!string.IsNullOrWhiteSpace(query.Search)) { var term=query.Search.Trim().ToUpperInvariant(); rows=rows.Where(x=>x.WarehouseCode.ToUpper().Contains(term)||x.Name.ToUpper().Contains(term)); }
        if (query.IsActive.HasValue) rows=rows.Where(x=>x.IsActive==query.IsActive.Value);
        rows=string.Equals(query.SortBy,"name",StringComparison.OrdinalIgnoreCase)?rows.OrderBy(x=>x.Name).ThenBy(x=>x.WarehouseCode):rows.OrderBy(x=>x.WarehouseCode);
        if (string.Equals(query.SortDirection,"desc",StringComparison.OrdinalIgnoreCase)) rows=rows.OrderByDescending(x=>x.WarehouseCode);
        var materialized=await rows.ToListAsync(ct);return materialized.Select(ExportRow).ToArray();
    }

    public async Task<MasterDataExistingSet> LoadExistingAsync(IReadOnlyCollection<string> codes,IReadOnlyCollection<Guid> ids,CancellationToken ct)
    {
        var company=await Company(ct);var rows=await db.Warehouses.AsNoTracking().Include(x=>x.ResponsibleEmployee).Include(x=>x.Department).Where(x=>x.CompanyId==company.Id&&(codes.Contains(x.WarehouseCode)||ids.Contains(x.Id))).ToListAsync(ct);var records=rows.Select(Existing).ToArray();return new(records.ToDictionary(x=>x.NormalizedBusinessCode,StringComparer.Ordinal),records.ToDictionary(x=>x.Id));
    }

    public async Task<MasterDataApplyResult> CreateAsync(UpsertWarehouseRequest request,CancellationToken ct)
    {
        var company=await Company(ct);var values=await Validate(request,company.Id,null,ct);var row=new Warehouse{CompanyId=company.Id,WarehouseCode=values.Code,Name=values.Name,WarehouseType=values.Type,Location=values.Location,ResponsibleEmployeeId=values.EmployeeId,DepartmentId=values.DepartmentId,CreatedBy=user.LoginId};db.Warehouses.Add(row);AddHistory(row);await db.SaveChangesAsync(ct);await audit.WriteAsync("Masters","CreateDraft",nameof(Warehouse),row.Id.ToString(),null,ExportRow(row),ct);return new(row.Id,row.Version);
    }

    public async Task<MasterDataApplyResult> UpdateAsync(MasterDataExistingRecord existing,UpsertWarehouseRequest request,CancellationToken ct)
    {
        var company=await Company(ct);var row=await db.Warehouses.SingleOrDefaultAsync(x=>x.Id==existing.Id&&x.CompanyId==company.Id,ct)??throw new MasterDataNotFoundException("Warehouse not found in the selected company.");if(request.Version!=row.Version)throw new MasterDataConflictException("Stale record version. Refresh and retry.");var values=await Validate(request,company.Id,row.Id,ct);if(values.Code!=row.WarehouseCode)throw new MasterDataValidationException("Warehouse Code is immutable through upload. Use a governed rename operation.");var before=ExportRow(row);row.Name=values.Name;row.WarehouseType=values.Type;row.Location=values.Location;row.ResponsibleEmployeeId=values.EmployeeId;row.DepartmentId=values.DepartmentId;row.Version=checked(row.Version+1);row.UpdatedAt=DateTimeOffset.UtcNow;row.UpdatedBy=user.LoginId;await db.SaveChangesAsync(ct);await audit.WriteAsync("Masters","Update",nameof(Warehouse),row.Id.ToString(),before,ExportRow(row),ct);return new(row.Id,row.Version);
    }

    private async Task<(string Code,string Name,string Type,string? Location,Guid? EmployeeId,Guid? DepartmentId)> Validate(UpsertWarehouseRequest r,Guid companyId,Guid? id,CancellationToken ct)
    {
        var code=Code(r.WarehouseCode);var name=r.Name?.Trim()??"";var type=r.WarehouseType?.Trim().ToUpperInvariant()??"";var location=Optional(r.Location);if(code.Length is 0 or >80||name.Length is 0 or >200||type.Length is 0 or >80||location?.Length>1000)throw new MasterDataValidationException("Warehouse Code, Name and Type are required and must fit their documented lengths.");if(await db.Warehouses.AnyAsync(x=>x.CompanyId==companyId&&x.Id!=id&&x.WarehouseCode==code,ct))throw new MasterDataConflictException("Warehouse Code already exists in the selected company.");
        Guid? employeeId=null;if(!string.IsNullOrWhiteSpace(r.ResponsibleEmployeeCode)){var employeeCode=Code(r.ResponsibleEmployeeCode);employeeId=await db.EmployeeCompanyAssignments.Where(x=>x.CompanyId==companyId&&x.EmployeeCode==employeeCode&&x.IsActive&&x.Status=="ACTIVE").Select(x=>(Guid?)x.EmployeeId).SingleOrDefaultAsync(ct);if(!employeeId.HasValue)throw new MasterDataValidationException("Responsible Employee Code must have an active assignment in the selected company.");}
        Guid? departmentId=null;if(!string.IsNullOrWhiteSpace(r.DepartmentCode)){var departmentCode=Code(r.DepartmentCode);departmentId=await db.Departments.Where(x=>x.Code==departmentCode&&x.IsActive).Select(x=>(Guid?)x.Id).SingleOrDefaultAsync(ct);if(!departmentId.HasValue)throw new MasterDataValidationException("Department Code must identify an active department.");}
        if(new[]{r.DefaultReceivingLocationId,r.DefaultAcceptedLocationId,r.DefaultQcHoldLocationId,r.DefaultRejectedLocationId,r.DefaultRepairableLocationId,r.DefaultScrapLocationId}.Any(x=>x.HasValue))throw new MasterDataValidationException("Default condition locations are governed through the warehouse condition-location UI and are not maintained by warehouse upload.");return(code,name,type,location,employeeId,departmentId);
    }

    private async Task<SESS.NexaERP.Domain.Foundation.Company> Company(CancellationToken ct)=>await db.Companies.SingleOrDefaultAsync(x=>x.Code==user.OrganizationId&&x.IsActive&&x.Status=="ACTIVE",ct)??throw new UnauthorizedAccessException("Selected company is unavailable.");
    private void AddHistory(Warehouse x)=>db.MasterStatusHistories.Add(new MasterStatusHistory{MasterType=nameof(Warehouse),MasterId=x.Id,MasterCode=x.WarehouseCode,NewStatus=x.Status,Reason="Warehouse draft created",SourceRevision="WAREHOUSE_MASTER",CorrelationId=$"WAREHOUSE_CREATE_{x.Id:N}",CreatedBy=user.LoginId});
    private static MasterDataExportRow ExportRow(Warehouse x)=>new(new Dictionary<string,object?>(StringComparer.Ordinal){{"RecordId",x.Id.ToString()},{"Version",x.Version},{"WarehouseCode",x.WarehouseCode},{"Name",x.Name},{"WarehouseType",x.WarehouseType},{"Location",x.Location},{"ResponsibleEmployeeCode",x.ResponsibleEmployee?.EmployeeCode},{"DepartmentCode",x.Department?.Code},{"Status",x.Status},{"ApprovalStatus",x.ApprovalStatus},{"IsActive",x.IsActive}});
    private static MasterDataExistingRecord Existing(Warehouse x)=>new(x.Id,x.WarehouseCode,x.WarehouseCode,x.Version,ExportRow(x).Values.ToDictionary(k=>k.Key,v=>Convert.ToString(v.Value,CultureInfo.InvariantCulture),StringComparer.Ordinal));
    internal static string Code(string? value)=>(value??"").Trim().ToUpperInvariant();internal static string? Optional(string? value)=>string.IsNullOrWhiteSpace(value)?null:value.Trim();
}

public sealed class EfRackBinMasterDataService(NexaErpDbContext db,ICurrentUser user,IAuditWriter audit) : IRackBinMasterDataService
{
    public async Task<IReadOnlyList<MasterDataExportRow>> ExportAsync(MasterDataExportQuery query,CancellationToken ct){var company=await Company(ct);var rows=db.RackBins.AsNoTracking().Include(x=>x.Warehouse).Where(x=>x.CompanyId==company.Id);if(!string.IsNullOrWhiteSpace(query.Search)){var term=query.Search.Trim().ToUpperInvariant();rows=rows.Where(x=>x.BinCode.ToUpper().Contains(term)||x.RackName.ToUpper().Contains(term)||x.Warehouse!.WarehouseCode.ToUpper().Contains(term));}if(query.IsActive.HasValue)rows=rows.Where(x=>x.IsActive==query.IsActive.Value);rows=string.Equals(query.SortDirection,"desc",StringComparison.OrdinalIgnoreCase)?rows.OrderByDescending(x=>x.BinCode):rows.OrderBy(x=>x.BinCode);var materialized=await rows.ToListAsync(ct);return materialized.Select(x=>ExportRow(x)).ToArray();}
    public async Task<MasterDataExistingSet> LoadExistingAsync(IReadOnlyCollection<string> codes,IReadOnlyCollection<Guid> ids,CancellationToken ct){var company=await Company(ct);var rows=await db.RackBins.AsNoTracking().Include(x=>x.Warehouse).Where(x=>x.CompanyId==company.Id&&(codes.Contains(x.BinCode)||ids.Contains(x.Id))).ToListAsync(ct);var records=rows.Select(Existing).ToArray();return new(records.ToDictionary(x=>x.NormalizedBusinessCode,StringComparer.Ordinal),records.ToDictionary(x=>x.Id));}
    public async Task<MasterDataApplyResult> CreateAsync(UpsertRackBinRequest request,CancellationToken ct){var company=await Company(ct);var v=await Validate(request,company.Id,null,ct);var row=new RackBin{CompanyId=company.Id,WarehouseId=v.WarehouseId,BinCode=v.Code,RackName=v.RackName,BinNameNumber=v.BinNumber,Zone=v.Zone,LocationType=v.LocationType,MaterialCondition=v.Condition,CapacityQuantity=v.Capacity,CapacityUom=v.CapacityUom,Barcode=v.Barcode,Description=v.Description,CreatedBy=user.LoginId};db.RackBins.Add(row);AddHistory(row);await db.SaveChangesAsync(ct);await audit.WriteAsync("Masters","CreateDraft",nameof(RackBin),row.Id.ToString(),null,ExportRow(row,v.WarehouseCode),ct);return new(row.Id,row.Version);}
    public async Task<MasterDataApplyResult> UpdateAsync(MasterDataExistingRecord existing,UpsertRackBinRequest request,CancellationToken ct){var company=await Company(ct);var row=await db.RackBins.Include(x=>x.Warehouse).SingleOrDefaultAsync(x=>x.Id==existing.Id&&x.CompanyId==company.Id,ct)??throw new MasterDataNotFoundException("Rack/bin not found in the selected company.");if(request.Version!=row.Version)throw new MasterDataConflictException("Stale record version. Refresh and retry.");var v=await Validate(request,company.Id,row.Id,ct);if(v.Code!=row.BinCode)throw new MasterDataValidationException("Bin Code is immutable through upload. Use a governed rename operation.");if(v.WarehouseId!=row.WarehouseId)throw new MasterDataValidationException("Warehouse assignment is immutable. Deactivate this rack/bin and create it in the other warehouse.");if(v.Condition!=row.MaterialCondition&&await db.WarehouseConditionLocations.AnyAsync(x=>x.RackBinId==row.Id,ct))throw new MasterDataConflictException("Material Condition cannot change after a condition-location version references this rack/bin.");var before=ExportRow(row);row.RackName=v.RackName;row.BinNameNumber=v.BinNumber;row.Zone=v.Zone;row.LocationType=v.LocationType;row.MaterialCondition=v.Condition;row.CapacityQuantity=v.Capacity;row.CapacityUom=v.CapacityUom;row.Barcode=v.Barcode;row.Description=v.Description;row.Version=checked(row.Version+1);row.UpdatedAt=DateTimeOffset.UtcNow;row.UpdatedBy=user.LoginId;await db.SaveChangesAsync(ct);await audit.WriteAsync("Masters","Update",nameof(RackBin),row.Id.ToString(),before,ExportRow(row),ct);return new(row.Id,row.Version);}
    private async Task<(Guid WarehouseId,string WarehouseCode,string Code,string RackName,string BinNumber,string? Zone,string LocationType,string Condition,decimal? Capacity,string? CapacityUom,string? Barcode,string? Description)> Validate(UpsertRackBinRequest r,Guid companyId,Guid? id,CancellationToken ct){var wh=EfWarehouseMasterDataService.Code(r.WarehouseCode);var code=EfWarehouseMasterDataService.Code(r.BinCode);var rack=(r.RackName??"").Trim();var number=(r.BinNameNumber??"").Trim();var zone=EfWarehouseMasterDataService.Optional(r.Zone);var type=(r.LocationType??"").Trim().ToUpperInvariant();var condition=EfWarehouseMasterDataService.Code(r.MaterialCondition);var uom=EfWarehouseMasterDataService.Code(r.CapacityUom);var barcode=EfWarehouseMasterDataService.Optional(r.Barcode)?.ToUpperInvariant();var description=EfWarehouseMasterDataService.Optional(r.Description);if(wh.Length is 0 or >80||code.Length is 0 or >80||rack.Length is 0 or >120||number.Length is 0 or >120||zone?.Length>120||type.Length is 0 or >80||description?.Length>240||barcode?.Length>128)throw new MasterDataValidationException("Warehouse, Bin Code, Rack Name, Bin/Partition Number, Location Type and valid documented lengths are required.");if(!InventoryConditionCodes.All.Contains(condition,StringComparer.Ordinal))throw new MasterDataValidationException("Material Condition must be one of the documented inventory condition codes.");if(r.CapacityQuantity<0)throw new MasterDataValidationException("Capacity Quantity cannot be negative.");if(r.CapacityQuantity.HasValue!=!string.IsNullOrWhiteSpace(uom))throw new MasterDataValidationException("Capacity Quantity and Capacity UOM must be supplied together.");if(uom.Length>0&&!await db.Uoms.AnyAsync(x=>x.Code==uom&&x.IsActive,ct))throw new MasterDataValidationException("Capacity UOM must identify an active UOM.");var warehouse=await db.Warehouses.SingleOrDefaultAsync(x=>x.CompanyId==companyId&&x.WarehouseCode==wh&&x.IsActive,ct)??throw new MasterDataValidationException("Warehouse Code must identify an active warehouse in the selected company.");if(await db.RackBins.AnyAsync(x=>x.CompanyId==companyId&&x.Id!=id&&x.BinCode==code,ct))throw new MasterDataConflictException("Bin Code already exists in the selected company.");return(warehouse.Id,warehouse.WarehouseCode,code,rack,number,zone,type,condition,r.CapacityQuantity,uom.Length==0?null:uom,barcode,description);}
    private async Task<SESS.NexaERP.Domain.Foundation.Company> Company(CancellationToken ct)=>await db.Companies.SingleOrDefaultAsync(x=>x.Code==user.OrganizationId&&x.IsActive&&x.Status=="ACTIVE",ct)??throw new UnauthorizedAccessException("Selected company is unavailable.");
    private void AddHistory(RackBin x)=>db.MasterStatusHistories.Add(new MasterStatusHistory{MasterType=nameof(RackBin),MasterId=x.Id,MasterCode=x.BinCode,NewStatus=x.Status,Reason="Rack/bin draft created",SourceRevision="WAREHOUSE_MASTER",CorrelationId=$"RACK_BIN_CREATE_{x.Id:N}",CreatedBy=user.LoginId});
    private static MasterDataExportRow ExportRow(RackBin x,string? warehouseCode=null)=>new(new Dictionary<string,object?>(StringComparer.Ordinal){{"RecordId",x.Id.ToString()},{"Version",x.Version},{"WarehouseCode",warehouseCode??x.Warehouse?.WarehouseCode},{"BinCode",x.BinCode},{"RackName",x.RackName},{"BinNameNumber",x.BinNameNumber},{"Zone",x.Zone},{"LocationType",x.LocationType},{"MaterialCondition",x.MaterialCondition},{"CapacityQuantity",x.CapacityQuantity},{"CapacityUom",x.CapacityUom},{"Barcode",x.Barcode},{"Description",x.Description},{"Status",x.Status},{"ApprovalStatus",x.ApprovalStatus},{"IsActive",x.IsActive}});
    private static MasterDataExistingRecord Existing(RackBin x)=>new(x.Id,x.BinCode,x.BinCode,x.Version,ExportRow(x).Values.ToDictionary(k=>k.Key,v=>Convert.ToString(v.Value,CultureInfo.InvariantCulture),StringComparer.Ordinal));
}
