using System.Data;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using SESS.NexaERP.Application.Purchase;
using SESS.NexaERP.Domain.Authorization;
using SESS.NexaERP.Domain.Purchase;

namespace SESS.NexaERP.Infrastructure.Purchase;

public sealed partial class EfRev869BPurchaseService
{
    public async Task<Rev869BDocumentResult> CreateComparisonAsync(Rev869BCreateComparisonRequest request, CancellationToken ct)
    {
        var actor = RequireActor(); RequireRole(Rev869ARoleCodes.PurchaseManager); await using var tx = await db.Database.BeginTransactionAsync(IsolationLevel.Serializable, ct);
        var organization = RequireOrganization(); var existing = await db.CommercialComparisons.SingleOrDefaultAsync(x => x.OrganizationId == organization && x.IdempotencyKey == request.IdempotencyKey.Trim(), ct); if (existing is not null) return Result(existing.Id, existing.ComparisonNumber, existing.Status, existing.Version);
        var rfq = await db.RequestForQuotations.SingleAsync(x => x.OrganizationId == organization && x.RfqNumber == request.RfqNumber.Trim().ToUpper(), ct); await RequireScopeAsync(actor, organization, rfq.RequestingDepartmentId, rfq.DeliveryWarehouseId, null, rfq.OwnerEmployeeId, ct);
        var quotes = await db.VendorQuotations.Include(x => x.Lines).Where(x => x.RfqVendorInvitation!.RequestForQuotationId == rfq.Id && x.IsCurrentRevision && x.Status == Rev869BStatuses.TechnicallyCompliant).ToListAsync(ct); if (quotes.Count == 0) throw new InvalidOperationException("No current technically compliant quotation is available."); if (quotes.Any(x => x.CurrencyCode != rfq.CurrencyCode)) throw new InvalidOperationException("Currency conversion unavailable; quotations must match RFQ currency.");
        var next = await NextNumberAsync(organization, "CMP", DateOnly.FromDateTime(DateTime.UtcNow), ct); var comparison = new CommercialComparison { OrganizationId = organization, ComparisonNumber = next.Number, FinancialYear = next.Year, SequenceNumber = next.Sequence, RequestForQuotationId = rfq.Id, OwnerEmployeeId = actor, CurrencyCode = rfq.CurrencyCode, IsSingleSource = rfq.IsSingleSource, SingleSourceJustification = rfq.SingleSourceJustification, IdempotencyKey = request.IdempotencyKey.Trim(), CreatedBy = user.LoginId };
        foreach (var quote in quotes) foreach (var line in quote.Lines) comparison.Lines.Add(new CommercialComparisonLine { VendorQuotationLineId = line.Id, VendorId = quote.VendorId, TechnicalComplianceSnapshot = Rev869BStatuses.TechnicallyCompliant, CommercialSnapshotJson = JsonSerializer.Serialize(line, JsonOptions), DeliverySnapshot = line.PromisedDeliveryDate.ToString("yyyy-MM-dd"), WarrantySnapshot = quote.WarrantyTermsSnapshot, PaymentTermsSnapshot = quote.PaymentTermsSnapshot, TotalPayableValue = line.TotalPayableValue, CreatedBy = user.LoginId });
        db.CommercialComparisons.Add(comparison); AddStatus("CommercialComparison", comparison.Id, comparison.ComparisonNumber, null, comparison.Status, "Create", "Created from technically compliant quotations", request.IdempotencyKey); await db.SaveChangesAsync(ct); await audit.WriteAsync("Purchase", "CreateComparison", nameof(CommercialComparison), comparison.Id.ToString(), null, new { comparison.ComparisonNumber, lineCount = comparison.Lines.Count }, ct); await tx.CommitAsync(ct); return Result(comparison.Id, comparison.ComparisonNumber, comparison.Status, comparison.Version);
    }

    public async Task<Rev869BDocumentResult> RecommendAsync(string number, Rev869BRecommendComparisonRequest request, CancellationToken ct)
    {
        var actor = RequireActor(); RequireRole(Rev869ARoleCodes.PurchaseManager); var comparison = await LoadComparisonAsync(number, ct); await AuthorizeComparisonAsync(actor, comparison, ct); CheckVersion(comparison.Version, request.Version); if (comparison.Status is not (Rev869BStatuses.Draft or Rev869BStatuses.RevisionRequested)) throw new InvalidOperationException("Comparison cannot be recommended now.");
        var quote = await db.VendorQuotations.Include(x => x.Lines).SingleAsync(x => x.Id == request.VendorQuotationId && x.IsCurrentRevision && x.Status == Rev869BStatuses.TechnicallyCompliant, ct); var comparisonLineIds = comparison.Lines.Select(x => x.VendorQuotationLineId).ToHashSet(); if (quote.Lines.Any(x => !comparisonLineIds.Contains(x.Id))) throw new InvalidOperationException("Recommended quotation is outside this comparison."); if (comparison.IsSingleSource && string.IsNullOrWhiteSpace(request.SingleSourceJustification ?? comparison.SingleSourceJustification)) throw new InvalidOperationException("Single-source recommendation justification is required.");
        foreach (var line in comparison.Lines) { line.IsRecommended = quote.Lines.Any(x => x.Id == line.VendorQuotationLineId); line.RecommendationReason = line.IsRecommended ? RequiredRemarks(request.RecommendationRemarks) : null; }
        comparison.RecommendedVendorQuotationId = quote.Id; comparison.SelectedVendorId = quote.VendorId; comparison.TotalPayableValue = quote.TotalPayableValue; comparison.SingleSourceJustification = Trim(request.SingleSourceJustification) ?? comparison.SingleSourceJustification; comparison.RecommendationRemarks = RequiredRemarks(request.RecommendationRemarks); comparison.ApprovalRoute = await ResolveApprovalRouteAsync(comparison.TotalPayableValue, comparison.OrganizationId, ct); Transition(comparison, Rev869BStatuses.PendingApproval, "Recommend", comparison.RecommendationRemarks, request.IdempotencyKey); await db.SaveChangesAsync(ct); await audit.WriteAsync("Purchase", "RecommendVendor", nameof(CommercialComparison), comparison.Id.ToString(), null, new { comparison.SelectedVendorId, comparison.TotalPayableValue, comparison.ApprovalRoute }, ct); return Result(comparison.Id, comparison.ComparisonNumber, comparison.Status, comparison.Version);
    }

    public Task<Rev869BDocumentResult> ApproveAsync(string number, Rev869BApprovalActionRequest request, CancellationToken ct) => ApprovalActionAsync(number, request, "Approve", Rev869BStatuses.Approved, ct);
    public Task<Rev869BDocumentResult> RejectAsync(string number, Rev869BApprovalActionRequest request, CancellationToken ct) => ApprovalActionAsync(number, request, "Reject", Rev869BStatuses.Rejected, ct);
    public Task<Rev869BDocumentResult> RequestRevisionAsync(string number, Rev869BApprovalActionRequest request, CancellationToken ct) => ApprovalActionAsync(number, request, "RequestRevision", Rev869BStatuses.RevisionRequested, ct);

    public async Task<Rev869BDocumentResult> ResubmitAsync(string number, Rev869BApprovalActionRequest request, CancellationToken ct)
    {
        var actor = RequireActor(); RequireRole(Rev869ARoleCodes.PurchaseManager); var c = await LoadComparisonAsync(number, ct); await AuthorizeComparisonAsync(actor, c, ct); CheckVersion(c.Version, request.Version); if (c.Status != Rev869BStatuses.RevisionRequested) throw new InvalidOperationException("Only revision-requested comparison may be resubmitted."); var from = c.Status; Transition(c, Rev869BStatuses.PendingApproval, "Resubmit", RequiredRemarks(request.Remarks), request.IdempotencyKey); AddApproval(c, "Resubmit", from, c.Status, request.Remarks, request.IdempotencyKey); await db.SaveChangesAsync(ct); await audit.WriteAsync("Purchase", "ResubmitComparison", nameof(CommercialComparison), c.Id.ToString(), null, new { c.Status }, ct); return Result(c.Id, c.ComparisonNumber, c.Status, c.Version);
    }

    private async Task<Rev869BDocumentResult> ApprovalActionAsync(string number, Rev869BApprovalActionRequest request, string action, string next, CancellationToken ct)
    {
        var actor = RequireActor(); var c = await LoadComparisonAsync(number, ct); await AuthorizeComparisonAsync(actor, c, ct); CheckVersion(c.Version, request.Version); if (c.Status != Rev869BStatuses.PendingApproval) throw new InvalidOperationException("Comparison is not pending approval."); var department = await db.RequestForQuotations.Where(x => x.Id == c.RequestForQuotationId).Select(x => x.RequestingDepartmentId).SingleAsync(ct); await RequireApproverAsync(c.ApprovalRoute, department, actor, c.CreatedBy, ct); var from = c.Status; Transition(c, next, action, RequiredRemarks(request.Remarks), request.IdempotencyKey); AddApproval(c, action, from, next, request.Remarks, request.IdempotencyKey); await db.SaveChangesAsync(ct); await audit.WriteAsync("Purchase", action + "Comparison", nameof(CommercialComparison), c.Id.ToString(), new { status = from }, new { status = next, c.ApprovalRoute }, ct); return Result(c.Id, c.ComparisonNumber, c.Status, c.Version);
    }

    public async Task<Rev869BDocumentResult> CreatePurchaseOrderAsync(Rev869BCreatePurchaseOrderRequest request, CancellationToken ct)
    {
        var actor = RequireActor(); RequireRole(Rev869ARoleCodes.PurchaseManager); await using var tx = await db.Database.BeginTransactionAsync(IsolationLevel.Serializable, ct); var c = await LoadComparisonAsync(request.ComparisonNumber, ct); await AuthorizeComparisonAsync(actor, c, ct); if (c.Status != Rev869BStatuses.Approved || !c.RecommendedVendorQuotationId.HasValue || !c.SelectedVendorId.HasValue) throw new InvalidOperationException("PO requires approved comparison and explicit selection.");
        var duplicate = await db.PurchaseOrders.SingleOrDefaultAsync(x => x.OrganizationId == c.OrganizationId && x.IdempotencyKey == request.IdempotencyKey.Trim(), ct); if (duplicate is not null) return Result(duplicate.Id, duplicate.PoNumber, duplicate.Status, duplicate.Version);
        var rfq = await db.RequestForQuotations.SingleAsync(x => x.Id == c.RequestForQuotationId, ct); var quote = await db.VendorQuotations.Include(x => x.Lines).ThenInclude(x => x.RequestForQuotationLine).SingleAsync(x => x.Id == c.RecommendedVendorQuotationId, ct); if (!await vendors.IsEligibleAsync(quote.VendorId, c.OrganizationId, null, DateOnly.FromDateTime(DateTime.UtcNow), ct)) throw new InvalidOperationException("Selected vendor is no longer qualified.");
        var next = await NextNumberAsync(c.OrganizationId, "PO", DateOnly.FromDateTime(DateTime.UtcNow), ct); var po = new PurchaseOrder { OrganizationId = c.OrganizationId, PoNumber = next.Number, FinancialYear = next.Year, SequenceNumber = next.Sequence, RootPurchaseOrderId = Guid.NewGuid(), RevisionNumber = 1, CommercialComparisonId = c.Id, VendorId = quote.VendorId, RequestingDepartmentId = rfq.RequestingDepartmentId, DeliveryWarehouseId = rfq.DeliveryWarehouseId, OwnerEmployeeId = actor, Status = Rev869BStatuses.Approved, CurrencyCode = quote.CurrencyCode, TotalPayableValue = quote.TotalPayableValue, PaymentTermsSnapshot = quote.PaymentTermsSnapshot, DeliveryTermsSnapshot = quote.DeliveryTermsSnapshot, WarrantyTermsSnapshot = quote.WarrantyTermsSnapshot, IdempotencyKey = request.IdempotencyKey.Trim(), CreatedBy = user.LoginId };
        var lineNo = 0;
        foreach (var ql in quote.Lines)
        {
            var source = ql.RequestForQuotationLine!; var ordered = await OrderedQuantityAsync(source.PurchaseRequisitionLineId, ct); var remaining = source.ApprovedQuantitySnapshot - ordered; if (ql.Quantity > remaining) throw new InvalidOperationException("Cumulative PO quantity exceeds approved outstanding quantity."); var comparisonLine = c.Lines.Single(x => x.VendorQuotationLineId == ql.Id);
            po.Lines.Add(new PurchaseOrderLine { CommercialComparisonLineId = comparisonLine.Id, PurchaseRequisitionLineId = source.PurchaseRequisitionLineId, PurchaseRequirementHandoffId = source.PurchaseRequirementHandoffId, ItemId = source.ItemId, LineNumber = ++lineNo, ItemCodeSnapshot = source.ItemCodeSnapshot, ItemNameSnapshot = source.ItemNameSnapshot, UomSnapshot = source.UomSnapshot, OrderedQuantity = ql.Quantity, ApprovedOutstandingQuantitySnapshot = remaining, UnitRate = ql.UnitRate, CommercialSnapshotJson = JsonSerializer.Serialize(ql, JsonOptions), TaxRuleSnapshotJson = ql.TaxRuleSnapshotJson, TotalPayableValue = ql.TotalPayableValue, CreatedBy = user.LoginId });
            po.TaxableValue += ql.TaxableValue; po.DiscountValue += ql.DiscountValue; po.TaxValue += ql.CgstValue + ql.SgstValue + ql.IgstValue + ql.CessValue; po.PackingForwarding += ql.PackingForwarding; po.Freight += ql.Freight; po.Insurance += ql.Insurance; po.OtherCharges += ql.OtherCharges; po.RoundOff += ql.RoundOff;
        }
        db.PurchaseOrders.Add(po); AddPoHistory(po, "Create", "", po.Status, "Created from approved comparison", request.IdempotencyKey); AddStatus("PurchaseOrder", po.Id, po.PoNumber, null, po.Status, "Create", "Created from approved comparison", request.IdempotencyKey); await db.SaveChangesAsync(ct); await audit.WriteAsync("Purchase", "CreatePO", nameof(PurchaseOrder), po.Id.ToString(), null, new { po.PoNumber, po.TotalPayableValue }, ct); await tx.CommitAsync(ct); return Result(po.Id, po.PoNumber, po.Status, po.Version);
    }

    public async Task<Rev869BDocumentResult> IssuePurchaseOrderAsync(string number, Rev869BIssuePurchaseOrderRequest request, CancellationToken ct)
    {
        var actor = RequireActor(); RequireRole(Rev869ARoleCodes.PurchaseManager); await using var tx = await db.Database.BeginTransactionAsync(IsolationLevel.Serializable, ct); var po = await LoadPoAsync(number, ct); await AuthorizePoAsync(actor, po, ct); CheckVersion(po.Version, request.Version); if (po.Status != Rev869BStatuses.Approved) throw new InvalidOperationException("Only approved current PO may be issued."); var from = po.Status; po.Status = Rev869BStatuses.Issued; po.IssuedAt = DateTimeOffset.UtcNow; po.UpdatedAt = DateTimeOffset.UtcNow; po.UpdatedBy = user.LoginId;
        foreach (var line in po.Lines) db.MaterialFollowUpHandoffs.Add(new MaterialFollowUpHandoff { PurchaseOrderId = po.Id, PurchaseOrderLineId = line.Id, HandoffNumber = $"MFU-{po.PoNumber}-{line.LineNumber:000}", OrderedQuantitySnapshot = line.OrderedQuantity, HandoffAt = DateTimeOffset.UtcNow, CorrelationId = request.IdempotencyKey.Trim(), CreatedBy = user.LoginId }); AddPoHistory(po, "Issue", from, po.Status, RequiredRemarks(request.Remarks), request.IdempotencyKey); AddStatus("PurchaseOrder", po.Id, po.PoNumber, from, po.Status, "Issue", request.Remarks, request.IdempotencyKey); await db.SaveChangesAsync(ct); await audit.WriteAsync("Purchase", "IssuePO", nameof(PurchaseOrder), po.Id.ToString(), new { status = from }, new { po.Status, po.IssuedAt }, ct); await tx.CommitAsync(ct); return Result(po.Id, po.PoNumber, po.Status, po.Version);
    }

    public async Task<Rev869BDocumentResult> AmendPurchaseOrderAsync(string number, Rev869BAmendPurchaseOrderRequest request, CancellationToken ct)
    {
        var actor = RequireActor(); RequireRole(Rev869ARoleCodes.PurchaseManager); await using var tx = await db.Database.BeginTransactionAsync(IsolationLevel.Serializable, ct); var prior = await LoadPoAsync(number, ct); await AuthorizePoAsync(actor, prior, ct); CheckVersion(prior.Version, request.Version); if (prior.Status is not (Rev869BStatuses.Approved or Rev869BStatuses.Issued)) throw new InvalidOperationException("Only approved/issued current PO may be amended."); var oldStatus = prior.Status;
        var next = new PurchaseOrder { OrganizationId = prior.OrganizationId, PoNumber = prior.PoNumber, FinancialYear = prior.FinancialYear, SequenceNumber = prior.SequenceNumber, RootPurchaseOrderId = prior.RootPurchaseOrderId, PreviousVersionId = prior.Id, RevisionNumber = prior.RevisionNumber + 1, CommercialComparisonId = prior.CommercialComparisonId, VendorId = prior.VendorId, RequestingDepartmentId = prior.RequestingDepartmentId, DeliveryWarehouseId = prior.DeliveryWarehouseId, OwnerEmployeeId = actor, Status = Rev869BStatuses.PendingReapproval, CurrencyCode = prior.CurrencyCode, TaxableValue = prior.TaxableValue, DiscountValue = prior.DiscountValue, TaxValue = prior.TaxValue, PackingForwarding = prior.PackingForwarding, Freight = prior.Freight, Insurance = prior.Insurance, OtherCharges = prior.OtherCharges, RoundOff = prior.RoundOff, TotalPayableValue = prior.TotalPayableValue, PaymentTermsSnapshot = Required(request.PaymentTerms, "Payment terms"), DeliveryTermsSnapshot = Required(request.DeliveryTerms, "Delivery terms"), WarrantyTermsSnapshot = Required(request.WarrantyTerms, "Warranty terms"), AmendmentReason = RequiredRemarks(request.AmendmentReason), IdempotencyKey = request.IdempotencyKey.Trim(), CreatedBy = user.LoginId };
        foreach (var l in prior.Lines) next.Lines.Add(new PurchaseOrderLine { CommercialComparisonLineId = l.CommercialComparisonLineId, PurchaseRequisitionLineId = l.PurchaseRequisitionLineId, PurchaseRequirementHandoffId = l.PurchaseRequirementHandoffId, ItemId = l.ItemId, LineNumber = l.LineNumber, ItemCodeSnapshot = l.ItemCodeSnapshot, ItemNameSnapshot = l.ItemNameSnapshot, UomSnapshot = l.UomSnapshot, OrderedQuantity = l.OrderedQuantity, ApprovedOutstandingQuantitySnapshot = l.ApprovedOutstandingQuantitySnapshot, UnitRate = l.UnitRate, CommercialSnapshotJson = l.CommercialSnapshotJson, TaxRuleSnapshotJson = l.TaxRuleSnapshotJson, TotalPayableValue = l.TotalPayableValue, CreatedBy = user.LoginId });
        prior.IsCurrentVersion = false; prior.Status = Rev869BStatuses.Superseded; prior.UpdatedAt = DateTimeOffset.UtcNow; prior.UpdatedBy = user.LoginId; db.PurchaseOrders.Add(next); AddPoHistory(prior, "Supersede", oldStatus, prior.Status, request.AmendmentReason, request.IdempotencyKey); AddPoHistory(next, "Amend", oldStatus, next.Status, request.AmendmentReason, request.IdempotencyKey); await db.SaveChangesAsync(ct); await audit.WriteAsync("Purchase", "AmendPO", nameof(PurchaseOrder), next.Id.ToString(), new { prior.Id, prior.RevisionNumber }, new { next.RevisionNumber, next.Status }, ct); await tx.CommitAsync(ct); return Result(next.Id, next.PoNumber, next.Status, next.Version);
    }

    public async Task<Rev869BDocumentResult> ApprovePurchaseOrderAsync(string number, Rev869BApprovalActionRequest request, CancellationToken ct)
    {
        var actor = RequireActor(); var po = await LoadPoAsync(number, ct); await AuthorizePoAsync(actor, po, ct); CheckVersion(po.Version, request.Version); if (po.Status != Rev869BStatuses.PendingReapproval) throw new InvalidOperationException("Only pending-reapproval amendment may be approved."); var route = await ResolveApprovalRouteAsync(po.TotalPayableValue, po.OrganizationId, ct); await RequireApproverAsync(route, po.RequestingDepartmentId, actor, po.CreatedBy, ct); var from = po.Status; po.Status = Rev869BStatuses.Approved; po.UpdatedAt = DateTimeOffset.UtcNow; po.UpdatedBy = user.LoginId; AddPoHistory(po, "ApproveAmendment", from, po.Status, RequiredRemarks(request.Remarks), request.IdempotencyKey); await db.SaveChangesAsync(ct); await audit.WriteAsync("Purchase", "ApprovePOAmendment", nameof(PurchaseOrder), po.Id.ToString(), new { status = from }, new { po.Status, route }, ct); return Result(po.Id, po.PoNumber, po.Status, po.Version);
    }

    public async Task<Rev869BDocumentResult> CancelPurchaseOrderAsync(string number, Rev869BCancelPurchaseOrderRequest request, CancellationToken ct)
    {
        var actor = RequireActor(); RequireRole(Rev869ARoleCodes.PurchaseManager, Rev869ARoleCodes.TechnicalDirector, Rev869ARoleCodes.ManagingDirector); var po = await LoadPoAsync(number, ct); await AuthorizePoAsync(actor, po, ct); CheckVersion(po.Version, request.Version); if (po.Status == Rev869BStatuses.Cancelled) throw new InvalidOperationException("PO already cancelled."); var from = po.Status; po.Status = Rev869BStatuses.Cancelled; po.CancelledAt = DateTimeOffset.UtcNow; po.CancellationReason = RequiredRemarks(request.Reason); po.UpdatedAt = DateTimeOffset.UtcNow; po.UpdatedBy = user.LoginId; AddPoHistory(po, "Cancel", from, po.Status, request.Reason, request.IdempotencyKey); AddStatus("PurchaseOrder", po.Id, po.PoNumber, from, po.Status, "Cancel", request.Reason, request.IdempotencyKey); await db.SaveChangesAsync(ct); await audit.WriteAsync("Purchase", "CancelPO", nameof(PurchaseOrder), po.Id.ToString(), new { status = from }, new { po.Status, po.CancelledAt }, ct); return Result(po.Id, po.PoNumber, po.Status, po.Version);
    }
}