using Microsoft.EntityFrameworkCore;
using SESS.NexaERP.Domain.Stores;

namespace SESS.NexaERP.Infrastructure.Persistence;

public sealed partial class NexaErpDbContext
{
    public DbSet<VendorBill> VendorBills => Set<VendorBill>();
    public DbSet<VendorBillLine> VendorBillLines => Set<VendorBillLine>();
    public DbSet<VendorBillHistory> VendorBillHistories => Set<VendorBillHistory>();
    public DbSet<FifoInventoryCostLayer> FifoInventoryCostLayers => Set<FifoInventoryCostLayer>();
    public DbSet<FifoCostConsumption> FifoCostConsumptions => Set<FifoCostConsumption>();
    public DbSet<VendorBillCostAllocation> VendorBillCostAllocations => Set<VendorBillCostAllocation>();
    public DbSet<VendorBillCharge> VendorBillCharges => Set<VendorBillCharge>();
    public DbSet<VendorBillChargeAllocation> VendorBillChargeAllocations => Set<VendorBillChargeAllocation>();
    public DbSet<FifoLandedCostAdjustment> FifoLandedCostAdjustments => Set<FifoLandedCostAdjustment>();
    public DbSet<ItemCompanyLastPurchase> ItemCompanyLastPurchases => Set<ItemCompanyLastPurchase>();

    private static void ConfigureVendorBillCosting(ModelBuilder m)
    {
        m.Entity<VendorBill>(e => {
            e.ToTable("vendor_bills", t => { t.HasCheckConstraint("CK_vendor_bill_status", "\"Status\" IN ('DRAFT','ACCEPTED','REJECTED','REVERSED')"); t.HasCheckConstraint("CK_vendor_bill_match", "\"MatchStatus\" IN ('MATCHED','PRICE_MISMATCH')"); t.HasCheckConstraint("CK_vendor_bill_value", "\"TotalPayableValue\">=0"); });
            e.HasKey(x => x.Id); e.HasAlternateKey(x => new { x.CompanyId, x.Id }); e.HasIndex(x => new { x.CompanyId, x.BillNumber }).IsUnique().HasFilter("\"Status\" NOT IN ('REVERSED','REJECTED')"); e.HasIndex(x => new { x.CompanyId, x.GoodsReceiptId }).IsUnique().HasFilter("\"Status\" NOT IN ('REVERSED','REJECTED')"); e.HasIndex(x => new { x.CompanyId, x.CreateIdempotencyKey }).IsUnique(); e.HasIndex(x => new { x.CompanyId, x.DecisionIdempotencyKey }).IsUnique().HasFilter("\"DecisionIdempotencyKey\" IS NOT NULL"); e.HasIndex(x => new { x.CompanyId, x.ReversalIdempotencyKey }).IsUnique().HasFilter("\"ReversalIdempotencyKey\" IS NOT NULL");
            e.Property(x => x.BillNumber).HasMaxLength(100).IsRequired(); e.Property(x => x.Status).HasMaxLength(20).IsRequired(); e.Property(x => x.MatchStatus).HasMaxLength(30).IsRequired(); e.Property(x => x.TotalPayableValue).HasPrecision(24, 6); e.Property(x => x.TotalChargeValue).HasPrecision(24, 6); e.Property(x => x.TotalLandedValue).HasPrecision(24, 6); e.Property(x => x.ActorRoleCode).HasMaxLength(100).IsRequired(); e.Property(x => x.ResolvedRoleAssignmentType).HasMaxLength(20).IsRequired(); e.Property(x => x.CreateIdempotencyKey).HasMaxLength(100).IsRequired(); e.Property(x => x.CreateRequestFingerprint).HasColumnType("character(64)").IsRequired(); e.Property(x => x.DecisionActorRoleCode).HasMaxLength(100); e.Property(x => x.DecisionRoleAssignmentType).HasMaxLength(20); e.Property(x => x.DecisionReason).HasMaxLength(1000); e.Property(x => x.DecisionIdempotencyKey).HasMaxLength(100); e.Property(x => x.DecisionRequestFingerprint).HasColumnType("character(64)"); e.Property(x => x.ReversalActorRoleCode).HasMaxLength(100); e.Property(x => x.ReversalRoleAssignmentType).HasMaxLength(20); e.Property(x => x.ReversalReason).HasMaxLength(1000); e.Property(x => x.ReversalIdempotencyKey).HasMaxLength(100); e.Property(x => x.ReversalRequestFingerprint).HasColumnType("character(64)");
            e.HasOne(x => x.GoodsReceipt).WithMany().HasForeignKey(x => new { x.CompanyId, x.GoodsReceiptId }).HasPrincipalKey(x => new { x.CompanyId, x.Id }).OnDelete(DeleteBehavior.Restrict); e.HasOne(x => x.PurchaseOrder).WithMany().HasForeignKey(x => x.PurchaseOrderId).OnDelete(DeleteBehavior.Restrict); e.HasOne(x => x.Vendor).WithMany().HasForeignKey(x => x.VendorId).OnDelete(DeleteBehavior.Restrict); e.HasOne(x => x.CreatedByEmployee).WithMany().HasForeignKey(x => x.CreatedByEmployeeId).OnDelete(DeleteBehavior.Restrict); e.HasOne(x => x.ResolvedRoleAssignment).WithMany().HasForeignKey(x => x.ResolvedRoleAssignmentId).OnDelete(DeleteBehavior.Restrict); e.HasOne(x => x.DecidedByEmployee).WithMany().HasForeignKey(x => x.DecidedByEmployeeId).OnDelete(DeleteBehavior.Restrict); e.HasOne(x => x.DecisionRoleAssignment).WithMany().HasForeignKey(x => x.DecisionRoleAssignmentId).OnDelete(DeleteBehavior.Restrict); e.HasOne(x => x.ReversedByEmployee).WithMany().HasForeignKey(x => x.ReversedByEmployeeId).OnDelete(DeleteBehavior.Restrict); e.HasOne(x => x.ReversalRoleAssignment).WithMany().HasForeignKey(x => x.ReversalRoleAssignmentId).OnDelete(DeleteBehavior.Restrict);
        });
        m.Entity<VendorBillLine>(e => {
            e.ToTable("vendor_bill_lines", t => t.HasCheckConstraint("CK_vendor_bill_line_values", "\"BilledQuantity\">0 AND \"ExpectedUnitRate\">=0 AND \"BilledUnitRate\">=0 AND \"ExpectedPayableValue\">=0 AND \"BilledPayableValue\">=0")); e.HasKey(x => x.Id); e.HasAlternateKey(x => new { x.CompanyId, x.Id }); e.HasIndex(x => new { x.VendorBillId, x.LineNumber }).IsUnique(); e.HasIndex(x => new { x.CompanyId, x.VendorBillId, x.GoodsReceiptLineId }).IsUnique();
            e.Property(x => x.BilledQuantity).HasPrecision(24, 6); e.Property(x => x.ExpectedUnitRate).HasPrecision(24, 6); e.Property(x => x.BilledUnitRate).HasPrecision(24, 6); e.Property(x => x.ExpectedPayableValue).HasPrecision(24, 6); e.Property(x => x.BilledPayableValue).HasPrecision(24, 6); e.Property(x => x.VerifiedGrossWeightKg).HasPrecision(24, 6); e.Property(x => x.MatchStatus).HasMaxLength(30).IsRequired();
            e.HasOne(x => x.VendorBill).WithMany(x => x.Lines).HasForeignKey(x => new { x.CompanyId, x.VendorBillId }).HasPrincipalKey(x => new { x.CompanyId, x.Id }).OnDelete(DeleteBehavior.Restrict); e.HasOne(x => x.GoodsReceiptLine).WithMany().HasForeignKey(x => new { x.CompanyId, x.GoodsReceiptLineId }).HasPrincipalKey(x => new { x.CompanyId, x.Id }).OnDelete(DeleteBehavior.Restrict); e.HasOne(x => x.PurchaseOrderLine).WithMany().HasForeignKey(x => x.PurchaseOrderLineId).OnDelete(DeleteBehavior.Restrict); e.HasOne(x => x.Item).WithMany().HasForeignKey(x => x.ItemId).OnDelete(DeleteBehavior.Restrict);
        });
        m.Entity<FifoInventoryCostLayer>(e => {
            e.ToTable("fifo_inventory_cost_layers", t => t.HasCheckConstraint("CK_fifo_cost_layer", "\"QuantityReceived\">0 AND \"UnitCost\">=0 AND \"LayerValue\">=0 AND \"CostBasis\" IN ('PO_PROVISIONAL_IDENTICAL','OPENING_LANDED') AND num_nonnulls(\"GoodsReceiptLineId\",\"OpeningStockLineId\")=1")); e.HasKey(x => x.Id); e.HasAlternateKey(x => new { x.CompanyId, x.Id }); e.HasIndex(x => new { x.CompanyId, x.GoodsReceiptLineId }).IsUnique(); e.HasIndex(x => new { x.CompanyId, x.OpeningStockLineId }).IsUnique().HasFilter("\"OpeningStockLineId\" IS NOT NULL"); e.HasIndex(x => new { x.CompanyId, x.ItemId, x.ReceivedAt }); e.Property(x => x.QuantityReceived).HasPrecision(24, 6); e.Property(x => x.UnitCost).HasPrecision(24, 6); e.Property(x => x.LayerValue).HasPrecision(24, 6); e.Property(x => x.CostBasis).HasMaxLength(40).IsRequired(); e.HasOne(x => x.GoodsReceiptLine).WithMany().HasForeignKey(x => new { x.CompanyId, x.GoodsReceiptLineId }).HasPrincipalKey(x => new { x.CompanyId, x.Id }).OnDelete(DeleteBehavior.Restrict); e.HasOne(x => x.OpeningStockLine).WithMany().HasForeignKey(x => new { x.CompanyId, x.OpeningStockLineId }).HasPrincipalKey(x => new { x.CompanyId, x.Id }).OnDelete(DeleteBehavior.Restrict); e.HasOne(x => x.Item).WithMany().HasForeignKey(x => x.ItemId).OnDelete(DeleteBehavior.Restrict);
        });
        m.Entity<FifoCostConsumption>(e => {
            e.ToTable("fifo_cost_consumptions", t => t.HasCheckConstraint("CK_fifo_cost_consumption", "\"Quantity\">0 AND \"UnitCost\">=0 AND \"ConsumedValue\">=0")); e.HasKey(x => x.Id); e.HasIndex(x => new { x.CompanyId, x.FifoInventoryCostLayerId, x.MaterialIssueLineId }).IsUnique(); e.Property(x => x.Quantity).HasPrecision(24, 6); e.Property(x => x.UnitCost).HasPrecision(24, 6); e.Property(x => x.ConsumedValue).HasPrecision(24, 6); e.HasOne(x => x.FifoInventoryCostLayer).WithMany().HasForeignKey(x => new { x.CompanyId, x.FifoInventoryCostLayerId }).HasPrincipalKey(x => new { x.CompanyId, x.Id }).OnDelete(DeleteBehavior.Restrict); e.HasOne(x => x.MaterialIssueLine).WithMany().HasForeignKey(x => new { x.CompanyId, x.MaterialIssueLineId }).HasPrincipalKey(x => new { x.CompanyId, x.Id }).OnDelete(DeleteBehavior.Restrict);
        });
        m.Entity<VendorBillCostAllocation>(e => {
            e.ToTable("vendor_bill_cost_allocations", t => t.HasCheckConstraint("CK_vendor_bill_cost_allocation", "\"AllocatedQuantity\">0 AND \"AcceptedValue\">=0")); e.HasKey(x => x.Id); e.HasIndex(x => new { x.CompanyId, x.VendorBillLineId, x.FifoInventoryCostLayerId }).IsUnique(); e.Property(x => x.AllocatedQuantity).HasPrecision(24, 6); e.Property(x => x.AcceptedValue).HasPrecision(24, 6); e.HasOne(x => x.VendorBillLine).WithMany().HasForeignKey(x => new { x.CompanyId, x.VendorBillLineId }).HasPrincipalKey(x => new { x.CompanyId, x.Id }).OnDelete(DeleteBehavior.Restrict); e.HasOne(x => x.FifoInventoryCostLayer).WithMany().HasForeignKey(x => new { x.CompanyId, x.FifoInventoryCostLayerId }).HasPrincipalKey(x => new { x.CompanyId, x.Id }).OnDelete(DeleteBehavior.Restrict);
        });
        m.Entity<VendorBillCharge>(e => {
            e.ToTable("vendor_bill_charges", t => t.HasCheckConstraint("CK_vendor_bill_charge", """ "ChargeNumber">0 AND "ChargeValue">=0 AND "ChargeType" IN ('DUTY','INSURANCE','FREIGHT','PACKING','HANDLING','CLEARING_AGENT','MISC_INWARD','NON_CREDITABLE_TAX','RECOVERABLE_GST') AND "AllocationBasis" IN ('ITEM_VALUE','GROSS_WEIGHT','EXCLUDED') AND "IncludedInInventoryCost"<>"IsRecoverableTax" """));
            e.HasKey(x => x.Id); e.HasAlternateKey(x => new { x.CompanyId, x.Id }); e.HasIndex(x => new { x.CompanyId, x.VendorBillId, x.ChargeNumber }).IsUnique();
            e.Property(x => x.ChargeType).HasMaxLength(40).IsRequired(); e.Property(x => x.ChargeValue).HasPrecision(24, 6); e.Property(x => x.AllocationBasis).HasMaxLength(30).IsRequired();
            e.HasOne(x => x.VendorBill).WithMany(x => x.Charges).HasForeignKey(x => new { x.CompanyId, x.VendorBillId }).HasPrincipalKey(x => new { x.CompanyId, x.Id }).OnDelete(DeleteBehavior.Restrict);
        });
        m.Entity<VendorBillChargeAllocation>(e => {
            e.ToTable("vendor_bill_charge_allocations", t => t.HasCheckConstraint("CK_vendor_bill_charge_allocation", """ "BasisValue">0 AND "AllocatedChargeValue">=0 """));
            e.HasKey(x => x.Id); e.HasIndex(x => new { x.CompanyId, x.VendorBillChargeId, x.VendorBillLineId }).IsUnique();
            e.Property(x => x.BasisValue).HasPrecision(24, 6); e.Property(x => x.AllocatedChargeValue).HasPrecision(24, 6);
            e.HasOne(x => x.VendorBillCharge).WithMany().HasForeignKey(x => new { x.CompanyId, x.VendorBillChargeId }).HasPrincipalKey(x => new { x.CompanyId, x.Id }).OnDelete(DeleteBehavior.Restrict);
            e.HasOne(x => x.VendorBillLine).WithMany().HasForeignKey(x => new { x.CompanyId, x.VendorBillLineId }).HasPrincipalKey(x => new { x.CompanyId, x.Id }).OnDelete(DeleteBehavior.Restrict);
        });
        m.Entity<FifoLandedCostAdjustment>(e => {
            e.ToTable("fifo_landed_cost_adjustments", t => t.HasCheckConstraint("CK_fifo_landed_cost_adjustment", """ "ProvisionalUnitRate">=0 AND "LandedUnitRate">=0 AND "AllocatedChargeValue">=0 AND "ConsumedQuantityAtAcceptance">=0 AND "RemainingQuantityAtAcceptance">=0 AND "ConsumedCostAdjustmentValue">=0 AND "RemainingStockAdjustmentValue">=0 AND "ConsumedCostAdjustmentValue"+"RemainingStockAdjustmentValue"="AllocatedChargeValue" """));
            e.HasKey(x => x.Id); e.HasIndex(x => new { x.CompanyId, x.VendorBillLineId, x.FifoInventoryCostLayerId }).IsUnique();
            e.Property(x => x.ProvisionalUnitRate).HasPrecision(24, 6); e.Property(x => x.LandedUnitRate).HasPrecision(24, 6); e.Property(x => x.AllocatedChargeValue).HasPrecision(24, 6); e.Property(x => x.ConsumedQuantityAtAcceptance).HasPrecision(24, 6); e.Property(x => x.RemainingQuantityAtAcceptance).HasPrecision(24, 6); e.Property(x => x.ConsumedCostAdjustmentValue).HasPrecision(24, 6); e.Property(x => x.RemainingStockAdjustmentValue).HasPrecision(24, 6);
            e.HasOne(x => x.VendorBillLine).WithMany().HasForeignKey(x => new { x.CompanyId, x.VendorBillLineId }).HasPrincipalKey(x => new { x.CompanyId, x.Id }).OnDelete(DeleteBehavior.Restrict);
            e.HasOne(x => x.FifoInventoryCostLayer).WithMany().HasForeignKey(x => new { x.CompanyId, x.FifoInventoryCostLayerId }).HasPrincipalKey(x => new { x.CompanyId, x.Id }).OnDelete(DeleteBehavior.Restrict);
        });
        m.Entity<ItemCompanyLastPurchase>(e => {
            e.ToTable("item_company_last_purchases", t => t.HasCheckConstraint("CK_item_company_last_purchase_complete", "num_nonnulls(\"LastPurchaseRate\",\"LastPurchaseDate\",\"LastPurchaseBillId\") IN (0,3) AND (\"LastPurchaseRate\" IS NULL OR \"LastPurchaseRate\">=0)"));
            e.HasKey(x => x.Id); e.HasIndex(x => new { x.CompanyId, x.ItemId }).IsUnique();
            e.Property(x => x.LastPurchaseRate).HasPrecision(24, 6);
            e.HasOne(x => x.Item).WithMany().HasForeignKey(x => x.ItemId).OnDelete(DeleteBehavior.Restrict);
            e.HasOne(x => x.LastPurchaseBill).WithMany().HasForeignKey(x => new { x.CompanyId, x.LastPurchaseBillId }).HasPrincipalKey(x => new { x.CompanyId, x.Id }).OnDelete(DeleteBehavior.Restrict);
        });        m.Entity<VendorBillHistory>(e => {
            e.ToTable("vendor_bill_history"); e.HasKey(x => x.Id); e.HasIndex(x => x.CorrelationId).IsUnique(); e.Property(x => x.Action).HasMaxLength(30).IsRequired(); e.Property(x => x.FromStatus).HasMaxLength(30); e.Property(x => x.ToStatus).HasMaxLength(30).IsRequired(); e.Property(x => x.ActorRoleCode).HasMaxLength(100).IsRequired(); e.Property(x => x.ResolvedRoleAssignmentType).HasMaxLength(20).IsRequired(); e.Property(x => x.CorrelationId).HasMaxLength(100).IsRequired(); e.Property(x => x.Remarks).HasMaxLength(1000).IsRequired(); e.HasOne(x => x.VendorBill).WithMany().HasForeignKey(x => new { x.CompanyId, x.VendorBillId }).HasPrincipalKey(x => new { x.CompanyId, x.Id }).OnDelete(DeleteBehavior.Restrict);
        });
    }
}
