const TONE_BY_VALUE: Record<string, string> = {
  Active: 'ok',
  Approved: 'ok',
  SeedApproved: 'ok',
  Verified: 'ok',
  Draft: 'muted',
  Submitted: 'info',
  PendingApproval: 'info',
  'Pending Approval': 'info',
  RevisionRequested: 'warn',
  'Revision Requested': 'warn',
  'Clarification Requested': 'warn',
  'On Hold': 'warn',
  Inactive: 'muted',
  LEFT: 'muted',
  Rejected: 'error',
  Blacklisted: 'error',
  Completed: 'ok',
  'W.I.P': 'info',
  'Not Completed': 'warn',
  // Stores document states
  DRAFT: 'muted',
  FINALIZED: 'ok',
  Issued: 'ok',
  QC_HOLD: 'warn',
  // Material issue request / issue / return states
  SUBMITTED: 'info',
  APPROVED: 'ok',
  REJECTED: 'error',
  CANCELLED: 'muted',
  PARTIALLY_FULFILLED: 'info',
  FULFILLED: 'ok',
  ISSUED: 'ok',
  PARTIALLY_RETURNED: 'info',
  RETURNED: 'ok',
  ACCEPTED: 'ok',
  CUSTOMER_FACING: 'warn',
  INTERNAL: 'info',
  Pending: 'warn',
  Decided: 'ok',
  // Job Order, FAT readiness, fitment and BOM states
  PENDING_ACCOUNTS: 'warn',
  OPEN: 'ok',
  NOT_RECONCILED: 'muted',
  BLOCKED: 'error',
  READY: 'ok',
  CONFIRMED: 'ok',
  REVERSED: 'error',
  'Self-reversal': 'warn',
  SUPERSEDED: 'muted',
  Pinned: 'ok',
  FITMENT: 'ok',
  REVERSAL: 'error',
  LOST: 'error',
  SCRAPPED: 'warn',
  UNEXPLAINED: 'error',
  EXPLAINED: 'ok',
  Overdue: 'error',
  // Actual BOM entry valuation
  LANDED_ACCEPTED: 'ok',
  PROVISIONAL_UNBILLED: 'warn',
}

export function StatusBadge({ value }: { value: string }) {
  const tone = TONE_BY_VALUE[value] ?? 'muted'
  return <span className={`badge badge-${tone}`}>{value}</span>
}
