using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Storage;
using Npgsql;
using SESS.NexaERP.Application.Audit;
using SESS.NexaERP.Application.Authorization;
using SESS.NexaERP.Application.Common;
using SESS.NexaERP.Application.Stores;
using SESS.NexaERP.Domain.Foundation;
using SESS.NexaERP.Domain.Purchase;
using SESS.NexaERP.Domain.Stores;
using SESS.NexaERP.Infrastructure.Persistence;

namespace SESS.NexaERP.Infrastructure.Stores;

public sealed class EfGoodsReceiptService(NexaErpDbContext db, ICurrentUser user, IRecordScopeAuthorizer scopes, IAuditWriter audit) : IGoodsReceiptService
{
    private static readonly JsonSerializerOptions JsonOptions = new(JsonSerializerDefaults.Web);

    public async Task<GoodsReceiptResult> CreateAsync(CreateGoodsReceiptRequest request, string idempotencyKey, CancellationToken ct)
    {
        var actor=Actor(); await RequireReceiptOperatorAsync(ct); var role=ActorRole(); var key=Required(idempotencyKey,"Idempotency-Key");
        ValidateHeader(request.VendorBillNumber,request.VendorBillDate,request.ReceivedAt,request.IsoReceiptVerificationJson,request.Lines);
        var fingerprint=Hash(new{GateEntryNumber=Required(request.GateEntryNumber,"GateEntryNumber").ToUpperInvariant(),VendorBillNumber=request.VendorBillNumber.Trim(),request.VendorBillDate,request.ReceivedAt,IsoReceiptVerificationJson=CanonicalObject(request.IsoReceiptVerificationJson),Lines=CanonicalLines(request.Lines)});
        await using var tx=await db.Database.BeginTransactionAsync(System.Data.IsolationLevel.Serializable,ct);
        var company=await Company(ct); var lockKey=$"GRN:CREATE:{company.Id}:{key}";
        await db.Database.ExecuteSqlInterpolatedAsync($"SELECT pg_advisory_xact_lock(hashtextextended({lockKey},0))",ct);
        var replay=await db.GoodsReceipts.SingleOrDefaultAsync(x=>x.CompanyId==company.Id&&x.IdempotencyKey==key,ct);
        if(replay is not null){if(replay.RequestFingerprint!=fingerprint)throw new StoresConflictException("Idempotency key was reused with different GRN data.");await tx.CommitAsync(ct);return await LoadResult(replay.Id,company.Id,false,ct);}
        var gateNumber=Required(request.GateEntryNumber,"GateEntryNumber").ToUpperInvariant();
        var gate=await GateQuery().SingleOrDefaultAsync(x=>x.CompanyId==company.Id&&x.GateEntryNumber==gateNumber,ct)??throw new KeyNotFoundException("Finalized Gate Entry was not found in the selected company.");
        if(gate.Status!="FINALIZED")throw new StoresConflictException("GRN requires a finalized Gate Entry.");
        var po=gate.PurchaseOrder??throw new StoresConflictException("Gate Entry Purchase Order is unavailable.");
        if(po.Status!=Rev869BStatuses.Issued)throw new StoresConflictException("GRN requires a current issued Purchase Order."); await RequireScope(po,ct);
        var qc=await EffectiveRule(company.Id,StoresConfigurationRuleKeys.QcCompletionDays,request.ReceivedAt,ct);var qcDays=JsonScalar<int>(qc.NewValueJson);
        var configJson=CanonicalObject(JsonSerializer.Serialize(new{qcCompletionDays=new{qc.Id,qc.VersionNumber,value=qcDays},capturedAt=request.ReceivedAt},JsonOptions));
        var receipt=new GoodsReceipt{CompanyId=company.Id,GrnNumber=await NextNumber(company.Id,Organization(),DateOnly.FromDateTime(request.ReceivedAt.UtcDateTime),ct),GateEntryId=gate.Id,PurchaseOrderId=gate.PurchaseOrderId,VendorId=gate.VendorId,VendorNameSnapshot=gate.VendorNameSnapshot,VendorBillNumber=request.VendorBillNumber.Trim(),VendorBillDate=request.VendorBillDate,VendorDcNumberSnapshot=gate.VendorDcNumber,ModeOfTransportSnapshot=gate.ModeOfTransport,ReceivedAt=request.ReceivedAt,ReceivedByEmployeeId=actor,IsoReceiptVerificationJson=CanonicalObject(request.IsoReceiptVerificationJson),ConfigurationSnapshotJson=configJson,ConfigurationSnapshotHash=await JsonbHash(configJson,ct),QcCompletionDaysConfigVersionId=qc.Id,QcCompletionDaysSnapshot=qcDays,QcDueAt=request.ReceivedAt.AddDays(qcDays),IdempotencyKey=key,RequestFingerprint=fingerprint,CreatedBy=user.LoginId};
        receipt.Lines=await BuildLines(receipt,gate,request.Lines,company.Id,actor,ct);db.GoodsReceipts.Add(receipt);AddHistory(receipt,null,"DRAFT","CREATED",Hash($"GRN:CREATED:{receipt.Id}"),role);
        await db.SaveChangesAsync(ct);await audit.WriteAsync("Stores","CreateGoodsReceipt",nameof(GoodsReceipt),receipt.Id.ToString(),null,new{receipt.GrnNumber,gate.GateEntryNumber,receipt.Status,Role=role},ct);await tx.CommitAsync(ct);return await LoadResult(receipt.Id,company.Id,false,ct);
    }

    public async Task<GoodsReceiptResult> UpdateAsync(Guid id,UpdateGoodsReceiptRequest request,CancellationToken ct)
    {
        var actor=Actor();await RequireReceiptOperatorAsync(ct);var role=ActorRole();ValidateHeader(request.VendorBillNumber,request.VendorBillDate,request.ReceivedAt,request.IsoReceiptVerificationJson,request.Lines);
        await using var tx=await db.Database.BeginTransactionAsync(System.Data.IsolationLevel.Serializable,ct);var company=await Company(ct);
        var receipt=await ReceiptQuery(true).SingleOrDefaultAsync(x=>x.Id==id&&x.CompanyId==company.Id,ct)??throw new KeyNotFoundException("GRN was not found.");
        if(receipt.Status!="DRAFT")throw new StoresConflictException("A finalized GRN is immutable; correct it by reversal and a new GRN.");if(receipt.Version!=request.Version)throw new DbUpdateConcurrencyException("GRN Version is stale.");
        var gate=receipt.GateEntry??throw new StoresConflictException("GRN Gate Entry is unavailable.");var po=receipt.PurchaseOrder??throw new StoresConflictException("GRN Purchase Order is unavailable.");await RequireScope(po,ct);
        db.GoodsReceiptLineSerials.RemoveRange(receipt.Lines.SelectMany(x=>x.Serials));db.GoodsReceiptLineLotAllocations.RemoveRange(receipt.Lines.SelectMany(x=>x.LotAllocations));db.GoodsReceiptLines.RemoveRange(receipt.Lines);receipt.Lines.Clear();await db.SaveChangesAsync(ct);
        var qc=await EffectiveRule(company.Id,StoresConfigurationRuleKeys.QcCompletionDays,request.ReceivedAt,ct);var qcDays=JsonScalar<int>(qc.NewValueJson);var configJson=CanonicalObject(JsonSerializer.Serialize(new{qcCompletionDays=new{qc.Id,qc.VersionNumber,value=qcDays},capturedAt=request.ReceivedAt},JsonOptions));
        receipt.VendorBillNumber=request.VendorBillNumber.Trim();receipt.VendorBillDate=request.VendorBillDate;receipt.ReceivedAt=request.ReceivedAt;receipt.IsoReceiptVerificationJson=CanonicalObject(request.IsoReceiptVerificationJson);receipt.ConfigurationSnapshotJson=configJson;receipt.ConfigurationSnapshotHash=await JsonbHash(configJson,ct);receipt.QcCompletionDaysConfigVersionId=qc.Id;receipt.QcCompletionDaysSnapshot=qcDays;receipt.QcDueAt=request.ReceivedAt.AddDays(qcDays);receipt.Version++;receipt.UpdatedAt=DateTimeOffset.UtcNow;receipt.UpdatedBy=user.LoginId;receipt.Lines=await BuildLines(receipt,gate,request.Lines,company.Id,actor,ct);
        await db.SaveChangesAsync(ct);await audit.WriteAsync("Stores","UpdateGoodsReceipt",nameof(GoodsReceipt),receipt.Id.ToString(),new{request.Version},new{receipt.Version,Role=role},ct);await tx.CommitAsync(ct);return await LoadResult(receipt.Id,company.Id,false,ct);
    }
    public async Task<GoodsReceiptResult> FinalizeAsync(Guid id,FinalizeGoodsReceiptRequest request,CancellationToken ct)
    {
        var actor=Actor();await RequireReceiptOperatorAsync(ct);var role=ActorRole();var key=Required(request.IdempotencyKey,"IdempotencyKey");await using var tx=await db.Database.BeginTransactionAsync(System.Data.IsolationLevel.Serializable,ct);var company=await Company(ct);
        var receipt=await ReceiptQuery().SingleOrDefaultAsync(x=>x.Id==id&&x.CompanyId==company.Id,ct)??throw new KeyNotFoundException("GRN was not found.");await RequireScope(receipt.PurchaseOrder!,ct);
        var fingerprint=Hash(new{receipt.Id,request.Version,receipt.RequestFingerprint,command="FINALIZE_GRN"});var correlation=Hash($"GRN:FINALIZE:{receipt.Id}:{key}");var result=await ExecuteFinalize(company.Id,receipt.Id,request.Version,key,fingerprint,correlation,actor,role,ct);
        if(!result.Replayed)await audit.WriteAsync("Stores","FinalizeGoodsReceipt",nameof(GoodsReceipt),receipt.Id.ToString(),new{Status="DRAFT",request.Version},new{Status="FINALIZED",Version=request.Version+1,result.StockPostingBatchId,Role=role},ct);
        await tx.CommitAsync(ct);return await LoadResult(receipt.Id,company.Id,result.Replayed,ct);
    }

    public async Task<GoodsReceiptResult> ReverseAsync(Guid id,ReverseGoodsReceiptRequest request,CancellationToken ct)
    {
        var actor=Actor();await RequireReceiptOperatorAsync(ct);var role=ActorRole();var reason=Required(request.Reason,"Reason");var key=Required(request.IdempotencyKey,"IdempotencyKey");var fingerprint=Hash(new{id,request.Version,reason,command="REVERSE_GRN"});var correlation=Hash($"GRN:REVERSE:{id}:{key}");
        await using var tx=await db.Database.BeginTransactionAsync(System.Data.IsolationLevel.Serializable,ct);var company=await Company(ct);var reversalLock=$"STORES:GRN:REVERSE:{company.Id}:{id}";await db.Database.ExecuteSqlInterpolatedAsync($"SELECT pg_advisory_xact_lock(hashtextextended({reversalLock},0))",ct);var original=await ReceiptQuery().SingleOrDefaultAsync(x=>x.Id==id&&x.CompanyId==company.Id,ct)??throw new KeyNotFoundException("GRN was not found.");await RequireScope(original.PurchaseOrder!,ct);
        var replay=await db.GoodsReceipts.AsNoTracking().SingleOrDefaultAsync(x=>x.CompanyId==company.Id&&x.IdempotencyKey==key,ct);if(replay is not null){if(replay.RequestFingerprint!=fingerprint)throw new StoresConflictException("Idempotency key was reused with different GRN reversal data.");await tx.CommitAsync(ct);return await LoadResult(replay.Id,company.Id,true,ct);}
        var reversalNumber=await NextNumber(company.Id,Organization(),DateOnly.FromDateTime(DateTime.UtcNow),ct);var result=await ExecuteReverse(company.Id,id,request.Version,reversalNumber,reason,key,fingerprint,correlation,actor,role,ct);
        if(!result.Replayed)await audit.WriteAsync("Stores","ReverseGoodsReceipt",nameof(GoodsReceipt),result.ReversalGoodsReceiptId.ToString(),new{OriginalGoodsReceiptId=id,request.Version},new{DocumentKind="REVERSAL",result.StockPostingBatchId,Reason=reason,Role=role},ct);
        await tx.CommitAsync(ct);return await LoadResult(result.ReversalGoodsReceiptId,company.Id,result.Replayed,ct);
    }

    public async Task<GoodsReceiptResult?> GetAsync(Guid id,CancellationToken ct)
    {var company=await Company(ct);var receipt=await ReceiptQuery().SingleOrDefaultAsync(x=>x.Id==id&&x.CompanyId==company.Id,ct);if(receipt is null)return null;return await Map(receipt,false,ct);}

    public async Task<GoodsReceiptListResult> ListAsync(string? grnNumber,string? gateEntryNumber,Guid? vendorId,string? status,int page,int pageSize,CancellationToken ct)
    {
        if(page<1||pageSize is <1 or >100)throw new StoresValidationException("page must be positive and pageSize must be 1-100.");var company=await Company(ct);var q=ReceiptQuery().Where(x=>x.CompanyId==company.Id);
        if(!string.IsNullOrWhiteSpace(grnNumber))q=q.Where(x=>x.GrnNumber==grnNumber.Trim().ToUpperInvariant());if(!string.IsNullOrWhiteSpace(gateEntryNumber))q=q.Where(x=>x.GateEntry!.GateEntryNumber==gateEntryNumber.Trim().ToUpperInvariant());if(vendorId.HasValue)q=q.Where(x=>x.VendorId==vendorId);
        if(!string.IsNullOrWhiteSpace(status)){var s=status.Trim().ToUpperInvariant();if(s is not("DRAFT" or "FINALIZED"))throw new StoresValidationException("status must be DRAFT or FINALIZED.");q=q.Where(x=>x.Status==s);}
        var total=await q.CountAsync(ct);var candidates=await q.OrderByDescending(x=>x.ReceivedAt).ThenBy(x=>x.Id).Skip((page-1)*pageSize).Take(pageSize).ToListAsync(ct);var results=new List<GoodsReceiptResult>();foreach(var receipt in candidates)results.Add(await Map(receipt,false,ct));return new(total,page,pageSize,results);
    }

    private async Task<List<GoodsReceiptLine>> BuildLines(GoodsReceipt receipt,GateEntry gate,IReadOnlyList<GoodsReceiptLineRequest> input,Guid companyId,Guid actor,CancellationToken ct)
    {
        if(input is null||input.Count==0)throw new StoresValidationException("GRN requires every Gate Entry line.");if(input.Select(x=>x.GateEntryLineId).Distinct().Count()!=input.Count)throw new StoresValidationException("A Gate Entry line may appear only once.");if(!gate.Lines.Select(x=>x.Id).Order().SequenceEqual(input.Select(x=>x.GateEntryLineId).Order()))throw new StoresValidationException("Every Gate Entry line must map to exactly one GRN line.");
        var threshold=await EffectiveRule(companyId,StoresConfigurationRuleKeys.SerialCaptureThreshold,receipt.ReceivedAt,ct);var thresholdValue=JsonScalar<decimal>(threshold.NewValueJson);var poLines=gate.PurchaseOrder!.Lines.ToDictionary(x=>x.Id);var poLineIds=gate.Lines.Select(x=>x.PurchaseOrderLineId).ToArray();
        var prior=await db.GoodsReceiptLines.Where(x=>poLineIds.Contains(x.PurchaseOrderLineId)&&x.GoodsReceipt!.Status=="FINALIZED"&&x.GoodsReceipt.DocumentKind=="NORMAL"&&!db.GoodsReceipts.Any(r=>r.ReversesGoodsReceiptId==x.GoodsReceiptId&&r.Status=="FINALIZED")).GroupBy(x=>x.PurchaseOrderLineId).Select(x=>new{Id=x.Key,Quantity=x.Sum(y=>y.ReceivedQuantity)}).ToDictionaryAsync(x=>x.Id,x=>x.Quantity,ct);
        var result=new List<GoodsReceiptLine>();var lineNo=0;
        foreach(var row in input){var gateLine=gate.Lines.Single(x=>x.Id==row.GateEntryLineId);var poLine=poLines[gateLine.PurchaseOrderLineId];var item=gateLine.Item??throw new StoresConflictException("Gate Entry Item is unavailable.");if(!item.CategoryId.HasValue||item.Category is null||item.Category.Code.Length!=3)throw new StoresConflictException("GRN Item requires one of the exact three-character category codes.");var priorReceived=prior.GetValueOrDefault(poLine.Id);var remaining=poLine.OrderedQuantity-priorReceived;if(gateLine.DeliveredQuantity>remaining)throw new StoresConflictException($"Gate Entry line {gateLine.LineNumber} exceeds the remaining PO quantity; over-receipt is refused.");
            var on=DateOnly.FromDateTime(receipt.ReceivedAt.UtcDateTime);var route=await db.StoreCategoryRoutes.SingleOrDefaultAsync(x=>x.CompanyId==companyId&&x.ItemCategoryId==item.CategoryId&&x.IsActive&&x.EffectiveFrom<=on&&(x.EffectiveTo==null||x.EffectiveTo>=on),ct)??throw new StoresConflictException($"No effective Stores category route exists for {item.Category.Code}.");var setting=await db.ItemCompanyInventorySettings.SingleOrDefaultAsync(x=>x.CompanyId==companyId&&x.ItemId==item.Id&&x.IsActive,ct);var serialMode=setting?.SerialCaptureMode is "REQUIRED" or "OPTIONAL"?setting.SerialCaptureMode:poLine.UnitRate>thresholdValue?"REQUIRED":"OPTIONAL";var warranty=receipt.VendorBillDate.AddMonths(13);
            var line=new GoodsReceiptLine{CompanyId=companyId,GoodsReceiptId=receipt.Id,GateEntryLineId=gateLine.Id,PurchaseOrderLineId=poLine.Id,LineNumber=++lineNo,ItemId=item.Id,ItemCodeSnapshot=item.ItemCode,ItemNameSnapshot=item.Name,ItemCategoryIdSnapshot=item.CategoryId.Value,ItemCategoryCodeSnapshot=item.Category.Code,HsnSacCodeSnapshot=item.HsnSacCode??string.Empty,GstPercentageSnapshot=item.GstPercentage,ModelSnapshot=item.Model,ManufacturerPartNumberSnapshot=item.PartNumber,ManufacturerMakeSnapshot=item.ManufacturerMake,UomSnapshot=item.Uom,PoOrderedQuantitySnapshot=poLine.OrderedQuantity,PriorEffectiveReceivedQuantitySnapshot=priorReceived,RemainingPoQuantitySnapshot=remaining,DeliveredQuantitySnapshot=gateLine.DeliveredQuantity,ReceivedQuantity=gateLine.DeliveredQuantity,ExcessRejectedQuantity=0,LineValueSnapshot=gateLine.DeliveredQuantity*poLine.UnitRate,UnitRateSnapshot=poLine.UnitRate,SerialThresholdConfigVersionId=threshold.Id,SerialThresholdValueSnapshot=thresholdValue,SerialCaptureModeSnapshot=serialMode,SerialOverrideSettingId=setting?.SerialCaptureMode is "REQUIRED" or "OPTIONAL"?setting.Id:null,QcRouteIdSnapshot=route.Id,QcHoldConditionLocationIdSnapshot=route.QcHoldConditionLocationId,BillWarrantyLimitDate=warranty,InitialWarrantyExpiryDate=warranty,CreatedBy=user.LoginId};line.LotAllocations=await BuildLots(line,receipt.VendorId,row.Lots,companyId,ct);line.Serials=BuildSerials(line,row.Serials,actor);ValidateLineAllocation(line);result.Add(line);}
        return result;
    }
    private async Task<List<GoodsReceiptLineLotAllocation>> BuildLots(GoodsReceiptLine line,Guid vendorId,IReadOnlyList<GoodsReceiptLotRequest> input,Guid companyId,CancellationToken ct)
    {
        if(input is null||input.Count==0)throw new StoresValidationException($"GRN line {line.LineNumber} requires at least one lot allocation.");if(input.Select(x=>x.LotOrdinal).Distinct().Count()!=input.Count||input.Any(x=>x.LotOrdinal<=0||x.Quantity<=0))throw new StoresValidationException($"GRN line {line.LineNumber} lot ordinals must be unique and quantities positive.");var allocations=new List<GoodsReceiptLineLotAllocation>();
        foreach(var row in input.OrderBy(x=>x.LotOrdinal)){if(row.ManufactureDate.HasValue&&row.ExpiryDate.HasValue&&row.ExpiryDate<row.ManufactureDate)throw new StoresValidationException($"GRN line {line.LineNumber} lot {row.LotOrdinal} expiry precedes manufacture.");var supplier=Trim(row.SupplierLotNumber);var manufacturer=Trim(row.ManufacturerLotNumber);var ns=Normalize(supplier);var nm=Normalize(manufacturer);InventoryLot? lot=null;if(ns is not null||nm is not null)lot=await db.InventoryLots.SingleOrDefaultAsync(x=>x.CompanyId==companyId&&x.ItemId==line.ItemId&&x.VendorId==vendorId&&x.NormalizedSupplierLotNumber==ns&&x.NormalizedManufacturerLotNumber==nm&&x.ManufactureDate==row.ManufactureDate&&x.ExpiryDate==row.ExpiryDate,ct);lot??=new InventoryLot{CompanyId=companyId,ItemId=line.ItemId,VendorId=vendorId,SupplierLotNumber=supplier,NormalizedSupplierLotNumber=ns,ManufacturerLotNumber=manufacturer,NormalizedManufacturerLotNumber=nm,ManufactureDate=row.ManufactureDate,ExpiryDate=row.ExpiryDate,CreatedBy=user.LoginId};allocations.Add(new GoodsReceiptLineLotAllocation{CompanyId=companyId,GoodsReceiptLineId=line.Id,InventoryLot=lot,InventoryLotId=lot.Id,LotOrdinal=row.LotOrdinal,Quantity=row.Quantity,CreatedBy=user.LoginId});}return allocations;
    }

    private List<GoodsReceiptLineSerial> BuildSerials(GoodsReceiptLine line,IReadOnlyList<GoodsReceiptSerialRequest> input,Guid actor)
    {
        input??=[];if(input.Select(x=>x.SerialOrdinal).Distinct().Count()!=input.Count||input.Any(x=>x.SerialOrdinal<=0))throw new StoresValidationException($"GRN line {line.LineNumber} serial ordinals must be positive and unique.");var lots=line.LotAllocations.ToDictionary(x=>x.LotOrdinal);var serials=new List<GoodsReceiptLineSerial>();
        foreach(var row in input.OrderBy(x=>x.SerialOrdinal)){if(!lots.TryGetValue(row.LotOrdinal,out var lot))throw new StoresValidationException($"GRN line {line.LineNumber} serial {row.SerialOrdinal} references an unknown lot ordinal.");var entered=Required(row.EnteredSerialNumber,"EnteredSerialNumber");var stored=Required(row.StoredSerialNumber,"StoredSerialNumber");var changed=!string.Equals(entered,stored,StringComparison.Ordinal);if(changed&&(!row.DuplicateWarningAcknowledged||string.IsNullOrWhiteSpace(row.DisambiguationReason)))throw new StoresValidationException("A changed stored serial requires duplicate-warning acknowledgement and a disambiguation reason.");serials.Add(new GoodsReceiptLineSerial{CompanyId=line.CompanyId,GoodsReceiptLineId=line.Id,GoodsReceiptLineLotAllocationId=lot.Id,ItemId=line.ItemId,SerialOrdinal=row.SerialOrdinal,EnteredSerialNumber=entered,StoredSerialNumberSnapshot=stored,ReceiptDisposition="QC_INSPECTION",DisambiguationApplied=changed,DuplicateWarningAcknowledged=row.DuplicateWarningAcknowledged,DisambiguationReason=Trim(row.DisambiguationReason),CapturedByEmployeeId=actor,CapturedAt=DateTimeOffset.UtcNow});}return serials;
    }

    private static void ValidateLineAllocation(GoodsReceiptLine line)
    {if(line.LotAllocations.Sum(x=>x.Quantity)!=line.ReceivedQuantity)throw new StoresValidationException($"GRN line {line.LineNumber} lot quantities must equal the received quantity.");if(line.SerialCaptureModeSnapshot=="REQUIRED"&&(line.ReceivedQuantity!=decimal.Truncate(line.ReceivedQuantity)||line.Serials.Count!=line.ReceivedQuantity))throw new StoresValidationException($"GRN line {line.LineNumber} requires one serial for every received unit.");if(line.SerialCaptureModeSnapshot=="OPTIONAL"&&line.Serials.Count!=0&&line.Serials.Count!=line.ReceivedQuantity)throw new StoresValidationException($"GRN line {line.LineNumber} optional serial capture must be empty or complete.");if(line.Serials.Count>0&&line.LotAllocations.Any(l=>line.Serials.Count(s=>s.GoodsReceiptLineLotAllocationId==l.Id)!=l.Quantity))throw new StoresValidationException($"GRN line {line.LineNumber} serials must reconcile by lot allocation.");}

    private async Task<FinalizeDbResult> ExecuteFinalize(Guid companyId,Guid receiptId,uint version,string key,string fingerprint,string correlation,Guid actor,string role,CancellationToken ct)
    {var connection=(NpgsqlConnection)db.Database.GetDbConnection();await using var command=connection.CreateCommand();command.Transaction=(NpgsqlTransaction?)db.Database.CurrentTransaction?.GetDbTransaction();command.CommandText="SELECT \"StockPostingBatchId\",\"Replayed\" FROM advance.finalize_goods_receipt(@company,@receipt,@version,@key,@fingerprint,@correlation,@actor,@role,@login)";command.Parameters.AddWithValue("company",companyId);command.Parameters.AddWithValue("receipt",receiptId);command.Parameters.AddWithValue("version",(long)version);command.Parameters.AddWithValue("key",key);command.Parameters.AddWithValue("fingerprint",fingerprint);command.Parameters.AddWithValue("correlation",correlation);command.Parameters.AddWithValue("actor",actor);command.Parameters.AddWithValue("role",role);command.Parameters.AddWithValue("login",user.LoginId);await using var reader=await command.ExecuteReaderAsync(ct);if(!await reader.ReadAsync(ct))throw new StoresConflictException("Controlled GRN finalization returned no result.");return new(reader.GetGuid(0),reader.GetBoolean(1));}

    private async Task<ReverseDbResult> ExecuteReverse(Guid companyId,Guid receiptId,uint version,string reversalNumber,string reason,string key,string fingerprint,string correlation,Guid actor,string role,CancellationToken ct)
    {var connection=(NpgsqlConnection)db.Database.GetDbConnection();await using var command=connection.CreateCommand();command.Transaction=(NpgsqlTransaction?)db.Database.CurrentTransaction?.GetDbTransaction();command.CommandText="SELECT \"ReversalGoodsReceiptId\",\"StockPostingBatchId\",\"Replayed\" FROM advance.reverse_goods_receipt(@company,@receipt,@version,@number,@reason,@key,@fingerprint,@correlation,@actor,@role,@login)";command.Parameters.AddWithValue("company",companyId);command.Parameters.AddWithValue("receipt",receiptId);command.Parameters.AddWithValue("version",(long)version);command.Parameters.AddWithValue("number",reversalNumber);command.Parameters.AddWithValue("reason",reason);command.Parameters.AddWithValue("key",key);command.Parameters.AddWithValue("fingerprint",fingerprint);command.Parameters.AddWithValue("correlation",correlation);command.Parameters.AddWithValue("actor",actor);command.Parameters.AddWithValue("role",role);command.Parameters.AddWithValue("login",user.LoginId);await using var reader=await command.ExecuteReaderAsync(ct);if(!await reader.ReadAsync(ct))throw new StoresConflictException("Controlled GRN reversal returned no result.");return new(reader.GetGuid(0),reader.GetGuid(1),reader.GetBoolean(2));}

    private IQueryable<GateEntry> GateQuery()=>db.GateEntries.AsNoTracking().Include(x=>x.Vendor).Include(x=>x.Lines).ThenInclude(x=>x.Item).ThenInclude(x=>x!.Category).Include(x=>x.PurchaseOrder).ThenInclude(x=>x!.Lines);
    private IQueryable<GoodsReceipt> ReceiptQuery(bool tracking=false){var q=db.GoodsReceipts.Include(x=>x.GateEntry).Include(x=>x.PurchaseOrder).Include(x=>x.Vendor).Include(x=>x.Lines).ThenInclude(x=>x.LotAllocations).ThenInclude(x=>x.InventoryLot).Include(x=>x.Lines).ThenInclude(x=>x.Serials);return tracking?q:q.AsNoTracking();}
    private async Task<GoodsReceiptResult> LoadResult(Guid id,Guid companyId,bool replayed,CancellationToken ct)=>await Map(await ReceiptQuery().SingleAsync(x=>x.Id==id&&x.CompanyId==companyId,ct),replayed,ct);

    private async Task<GoodsReceiptResult> Map(GoodsReceipt x,bool replayed,CancellationToken ct)
    {
        var histories=await db.StoresDocumentStatusHistories.AsNoTracking().Where(h=>h.GoodsReceiptId==x.Id).OrderBy(h=>h.OccurredAt).Select(h=>new GoodsReceiptHistoryResult(h.FromStatus,h.ToStatus,h.Action,h.ActorEmployeeId,h.ActorRoleCode,h.OccurredAt)).ToListAsync(ct);var batch=x.DocumentKind=="NORMAL"?await db.StockPostingBatches.AsNoTracking().Where(b=>b.GoodsReceiptId==x.Id&&b.PostingKind=="GRN_CUSTODY").Select(b=>(Guid?)b.Id).SingleOrDefaultAsync(ct):await db.StockPostingBatches.AsNoTracking().Where(b=>b.PostingKind=="REVERSAL"&&db.StockPostingBatches.Any(original=>original.Id==b.ReversesPostingBatchId&&original.GoodsReceiptId==x.ReversesGoodsReceiptId)).Select(b=>(Guid?)b.Id).SingleOrDefaultAsync(ct);var stored=x.Lines.SelectMany(l=>l.Serials).Select(s=>Normalize(s.StoredSerialNumberSnapshot)).Where(s=>s is not null).ToList();var duplicates=stored.GroupBy(s=>s).Where(g=>g.Count()>1).Select(g=>g.Key!).ToHashSet(StringComparer.Ordinal);var ownSerialIds=x.Lines.SelectMany(l=>l.Serials).Where(s=>s.InventorySerialId.HasValue).Select(s=>s.InventorySerialId!.Value).ToArray();var existing=await db.InventorySerials.AsNoTracking().Where(s=>s.CompanyId==x.CompanyId&&stored.Contains(s.NormalizedStoredSerialNumber)&&!ownSerialIds.Contains(s.Id)).Select(s=>s.NormalizedStoredSerialNumber).ToListAsync(ct);duplicates.UnionWith(existing);var warnings=duplicates.Order().Select(s=>$"Duplicate serial '{s}' must be made unique before finalization.").ToList();
        return new(x.Id,x.GrnNumber,x.DocumentKind,x.ReversesGoodsReceiptId,x.ReversalReason,x.GateEntry!.GateEntryNumber,x.GateEntryId,x.PurchaseOrder!.PoNumber,x.PurchaseOrderId,x.VendorId,x.VendorNameSnapshot,x.VendorBillNumber,x.VendorBillDate,x.VendorDcNumberSnapshot,x.ModeOfTransportSnapshot,x.ReceivedAt,x.IsoReceiptVerificationJson,x.Status,x.Version,batch,replayed,warnings,x.Lines.OrderBy(l=>l.LineNumber).Select(l=>new GoodsReceiptLineResult(l.Id,l.LineNumber,l.GateEntryLineId,l.PurchaseOrderLineId,l.ItemId,l.ItemCodeSnapshot,l.ItemNameSnapshot,l.ItemCategoryCodeSnapshot,l.HsnSacCodeSnapshot,l.GstPercentageSnapshot,l.ModelSnapshot,l.ManufacturerPartNumberSnapshot,l.UomSnapshot,l.ReceivedQuantity,l.UnitRateSnapshot,l.SerialCaptureModeSnapshot,l.InitialWarrantyExpiryDate,l.QcHoldConditionLocationIdSnapshot,l.LotAllocations.OrderBy(a=>a.LotOrdinal).Select(a=>new GoodsReceiptLotResult(a.Id,a.InventoryLotId,a.LotOrdinal,a.Quantity,a.InventoryLot!.SupplierLotNumber,a.InventoryLot.ManufacturerLotNumber,a.InventoryLot.ManufactureDate,a.InventoryLot.ExpiryDate)).ToList(),l.Serials.OrderBy(s=>s.SerialOrdinal).Select(s=>new GoodsReceiptSerialResult(s.Id,s.InventorySerialId,s.SerialOrdinal,l.LotAllocations.Single(a=>a.Id==s.GoodsReceiptLineLotAllocationId).LotOrdinal,s.EnteredSerialNumber,s.StoredSerialNumberSnapshot,s.DuplicateWarningAcknowledged,s.DisambiguationReason)).ToList())).ToList(),histories);
    }
    private async Task<BusinessRuleConfigurationVersion> EffectiveRule(Guid companyId,string key,DateTimeOffset at,CancellationToken ct)=>await db.BusinessRuleConfigurationVersions.Where(x=>x.CompanyId==companyId&&x.RuleKey==key&&x.EffectiveFrom<=at).OrderByDescending(x=>x.EffectiveFrom).ThenByDescending(x=>x.VersionNumber).FirstOrDefaultAsync(ct)??throw new StoresConflictException($"No effective {key} configuration exists.");
    private async Task<string> NextNumber(Guid companyId,string org,DateOnly date,CancellationToken ct){var year=date.Month>=4?$"{date.Year%100:00}-{(date.Year+1)%100:00}":$"{(date.Year-1)%100:00}-{date.Year%100:00}";var numberLock=$"NUMBER:{org}:{year}:GRN";await db.Database.ExecuteSqlInterpolatedAsync($"SELECT pg_advisory_xact_lock(hashtextextended({numberLock},0))",ct);var seq=await db.PurchaseNumberSequences.SingleOrDefaultAsync(x=>x.CompanyId==companyId&&x.OrganizationId==org&&x.FinancialYear==year&&x.Prefix=="GRN"&&x.IsActive,ct);if(seq is null){seq=new PurchaseNumberSequence{CompanyId=companyId,OrganizationId=org,FinancialYear=year,Prefix="GRN",CreatedBy=user.LoginId};db.PurchaseNumberSequences.Add(seq);}seq.LastNumber++;seq.UpdatedAt=DateTimeOffset.UtcNow;seq.UpdatedBy=user.LoginId;return $"GRN-{year}-{seq.LastNumber:000001}";}
    private void AddHistory(GoodsReceipt receipt,string? from,string to,string action,string correlation,string role)=>db.StoresDocumentStatusHistories.Add(new StoresDocumentStatusHistory{CompanyId=receipt.CompanyId,GoodsReceiptId=receipt.Id,FromStatus=from,ToStatus=to,Action=action,ActorEmployeeId=Actor(),ActorRoleCode=role,OccurredAt=DateTimeOffset.UtcNow,CorrelationId=correlation});
    private async Task RequireScope(PurchaseOrder po,CancellationToken ct){var d=await scopes.AuthorizeAsync(Actor(),ActorRole(),Target(po),DateOnly.FromDateTime(DateTime.UtcNow),ct);if(!d.Allowed)throw new UnauthorizedAccessException("GRN record scope is denied.");}
    private RecordScopeTarget Target(PurchaseOrder po)=>new(Organization(),po.RequestingDepartmentId,po.DeliveryWarehouseId,null,po.OwnerEmployeeId);
    private async Task<Company> Company(CancellationToken ct)=>await db.Companies.SingleOrDefaultAsync(x=>x.Code==Organization()&&x.IsActive&&x.Status=="ACTIVE",ct)??throw new UnauthorizedAccessException("Selected company is unavailable.");
    private Guid Actor()=>user.IsAuthenticated&&user.EmployeeId.HasValue?user.EmployeeId.Value:throw new UnauthorizedAccessException("A resolved employee identity is required.");
    private string ActorRole(){foreach(var role in new[]{"STORES_EXECUTIVE","STORES_ASSISTANT"})if(string.Equals(user.ActingRoleCode,role,StringComparison.OrdinalIgnoreCase))return role;throw new UnauthorizedAccessException("A Stores receipt operational role is required.");}
    private async Task RequireReceiptOperatorAsync(CancellationToken ct){var code=await db.Employees.AsNoTracking().Where(x=>x.Id==Actor()).Select(x=>x.EmployeeCode).SingleOrDefaultAsync(ct);if(code is not("SESS-16" or "SESS-35" or "SESS-41"))throw new UnauthorizedAccessException("GRN is restricted to the three settled receipt operators.");}
    private string Organization()=>!string.IsNullOrWhiteSpace(user.OrganizationId)?user.OrganizationId.Trim().ToUpperInvariant():throw new UnauthorizedAccessException("Company scope is required.");
    private static void ValidateHeader(string bill,DateOnly date,DateTimeOffset received,string iso,IReadOnlyList<GoodsReceiptLineRequest> lines){Required(bill,"VendorBillNumber");if(date==default)throw new StoresValidationException("VendorBillDate is required.");if(received==default)throw new StoresValidationException("ReceivedAt is required.");CanonicalObject(iso);if(lines is null)throw new StoresValidationException("Lines are required.");}
    private static object CanonicalLines(IReadOnlyList<GoodsReceiptLineRequest> lines)=>lines.OrderBy(x=>x.GateEntryLineId).Select(x=>new{x.GateEntryLineId,Lots=x.Lots.OrderBy(l=>l.LotOrdinal),Serials=x.Serials.OrderBy(s=>s.SerialOrdinal)});
    private async Task<string> JsonbHash(string json,CancellationToken ct)=>await db.Database.SqlQuery<string>($"SELECT encode(digest(convert_to({json}::jsonb::text,'UTF8'),'sha256'),'hex') AS \"Value\"").SingleAsync(ct);
    private static T JsonScalar<T>(string json){using var doc=JsonDocument.Parse(json);return JsonSerializer.Deserialize<T>(doc.RootElement.GetRawText(),JsonOptions)!;}
    private static string CanonicalObject(string value){try{using var doc=JsonDocument.Parse(Required(value,"JSON"));if(doc.RootElement.ValueKind!=JsonValueKind.Object)throw new StoresValidationException("JSON value must be an object.");return JsonSerializer.Serialize(doc.RootElement,JsonOptions);}catch(JsonException){throw new StoresValidationException("JSON value must be valid JSON.");}}
    private static string Hash(object value)=>Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(value is string s?s:JsonSerializer.Serialize(value,JsonOptions)))).ToLowerInvariant();
    private static string Required(string? value,string name)=>!string.IsNullOrWhiteSpace(value)?value.Trim():throw new StoresValidationException($"{name} is required.");
    private static string? Trim(string? value)=>string.IsNullOrWhiteSpace(value)?null:value.Trim();
    private static string? Normalize(string? value)=>Trim(value) is{ }v?string.Join(' ',v.Split((char[]?)null,StringSplitOptions.RemoveEmptyEntries)).ToUpperInvariant():null;
    private sealed record FinalizeDbResult(Guid StockPostingBatchId,bool Replayed);
    private sealed record ReverseDbResult(Guid ReversalGoodsReceiptId,Guid StockPostingBatchId,bool Replayed);
}
